-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#1c1810",
    base01 = "#2a261c",
    base02 = "#3a3527",
    base03 = "#504b38",
    base04 = "#5f5b45",
    base05 = "#736e55",
    base06 = "#bab696",
    base07 = "#f8f5de",
    base08 = "#e35142",
    base09 = "#fba11b",
    base0A = "#f2ff27",
    base0B = "#5ceb5a",
    base0C = "#5aebbc",
    base0D = "#489bf0",
    base0E = "#ff8080",
    base0F = "#f69be7",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#1c1810",
            bright = "#2a261c",
        },
        gray = {
            dim = "#3a3527",
            normal = "#504b38",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#5f5b45",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#bab696",
            normal = "#736e55",
            bright = "#f8f5de",
        },
        red = { normal = "#e35142", bright = "#e35142" },
        orange = { normal = "#fba11b", bright = "#fba11b" },
        yellow = { normal = "#f2ff27", bright = "#f2ff27" },
        green = { normal = "#5ceb5a", bright = "#5ceb5a" },
        cyan = { normal = "#5aebbc", bright = "#5aebbc" },
        blue = { normal = "#489bf0", bright = "#489bf0" },
        magenta = { normal = "#ff8080", bright = "#ff8080" },
        brown = { normal = "#f69be7" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#1c1810" },
            foreground = { normal = "#736e55" },
        },
        cursor = {
            background = { normal = "#736e55" },
            foreground = { normal = "#1c1810" },
        },
        gutter = { foreground = "#3a3527" },
        border = { normal = "#504b38" },
        chrome = {
            background = {
                normal = "#3a3527",
                dark = "#2a261c",
            },
            foreground = {
                normal = "#736e55",
                dark = "#5f5b45",
            },
        },
        selection = { background = "#2a261c" },
        highlight = {
            line = { background = "#2a261c" },
            text = { background = "#3a3527" },
            search = {
                background = "#2a261c",
                foreground = "#f2ff27",
            },
        },
        status = {
            error = "#e35142",
            warning = "#fba11b",
            info = "#f2ff27",
            success = "#5ceb5a",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#504b38",

        string = {
            default = "#5ceb5a",
            regexp = "#5ceb5a",
            other = "#5ceb5a",
        },

        constant = {
            default = "#fba11b",
            character = {
                default = "#e35142",
                escape = "#5aebbc",
            },
            language = "#fba11b",
            numeric = {
                default = "#fba11b",
                float = "#fba11b",
            },
        },

        entity = {
            name = {
                class = "#f2ff27",
                type = "#f2ff27",
                ["function"] = {
                    default = "#489bf0",
                    constructor = "#489bf0",
                },
                label = "#f2ff27",
                namespace = "#e35142",
                tag = "#f2ff27",
            },
            other = {
                ["attribute-name"] = "#f2ff27",
            },
        },

        keyword = {
            default = "#ff8080",
            control = {
                default = "#ff8080",
                import = "#489bf0",
                flow = "#f2ff27",
            },
            operator = "#ff8080",
            declaration = "#ff8080",
        },

        storage = {
            type = "#ff8080",
            modifier = "#f2ff27",
        },

        variable = {
            default = "#736e55",
            parameter = "#736e55",
            other = {
                property = "#736e55",
            },
        },

        punctuation = {
            separator = "#f69be7",
            section = "#f69be7",
        },

        markup = {
            default = "#736e55",
            heading = "#489bf0",
            raw = "#fba11b",
            link = "#fba11b",
            list = "#f2ff27",
            inserted = "#5ceb5a",
            deleted = "#e35142",
        },

        meta = {
            preprocessor = "#f2ff27",
        },
    },
}
