-- Auto-generated by tinted-builder-rust from a base24 scheme.
-- Translates base24 slots into tinted8-shaped keys. Mirrors base16.lua.mustache
-- exactly, plus brights from base12-17 and DiagnosticOk = bright_green.
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base24 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#1c2836",
    base01 = "#000000",
    base02 = "#555555",
    base03 = "#6e6e6e",
    base04 = "#888888",
    base05 = "#a1a1a1",
    base06 = "#bbbbbb",
    base07 = "#ffffff",
    base08 = "#f9555f",
    base09 = "#fdba29",
    base0A = "#fdf029",
    base0B = "#20af89",
    base0C = "#1e9ee6",
    base0D = "#589cf5",
    base0E = "#934d95",
    base0F = "#7c2a2f",
    base10 = "#383838",
    base11 = "#1c1c1c",
    base12 = "#fa8b8e",
    base13 = "#ffff55",
    base14 = "#34bb99",
    base15 = "#3978bb",
    base16 = "#589cf5",
    base17 = "#e75598",

    palette = {
        black = {
            normal = "#1c2836",
            bright = "#000000",
        },
        gray = {
            dim = "#555555",
            normal = "#6e6e6e",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#888888",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#bbbbbb",
            normal = "#a1a1a1",
            bright = "#ffffff",
        },
        red = { normal = "#f9555f", bright = "#fa8b8e" },
        -- base24 has no bright_orange slot; orange.bright falls back to .normal.
        orange = { normal = "#fdba29", bright = "#fdba29" },
        yellow = { normal = "#fdf029", bright = "#ffff55" },
        green = { normal = "#20af89", bright = "#34bb99" },
        cyan = { normal = "#1e9ee6", bright = "#3978bb" },
        blue = { normal = "#589cf5", bright = "#589cf5" },
        magenta = { normal = "#934d95", bright = "#e75598" },
        brown = { normal = "#7c2a2f" },
    },

    ui = {
        global = {
            background = { normal = "#1c2836" },
            foreground = { normal = "#a1a1a1" },
        },
        cursor = {
            background = { normal = "#a1a1a1" },
            foreground = { normal = "#1c2836" },
        },
        gutter = { foreground = "#555555" },
        border = { normal = "#6e6e6e" },
        chrome = {
            background = {
                normal = "#555555",
                dark = "#000000",
            },
            foreground = {
                normal = "#a1a1a1",
                dark = "#888888",
            },
        },
        selection = { background = "#000000" },
        highlight = {
            line = { background = "#000000" },
            text = { background = "#555555" },
            search = {
                background = "#000000",
                foreground = "#fdf029",
            },
        },
        status = {
            error = "#f9555f",
            warning = "#fdba29",
            info = "#fdf029",
            -- DiagnosticOk uses bright_green (base14) in current code; preserve.
            success = "#34bb99",
        },
    },

    syntax = {
        comment = "#6e6e6e",

        string = {
            default = "#20af89",
            regexp = "#20af89",
            other = "#20af89",
        },

        constant = {
            default = "#fdba29",
            character = {
                default = "#f9555f",
                escape = "#1e9ee6",
            },
            language = "#fdba29",
            numeric = {
                default = "#fdba29",
                float = "#fdba29",
            },
        },

        entity = {
            name = {
                class = "#fdf029",
                type = "#fdf029",
                ["function"] = {
                    default = "#589cf5",
                    constructor = "#589cf5",
                },
                label = "#fdf029",
                namespace = "#f9555f",
                tag = "#fdf029",
            },
            other = {
                ["attribute-name"] = "#fdf029",
            },
        },

        keyword = {
            default = "#934d95",
            control = {
                default = "#934d95",
                import = "#589cf5",
                flow = "#fdf029",
            },
            operator = "#934d95",
            declaration = "#934d95",
        },

        storage = {
            type = "#934d95",
            modifier = "#fdf029",
        },

        variable = {
            default = "#a1a1a1",
            parameter = "#a1a1a1",
            other = {
                property = "#a1a1a1",
            },
        },

        punctuation = {
            separator = "#7c2a2f",
            section = "#7c2a2f",
        },

        markup = {
            default = "#a1a1a1",
            heading = "#589cf5",
            raw = "#fdba29",
            link = "#fdba29",
            list = "#fdf029",
            inserted = "#20af89",
            deleted = "#f9555f",
        },

        meta = {
            preprocessor = "#fdf029",
        },
    },
}
