-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "light",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#cabda0",
    base01 = "#bcad8c",
    base02 = "#af9f7d",
    base03 = "#645538",
    base04 = "#110e06",
    base05 = "#382e1b",
    base06 = "#4b3e26",
    base07 = "#bcad8c",
    base08 = "#382e1b",
    base09 = "#110e06",
    base0A = "#110e06",
    base0B = "#110e06",
    base0C = "#110e06",
    base0D = "#251e0f",
    base0E = "#382e1b",
    base0F = "#4b3e26",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#cabda0",
            bright = "#bcad8c",
        },
        gray = {
            dim = "#af9f7d",
            normal = "#645538",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#110e06",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#4b3e26",
            normal = "#382e1b",
            bright = "#bcad8c",
        },
        red = { normal = "#382e1b", bright = "#382e1b" },
        orange = { normal = "#110e06", bright = "#110e06" },
        yellow = { normal = "#110e06", bright = "#110e06" },
        green = { normal = "#110e06", bright = "#110e06" },
        cyan = { normal = "#110e06", bright = "#110e06" },
        blue = { normal = "#251e0f", bright = "#251e0f" },
        magenta = { normal = "#382e1b", bright = "#382e1b" },
        brown = { normal = "#4b3e26" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#cabda0" },
            foreground = { normal = "#382e1b" },
        },
        cursor = {
            background = { normal = "#382e1b" },
            foreground = { normal = "#cabda0" },
        },
        gutter = { foreground = "#af9f7d" },
        border = { normal = "#645538" },
        chrome = {
            background = {
                normal = "#af9f7d",
                dark = "#bcad8c",
            },
            foreground = {
                normal = "#382e1b",
                dark = "#110e06",
            },
        },
        selection = { background = "#bcad8c" },
        highlight = {
            line = { background = "#bcad8c" },
            text = { background = "#af9f7d" },
            search = {
                background = "#bcad8c",
                foreground = "#110e06",
            },
        },
        status = {
            error = "#382e1b",
            warning = "#110e06",
            info = "#110e06",
            success = "#110e06",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#645538",

        string = {
            default = "#110e06",
            regexp = "#110e06",
            other = "#110e06",
        },

        constant = {
            default = "#110e06",
            character = {
                default = "#382e1b",
                escape = "#110e06",
            },
            language = "#110e06",
            numeric = {
                default = "#110e06",
                float = "#110e06",
            },
        },

        entity = {
            name = {
                class = "#110e06",
                type = "#110e06",
                ["function"] = {
                    default = "#251e0f",
                    constructor = "#251e0f",
                },
                label = "#110e06",
                namespace = "#382e1b",
                tag = "#110e06",
            },
            other = {
                ["attribute-name"] = "#110e06",
            },
        },

        keyword = {
            default = "#382e1b",
            control = {
                default = "#382e1b",
                import = "#251e0f",
                flow = "#110e06",
            },
            operator = "#382e1b",
            declaration = "#382e1b",
        },

        storage = {
            type = "#382e1b",
            modifier = "#110e06",
        },

        variable = {
            default = "#382e1b",
            parameter = "#382e1b",
            other = {
                property = "#382e1b",
            },
        },

        punctuation = {
            separator = "#4b3e26",
            section = "#4b3e26",
        },

        markup = {
            default = "#382e1b",
            heading = "#251e0f",
            raw = "#110e06",
            link = "#110e06",
            list = "#110e06",
            inserted = "#110e06",
            deleted = "#382e1b",
        },

        meta = {
            preprocessor = "#110e06",
        },
    },
}
