-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#0e3c46",
    base01 = "#1d494e",
    base02 = "#2a5054",
    base03 = "#587073",
    base04 = "#9dc8cd",
    base05 = "#c7dbdd",
    base06 = "#cbf2f7",
    base07 = "#d2faff",
    base08 = "#fb6953",
    base09 = "#fcab74",
    base0A = "#fce380",
    base0B = "#73d8ad",
    base0C = "#3fb2b9",
    base0D = "#46bddd",
    base0E = "#756b8a",
    base0F = "#9b647b",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#0e3c46",
            bright = "#1d494e",
        },
        gray = {
            dim = "#2a5054",
            normal = "#587073",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#9dc8cd",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#cbf2f7",
            normal = "#c7dbdd",
            bright = "#d2faff",
        },
        red = { normal = "#fb6953", bright = "#fb6953" },
        orange = { normal = "#fcab74", bright = "#fcab74" },
        yellow = { normal = "#fce380", bright = "#fce380" },
        green = { normal = "#73d8ad", bright = "#73d8ad" },
        cyan = { normal = "#3fb2b9", bright = "#3fb2b9" },
        blue = { normal = "#46bddd", bright = "#46bddd" },
        magenta = { normal = "#756b8a", bright = "#756b8a" },
        brown = { normal = "#9b647b" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#0e3c46" },
            foreground = { normal = "#c7dbdd" },
        },
        cursor = {
            background = { normal = "#c7dbdd" },
            foreground = { normal = "#0e3c46" },
        },
        gutter = { foreground = "#2a5054" },
        border = { normal = "#587073" },
        chrome = {
            background = {
                normal = "#2a5054",
                dark = "#1d494e",
            },
            foreground = {
                normal = "#c7dbdd",
                dark = "#9dc8cd",
            },
        },
        selection = { background = "#1d494e" },
        highlight = {
            line = { background = "#1d494e" },
            text = { background = "#2a5054" },
            search = {
                background = "#1d494e",
                foreground = "#fce380",
            },
        },
        status = {
            error = "#fb6953",
            warning = "#fcab74",
            info = "#fce380",
            success = "#73d8ad",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#587073",

        string = {
            default = "#73d8ad",
            regexp = "#73d8ad",
            other = "#73d8ad",
        },

        constant = {
            default = "#fcab74",
            character = {
                default = "#fb6953",
                escape = "#3fb2b9",
            },
            language = "#fcab74",
            numeric = {
                default = "#fcab74",
                float = "#fcab74",
            },
        },

        entity = {
            name = {
                class = "#fce380",
                type = "#fce380",
                ["function"] = {
                    default = "#46bddd",
                    constructor = "#46bddd",
                },
                label = "#fce380",
                namespace = "#fb6953",
                tag = "#fce380",
            },
            other = {
                ["attribute-name"] = "#fce380",
            },
        },

        keyword = {
            default = "#756b8a",
            control = {
                default = "#756b8a",
                import = "#46bddd",
                flow = "#fce380",
            },
            operator = "#756b8a",
            declaration = "#756b8a",
        },

        storage = {
            type = "#756b8a",
            modifier = "#fce380",
        },

        variable = {
            default = "#c7dbdd",
            parameter = "#c7dbdd",
            other = {
                property = "#c7dbdd",
            },
        },

        punctuation = {
            separator = "#9b647b",
            section = "#9b647b",
        },

        markup = {
            default = "#c7dbdd",
            heading = "#46bddd",
            raw = "#fcab74",
            link = "#fcab74",
            list = "#fce380",
            inserted = "#73d8ad",
            deleted = "#fb6953",
        },

        meta = {
            preprocessor = "#fce380",
        },
    },
}
