-- Auto-generated by tinted-builder-rust from a base24 scheme.
-- Translates base24 slots into tinted8-shaped keys. Mirrors base16.lua.mustache
-- exactly, plus brights from base12-17 and DiagnosticOk = bright_green.
-- Do not edit by hand.

return {
    variant = "light",

    -- Legacy base24 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#ffffff",
    base01 = "#000000",
    base02 = "#545753",
    base03 = "#6b6d6a",
    base04 = "#838482",
    base05 = "#9a9b9a",
    base06 = "#b2b2b2",
    base07 = "#ededec",
    base08 = "#f72729",
    base09 = "#f96f1c",
    base0A = "#156ffe",
    base0B = "#32895c",
    base0C = "#32c2c0",
    base0D = "#125ccf",
    base0E = "#9f00bc",
    base0F = "#7b1314",
    base10 = "#383a37",
    base11 = "#1c1d1b",
    base12 = "#fb0416",
    base13 = "#fcd627",
    base14 = "#2cc631",
    base15 = "#39d5ce",
    base16 = "#156ffe",
    base17 = "#e800b0",

    palette = {
        black = {
            normal = "#ffffff",
            bright = "#000000",
        },
        gray = {
            dim = "#545753",
            normal = "#6b6d6a",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#838482",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#b2b2b2",
            normal = "#9a9b9a",
            bright = "#ededec",
        },
        red     = { normal = "#f72729", bright = "#fb0416" },
        -- base24 has no bright_orange slot; orange.bright falls back to .normal.
        orange  = { normal = "#f96f1c", bright = "#f96f1c" },
        yellow  = { normal = "#156ffe", bright = "#fcd627" },
        green   = { normal = "#32895c", bright = "#2cc631" },
        cyan    = { normal = "#32c2c0", bright = "#39d5ce" },
        blue    = { normal = "#125ccf", bright = "#156ffe" },
        magenta = { normal = "#9f00bc", bright = "#e800b0" },
        brown   = { normal = "#7b1314" },
    },

    ui = {
        global = {
            background = { normal = "#ffffff" },
            foreground = { normal = "#9a9b9a" },
        },
        cursor = {
            background = { normal = "#9a9b9a" },
            foreground = { normal = "#ffffff" },
        },
        gutter = { foreground = "#545753" },
        border = { normal = "#6b6d6a" },
        chrome = {
            background = {
                normal = "#545753",
                dark = "#000000",
            },
            foreground = {
                normal = "#9a9b9a",
                dark = "#838482",
            },
        },
        selection = { background = "#000000" },
        highlight = {
            line = { background = "#000000" },
            text = { background = "#545753" },
            search = {
                background = "#000000",
                foreground = "#156ffe",
            },
        },
        status = {
            error = "#f72729",
            warning = "#f96f1c",
            info = "#156ffe",
            -- DiagnosticOk uses bright_green (base14) in current code; preserve.
            success = "#2cc631",
        },
    },

    syntax = {
        comment = "#6b6d6a",

        string = {
            default = "#32895c",
            regexp = "#32895c",
            other = "#32895c",
        },

        constant = {
            default = "#f96f1c",
            character = {
                default = "#f72729",
                escape = "#32c2c0",
            },
            language = "#f96f1c",
            numeric = {
                default = "#f96f1c",
                float = "#f96f1c",
            },
        },

        entity = {
            name = {
                class = "#156ffe",
                type = "#156ffe",
                ["function"] = {
                    default = "#125ccf",
                    constructor = "#125ccf",
                },
                label = "#156ffe",
                namespace = "#f72729",
                tag = "#156ffe",
            },
            other = {
                ["attribute-name"] = "#156ffe",
            },
        },

        keyword = {
            default = "#9f00bc",
            control = {
                default = "#9f00bc",
                import = "#125ccf",
                flow = "#156ffe",
            },
            operator = "#9f00bc",
            declaration = "#9f00bc",
        },

        storage = {
            type = "#9f00bc",
            modifier = "#156ffe",
        },

        variable = {
            default = "#9a9b9a",
            parameter = "#9a9b9a",
            other = {
                property = "#9a9b9a",
            },
        },

        punctuation = {
            separator = "#7b1314",
            section = "#7b1314",
        },

        markup = {
            default = "#9a9b9a",
            heading = "#125ccf",
            raw = "#f96f1c",
            link = "#f96f1c",
            list = "#156ffe",
            inserted = "#32895c",
            deleted = "#f72729",
        },

        meta = {
            preprocessor = "#156ffe",
        },
    },
}
