-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#2e2a31",
    base01 = "#4a464d",
    base02 = "#666369",
    base03 = "#838085",
    base04 = "#9f9da2",
    base05 = "#bcbabe",
    base06 = "#d8d7da",
    base07 = "#f5f4f7",
    base08 = "#d8137f",
    base09 = "#d65407",
    base0A = "#dc8a0e",
    base0B = "#17ad98",
    base0C = "#149bda",
    base0D = "#796af5",
    base0E = "#bb60ea",
    base0F = "#c720ca",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#2e2a31",
            bright = "#4a464d",
        },
        gray = {
            dim = "#666369",
            normal = "#838085",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#9f9da2",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#d8d7da",
            normal = "#bcbabe",
            bright = "#f5f4f7",
        },
        red = { normal = "#d8137f", bright = "#d8137f" },
        orange = { normal = "#d65407", bright = "#d65407" },
        yellow = { normal = "#dc8a0e", bright = "#dc8a0e" },
        green = { normal = "#17ad98", bright = "#17ad98" },
        cyan = { normal = "#149bda", bright = "#149bda" },
        blue = { normal = "#796af5", bright = "#796af5" },
        magenta = { normal = "#bb60ea", bright = "#bb60ea" },
        brown = { normal = "#c720ca" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#2e2a31" },
            foreground = { normal = "#bcbabe" },
        },
        cursor = {
            background = { normal = "#bcbabe" },
            foreground = { normal = "#2e2a31" },
        },
        gutter = { foreground = "#666369" },
        border = { normal = "#838085" },
        chrome = {
            background = {
                normal = "#666369",
                dark = "#4a464d",
            },
            foreground = {
                normal = "#bcbabe",
                dark = "#9f9da2",
            },
        },
        selection = { background = "#4a464d" },
        highlight = {
            line = { background = "#4a464d" },
            text = { background = "#666369" },
            search = {
                background = "#4a464d",
                foreground = "#dc8a0e",
            },
        },
        status = {
            error = "#d8137f",
            warning = "#d65407",
            info = "#dc8a0e",
            success = "#17ad98",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#838085",

        string = {
            default = "#17ad98",
            regexp = "#17ad98",
            other = "#17ad98",
        },

        constant = {
            default = "#d65407",
            character = {
                default = "#d8137f",
                escape = "#149bda",
            },
            language = "#d65407",
            numeric = {
                default = "#d65407",
                float = "#d65407",
            },
        },

        entity = {
            name = {
                class = "#dc8a0e",
                type = "#dc8a0e",
                ["function"] = {
                    default = "#796af5",
                    constructor = "#796af5",
                },
                label = "#dc8a0e",
                namespace = "#d8137f",
                tag = "#dc8a0e",
            },
            other = {
                ["attribute-name"] = "#dc8a0e",
            },
        },

        keyword = {
            default = "#bb60ea",
            control = {
                default = "#bb60ea",
                import = "#796af5",
                flow = "#dc8a0e",
            },
            operator = "#bb60ea",
            declaration = "#bb60ea",
        },

        storage = {
            type = "#bb60ea",
            modifier = "#dc8a0e",
        },

        variable = {
            default = "#bcbabe",
            parameter = "#bcbabe",
            other = {
                property = "#bcbabe",
            },
        },

        punctuation = {
            separator = "#c720ca",
            section = "#c720ca",
        },

        markup = {
            default = "#bcbabe",
            heading = "#796af5",
            raw = "#d65407",
            link = "#d65407",
            list = "#dc8a0e",
            inserted = "#17ad98",
            deleted = "#d8137f",
        },

        meta = {
            preprocessor = "#dc8a0e",
        },
    },
}
