-- Auto-generated by tinted-builder-rust from a base24 scheme.
-- Translates base24 slots into tinted8-shaped keys. Mirrors base16.lua.mustache
-- exactly, plus brights from base12-17 and DiagnosticOk = bright_green.
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base24 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#1d1f28",
    base01 = "#282a36",
    base02 = "#414458",
    base03 = "#707281",
    base04 = "#9fa0aa",
    base05 = "#ceced3",
    base06 = "#fdfdfd",
    base07 = "#bebec1",
    base08 = "#f37f97",
    base09 = "#f2a272",
    base0A = "#556fff",
    base0B = "#5adecd",
    base0C = "#79e6f3",
    base0D = "#8897f4",
    base0E = "#c574dd",
    base0F = "#793f4b",
    base10 = "#2b2d3a",
    base11 = "#15161d",
    base12 = "#ff4971",
    base13 = "#ff8037",
    base14 = "#18e3c8",
    base15 = "#3fdcee",
    base16 = "#556fff",
    base17 = "#b043d1",

    palette = {
        black = {
            normal = "#1d1f28",
            bright = "#282a36",
        },
        gray = {
            dim = "#414458",
            normal = "#707281",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#9fa0aa",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#fdfdfd",
            normal = "#ceced3",
            bright = "#bebec1",
        },
        red     = { normal = "#f37f97", bright = "#ff4971" },
        -- base24 has no bright_orange slot; orange.bright falls back to .normal.
        orange  = { normal = "#f2a272", bright = "#f2a272" },
        yellow  = { normal = "#556fff", bright = "#ff8037" },
        green   = { normal = "#5adecd", bright = "#18e3c8" },
        cyan    = { normal = "#79e6f3", bright = "#3fdcee" },
        blue    = { normal = "#8897f4", bright = "#556fff" },
        magenta = { normal = "#c574dd", bright = "#b043d1" },
        brown   = { normal = "#793f4b" },
    },

    ui = {
        global = {
            background = { normal = "#1d1f28" },
            foreground = { normal = "#ceced3" },
        },
        cursor = {
            background = { normal = "#ceced3" },
            foreground = { normal = "#1d1f28" },
        },
        gutter = { foreground = "#414458" },
        border = { normal = "#707281" },
        chrome = {
            background = {
                normal = "#414458",
                dark = "#282a36",
            },
            foreground = {
                normal = "#ceced3",
                dark = "#9fa0aa",
            },
        },
        selection = { background = "#282a36" },
        highlight = {
            line = { background = "#282a36" },
            text = { background = "#414458" },
            search = {
                background = "#282a36",
                foreground = "#556fff",
            },
        },
        status = {
            error = "#f37f97",
            warning = "#f2a272",
            info = "#556fff",
            -- DiagnosticOk uses bright_green (base14) in current code; preserve.
            success = "#18e3c8",
        },
    },

    syntax = {
        comment = "#707281",

        string = {
            default = "#5adecd",
            regexp = "#5adecd",
            other = "#5adecd",
        },

        constant = {
            default = "#f2a272",
            character = {
                default = "#f37f97",
                escape = "#79e6f3",
            },
            language = "#f2a272",
            numeric = {
                default = "#f2a272",
                float = "#f2a272",
            },
        },

        entity = {
            name = {
                class = "#556fff",
                type = "#556fff",
                ["function"] = {
                    default = "#8897f4",
                    constructor = "#8897f4",
                },
                label = "#556fff",
                namespace = "#f37f97",
                tag = "#556fff",
            },
            other = {
                ["attribute-name"] = "#556fff",
            },
        },

        keyword = {
            default = "#c574dd",
            control = {
                default = "#c574dd",
                import = "#8897f4",
                flow = "#556fff",
            },
            operator = "#c574dd",
            declaration = "#c574dd",
        },

        storage = {
            type = "#c574dd",
            modifier = "#556fff",
        },

        variable = {
            default = "#ceced3",
            parameter = "#ceced3",
            other = {
                property = "#ceced3",
            },
        },

        punctuation = {
            separator = "#793f4b",
            section = "#793f4b",
        },

        markup = {
            default = "#ceced3",
            heading = "#8897f4",
            raw = "#f2a272",
            link = "#f2a272",
            list = "#556fff",
            inserted = "#5adecd",
            deleted = "#f37f97",
        },

        meta = {
            preprocessor = "#556fff",
        },
    },
}
