-- Auto-generated by tinted-builder-rust from a base24 scheme.
-- Translates base24 slots into tinted8-shaped keys. Mirrors base16.lua.mustache
-- exactly, plus brights from base12-17 and DiagnosticOk = bright_green.
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base24 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#282a36",
    base01 = "#21222c",
    base02 = "#44475a",
    base03 = "#6272a4",
    base04 = "#9ea8c7",
    base05 = "#f8f8f2",
    base06 = "#f8f8f2",
    base07 = "#ffffff",
    base08 = "#ff5555",
    base09 = "#ffb86c",
    base0A = "#f1fa8c",
    base0B = "#50fa7b",
    base0C = "#8be9fd",
    base0D = "#bd93f9",
    base0E = "#ff79c6",
    base0F = "#993333",
    base10 = "#1e2029",
    base11 = "#16171d",
    base12 = "#ff6e6e",
    base13 = "#ffffa5",
    base14 = "#69ff94",
    base15 = "#a4ffff",
    base16 = "#d6acff",
    base17 = "#ff92df",

    palette = {
        black = {
            normal = "#282a36",
            bright = "#21222c",
        },
        gray = {
            dim = "#44475a",
            normal = "#6272a4",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#9ea8c7",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#f8f8f2",
            normal = "#f8f8f2",
            bright = "#ffffff",
        },
        red = { normal = "#ff5555", bright = "#ff6e6e" },
        -- base24 has no bright_orange slot; orange.bright falls back to .normal.
        orange = { normal = "#ffb86c", bright = "#ffb86c" },
        yellow = { normal = "#f1fa8c", bright = "#ffffa5" },
        green = { normal = "#50fa7b", bright = "#69ff94" },
        cyan = { normal = "#8be9fd", bright = "#a4ffff" },
        blue = { normal = "#bd93f9", bright = "#d6acff" },
        magenta = { normal = "#ff79c6", bright = "#ff92df" },
        brown = { normal = "#993333" },
    },

    ui = {
        global = {
            background = { normal = "#282a36" },
            foreground = { normal = "#f8f8f2" },
        },
        cursor = {
            background = { normal = "#f8f8f2" },
            foreground = { normal = "#282a36" },
        },
        gutter = { foreground = "#44475a" },
        border = { normal = "#6272a4" },
        chrome = {
            background = {
                normal = "#44475a",
                dark = "#21222c",
            },
            foreground = {
                normal = "#f8f8f2",
                dark = "#9ea8c7",
            },
        },
        selection = { background = "#21222c" },
        highlight = {
            line = { background = "#21222c" },
            text = { background = "#44475a" },
            search = {
                background = "#21222c",
                foreground = "#f1fa8c",
            },
        },
        status = {
            error = "#ff5555",
            warning = "#ffb86c",
            info = "#f1fa8c",
            -- DiagnosticOk uses bright_green (base14) in current code; preserve.
            success = "#69ff94",
        },
    },

    syntax = {
        comment = "#6272a4",

        string = {
            default = "#50fa7b",
            regexp = "#50fa7b",
            other = "#50fa7b",
        },

        constant = {
            default = "#ffb86c",
            character = {
                default = "#ff5555",
                escape = "#8be9fd",
            },
            language = "#ffb86c",
            numeric = {
                default = "#ffb86c",
                float = "#ffb86c",
            },
        },

        entity = {
            name = {
                class = "#f1fa8c",
                type = "#f1fa8c",
                ["function"] = {
                    default = "#bd93f9",
                    constructor = "#bd93f9",
                },
                label = "#f1fa8c",
                namespace = "#ff5555",
                tag = "#f1fa8c",
            },
            other = {
                ["attribute-name"] = "#f1fa8c",
            },
        },

        keyword = {
            default = "#ff79c6",
            control = {
                default = "#ff79c6",
                import = "#bd93f9",
                flow = "#f1fa8c",
            },
            operator = "#ff79c6",
            declaration = "#ff79c6",
        },

        storage = {
            type = "#ff79c6",
            modifier = "#f1fa8c",
        },

        variable = {
            default = "#f8f8f2",
            parameter = "#f8f8f2",
            other = {
                property = "#f8f8f2",
            },
        },

        punctuation = {
            separator = "#993333",
            section = "#993333",
        },

        markup = {
            default = "#f8f8f2",
            heading = "#bd93f9",
            raw = "#ffb86c",
            link = "#ffb86c",
            list = "#f1fa8c",
            inserted = "#50fa7b",
            deleted = "#ff5555",
        },

        meta = {
            preprocessor = "#f1fa8c",
        },
    },
}
