-- Auto-generated by tinted-builder-rust from a base24 scheme.
-- Translates base24 slots into tinted8-shaped keys. Mirrors base16.lua.mustache
-- exactly, plus brights from base12-17 and DiagnosticOk = bright_green.
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base24 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#000000",
    base01 = "#878787",
    base02 = "#555555",
    base03 = "#7d7d7d",
    base04 = "#a5a5a5",
    base05 = "#cdcdcd",
    base06 = "#f5f5f5",
    base07 = "#e5e5e5",
    base08 = "#ff6600",
    base09 = "#ffcc00",
    base0A = "#0000ff",
    base0B = "#ccff04",
    base0C = "#44b3cc",
    base0D = "#44b3cc",
    base0E = "#9933cc",
    base0F = "#7f3300",
    base10 = "#383838",
    base11 = "#1c1c1c",
    base12 = "#ff0000",
    base13 = "#ffff00",
    base14 = "#00ff00",
    base15 = "#00ffff",
    base16 = "#0000ff",
    base17 = "#ff00ff",

    palette = {
        black = {
            normal = "#000000",
            bright = "#878787",
        },
        gray = {
            dim = "#555555",
            normal = "#7d7d7d",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#a5a5a5",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#f5f5f5",
            normal = "#cdcdcd",
            bright = "#e5e5e5",
        },
        red     = { normal = "#ff6600", bright = "#ff0000" },
        -- base24 has no bright_orange slot; orange.bright falls back to .normal.
        orange  = { normal = "#ffcc00", bright = "#ffcc00" },
        yellow  = { normal = "#0000ff", bright = "#ffff00" },
        green   = { normal = "#ccff04", bright = "#00ff00" },
        cyan    = { normal = "#44b3cc", bright = "#00ffff" },
        blue    = { normal = "#44b3cc", bright = "#0000ff" },
        magenta = { normal = "#9933cc", bright = "#ff00ff" },
        brown   = { normal = "#7f3300" },
    },

    ui = {
        global = {
            background = { normal = "#000000" },
            foreground = { normal = "#cdcdcd" },
        },
        cursor = {
            background = { normal = "#cdcdcd" },
            foreground = { normal = "#000000" },
        },
        gutter = { foreground = "#555555" },
        border = { normal = "#7d7d7d" },
        chrome = {
            background = {
                normal = "#555555",
                dark = "#878787",
            },
            foreground = {
                normal = "#cdcdcd",
                dark = "#a5a5a5",
            },
        },
        selection = { background = "#878787" },
        highlight = {
            line = { background = "#878787" },
            text = { background = "#555555" },
            search = {
                background = "#878787",
                foreground = "#0000ff",
            },
        },
        status = {
            error = "#ff6600",
            warning = "#ffcc00",
            info = "#0000ff",
            -- DiagnosticOk uses bright_green (base14) in current code; preserve.
            success = "#00ff00",
        },
    },

    syntax = {
        comment = "#7d7d7d",

        string = {
            default = "#ccff04",
            regexp = "#ccff04",
            other = "#ccff04",
        },

        constant = {
            default = "#ffcc00",
            character = {
                default = "#ff6600",
                escape = "#44b3cc",
            },
            language = "#ffcc00",
            numeric = {
                default = "#ffcc00",
                float = "#ffcc00",
            },
        },

        entity = {
            name = {
                class = "#0000ff",
                type = "#0000ff",
                ["function"] = {
                    default = "#44b3cc",
                    constructor = "#44b3cc",
                },
                label = "#0000ff",
                namespace = "#ff6600",
                tag = "#0000ff",
            },
            other = {
                ["attribute-name"] = "#0000ff",
            },
        },

        keyword = {
            default = "#9933cc",
            control = {
                default = "#9933cc",
                import = "#44b3cc",
                flow = "#0000ff",
            },
            operator = "#9933cc",
            declaration = "#9933cc",
        },

        storage = {
            type = "#9933cc",
            modifier = "#0000ff",
        },

        variable = {
            default = "#cdcdcd",
            parameter = "#cdcdcd",
            other = {
                property = "#cdcdcd",
            },
        },

        punctuation = {
            separator = "#7f3300",
            section = "#7f3300",
        },

        markup = {
            default = "#cdcdcd",
            heading = "#44b3cc",
            raw = "#ffcc00",
            link = "#ffcc00",
            list = "#0000ff",
            inserted = "#ccff04",
            deleted = "#ff6600",
        },

        meta = {
            preprocessor = "#0000ff",
        },
    },
}
