-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#000000",
    base01 = "#231a40",
    base02 = "#432d59",
    base03 = "#593380",
    base04 = "#00ff00",
    base05 = "#b08ae6",
    base06 = "#9045e6",
    base07 = "#a366ff",
    base08 = "#a82ee6",
    base09 = "#bb66cc",
    base0A = "#f29df2",
    base0B = "#4595e6",
    base0C = "#40dfff",
    base0D = "#4136d9",
    base0E = "#7e5ce6",
    base0F = "#a886bf",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#000000",
            bright = "#231a40",
        },
        gray = {
            dim = "#432d59",
            normal = "#593380",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#00ff00",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#9045e6",
            normal = "#b08ae6",
            bright = "#a366ff",
        },
        red     = { normal = "#a82ee6", bright = "#a82ee6" },
        orange  = { normal = "#bb66cc", bright = "#bb66cc" },
        yellow  = { normal = "#f29df2", bright = "#f29df2" },
        green   = { normal = "#4595e6", bright = "#4595e6" },
        cyan    = { normal = "#40dfff", bright = "#40dfff" },
        blue    = { normal = "#4136d9", bright = "#4136d9" },
        magenta = { normal = "#7e5ce6", bright = "#7e5ce6" },
        brown   = { normal = "#a886bf" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#000000" },
            foreground = { normal = "#b08ae6" },
        },
        cursor = {
            background = { normal = "#b08ae6" },
            foreground = { normal = "#000000" },
        },
        gutter = { foreground = "#432d59" },
        border = { normal = "#593380" },
        chrome = {
            background = {
                normal = "#432d59",
                dark = "#231a40",
            },
            foreground = {
                normal = "#b08ae6",
                dark = "#00ff00",
            },
        },
        selection = { background = "#231a40" },
        highlight = {
            line = { background = "#231a40" },
            text = { background = "#432d59" },
            search = {
                background = "#231a40",
                foreground = "#f29df2",
            },
        },
        status = {
            error = "#a82ee6",
            warning = "#bb66cc",
            info = "#f29df2",
            success = "#4595e6",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#593380",

        string = {
            default = "#4595e6",
            regexp = "#4595e6",
            other = "#4595e6",
        },

        constant = {
            default = "#bb66cc",
            character = {
                default = "#a82ee6",
                escape = "#40dfff",
            },
            language = "#bb66cc",
            numeric = {
                default = "#bb66cc",
                float = "#bb66cc",
            },
        },

        entity = {
            name = {
                class = "#f29df2",
                type = "#f29df2",
                ["function"] = {
                    default = "#4136d9",
                    constructor = "#4136d9",
                },
                label = "#f29df2",
                namespace = "#a82ee6",
                tag = "#f29df2",
            },
            other = {
                ["attribute-name"] = "#f29df2",
            },
        },

        keyword = {
            default = "#7e5ce6",
            control = {
                default = "#7e5ce6",
                import = "#4136d9",
                flow = "#f29df2",
            },
            operator = "#7e5ce6",
            declaration = "#7e5ce6",
        },

        storage = {
            type = "#7e5ce6",
            modifier = "#f29df2",
        },

        variable = {
            default = "#b08ae6",
            parameter = "#b08ae6",
            other = {
                property = "#b08ae6",
            },
        },

        punctuation = {
            separator = "#a886bf",
            section = "#a886bf",
        },

        markup = {
            default = "#b08ae6",
            heading = "#4136d9",
            raw = "#bb66cc",
            link = "#bb66cc",
            list = "#f29df2",
            inserted = "#4595e6",
            deleted = "#a82ee6",
        },

        meta = {
            preprocessor = "#f29df2",
        },
    },
}
