-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "light",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#fcfefd",
    base01 = "#ecf6f2",
    base02 = "#e0f0ef",
    base03 = "#cad8d2",
    base04 = "#9da8a3",
    base05 = "#5a605d",
    base06 = "#434846",
    base07 = "#2d302f",
    base08 = "#f9906f",
    base09 = "#b38a61",
    base0A = "#f0c239",
    base0B = "#8ab361",
    base0C = "#30dff3",
    base0D = "#b0a4e3",
    base0E = "#cca4e3",
    base0F = "#ca6924",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#fcfefd",
            bright = "#ecf6f2",
        },
        gray = {
            dim = "#e0f0ef",
            normal = "#cad8d2",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#9da8a3",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#434846",
            normal = "#5a605d",
            bright = "#2d302f",
        },
        red = { normal = "#f9906f", bright = "#f9906f" },
        orange = { normal = "#b38a61", bright = "#b38a61" },
        yellow = { normal = "#f0c239", bright = "#f0c239" },
        green = { normal = "#8ab361", bright = "#8ab361" },
        cyan = { normal = "#30dff3", bright = "#30dff3" },
        blue = { normal = "#b0a4e3", bright = "#b0a4e3" },
        magenta = { normal = "#cca4e3", bright = "#cca4e3" },
        brown = { normal = "#ca6924" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#fcfefd" },
            foreground = { normal = "#5a605d" },
        },
        cursor = {
            background = { normal = "#5a605d" },
            foreground = { normal = "#fcfefd" },
        },
        gutter = { foreground = "#e0f0ef" },
        border = { normal = "#cad8d2" },
        chrome = {
            background = {
                normal = "#e0f0ef",
                dark = "#ecf6f2",
            },
            foreground = {
                normal = "#5a605d",
                dark = "#9da8a3",
            },
        },
        selection = { background = "#ecf6f2" },
        highlight = {
            line = { background = "#ecf6f2" },
            text = { background = "#e0f0ef" },
            search = {
                background = "#ecf6f2",
                foreground = "#f0c239",
            },
        },
        status = {
            error = "#f9906f",
            warning = "#b38a61",
            info = "#f0c239",
            success = "#8ab361",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#cad8d2",

        string = {
            default = "#8ab361",
            regexp = "#8ab361",
            other = "#8ab361",
        },

        constant = {
            default = "#b38a61",
            character = {
                default = "#f9906f",
                escape = "#30dff3",
            },
            language = "#b38a61",
            numeric = {
                default = "#b38a61",
                float = "#b38a61",
            },
        },

        entity = {
            name = {
                class = "#f0c239",
                type = "#f0c239",
                ["function"] = {
                    default = "#b0a4e3",
                    constructor = "#b0a4e3",
                },
                label = "#f0c239",
                namespace = "#f9906f",
                tag = "#f0c239",
            },
            other = {
                ["attribute-name"] = "#f0c239",
            },
        },

        keyword = {
            default = "#cca4e3",
            control = {
                default = "#cca4e3",
                import = "#b0a4e3",
                flow = "#f0c239",
            },
            operator = "#cca4e3",
            declaration = "#cca4e3",
        },

        storage = {
            type = "#cca4e3",
            modifier = "#f0c239",
        },

        variable = {
            default = "#5a605d",
            parameter = "#5a605d",
            other = {
                property = "#5a605d",
            },
        },

        punctuation = {
            separator = "#ca6924",
            section = "#ca6924",
        },

        markup = {
            default = "#5a605d",
            heading = "#b0a4e3",
            raw = "#b38a61",
            link = "#b38a61",
            list = "#f0c239",
            inserted = "#8ab361",
            deleted = "#f9906f",
        },

        meta = {
            preprocessor = "#f0c239",
        },
    },
}
