-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#0b0e14",
    base01 = "#131721",
    base02 = "#202229",
    base03 = "#3e4b59",
    base04 = "#bfbdb6",
    base05 = "#e6e1cf",
    base06 = "#ece8db",
    base07 = "#f2f0e7",
    base08 = "#f07178",
    base09 = "#ff8f40",
    base0A = "#ffb454",
    base0B = "#aad94c",
    base0C = "#95e6cb",
    base0D = "#59c2ff",
    base0E = "#d2a6ff",
    base0F = "#e6b450",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#0b0e14",
            bright = "#131721",
        },
        gray = {
            dim = "#202229",
            normal = "#3e4b59",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#bfbdb6",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#ece8db",
            normal = "#e6e1cf",
            bright = "#f2f0e7",
        },
        red = { normal = "#f07178", bright = "#f07178" },
        orange = { normal = "#ff8f40", bright = "#ff8f40" },
        yellow = { normal = "#ffb454", bright = "#ffb454" },
        green = { normal = "#aad94c", bright = "#aad94c" },
        cyan = { normal = "#95e6cb", bright = "#95e6cb" },
        blue = { normal = "#59c2ff", bright = "#59c2ff" },
        magenta = { normal = "#d2a6ff", bright = "#d2a6ff" },
        brown = { normal = "#e6b450" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#0b0e14" },
            foreground = { normal = "#e6e1cf" },
        },
        cursor = {
            background = { normal = "#e6e1cf" },
            foreground = { normal = "#0b0e14" },
        },
        gutter = { foreground = "#202229" },
        border = { normal = "#3e4b59" },
        chrome = {
            background = {
                normal = "#202229",
                dark = "#131721",
            },
            foreground = {
                normal = "#e6e1cf",
                dark = "#bfbdb6",
            },
        },
        selection = { background = "#131721" },
        highlight = {
            line = { background = "#131721" },
            text = { background = "#202229" },
            search = {
                background = "#131721",
                foreground = "#ffb454",
            },
        },
        status = {
            error = "#f07178",
            warning = "#ff8f40",
            info = "#ffb454",
            success = "#aad94c",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#3e4b59",

        string = {
            default = "#aad94c",
            regexp = "#aad94c",
            other = "#aad94c",
        },

        constant = {
            default = "#ff8f40",
            character = {
                default = "#f07178",
                escape = "#95e6cb",
            },
            language = "#ff8f40",
            numeric = {
                default = "#ff8f40",
                float = "#ff8f40",
            },
        },

        entity = {
            name = {
                class = "#ffb454",
                type = "#ffb454",
                ["function"] = {
                    default = "#59c2ff",
                    constructor = "#59c2ff",
                },
                label = "#ffb454",
                namespace = "#f07178",
                tag = "#ffb454",
            },
            other = {
                ["attribute-name"] = "#ffb454",
            },
        },

        keyword = {
            default = "#d2a6ff",
            control = {
                default = "#d2a6ff",
                import = "#59c2ff",
                flow = "#ffb454",
            },
            operator = "#d2a6ff",
            declaration = "#d2a6ff",
        },

        storage = {
            type = "#d2a6ff",
            modifier = "#ffb454",
        },

        variable = {
            default = "#e6e1cf",
            parameter = "#e6e1cf",
            other = {
                property = "#e6e1cf",
            },
        },

        punctuation = {
            separator = "#e6b450",
            section = "#e6b450",
        },

        markup = {
            default = "#e6e1cf",
            heading = "#59c2ff",
            raw = "#ff8f40",
            link = "#ff8f40",
            list = "#ffb454",
            inserted = "#aad94c",
            deleted = "#f07178",
        },

        meta = {
            preprocessor = "#ffb454",
        },
    },
}
