-- Auto-generated by tinted-builder-rust from a base24 scheme.
-- Translates base24 slots into tinted8-shaped keys. Mirrors base16.lua.mustache
-- exactly, plus brights from base12-17 and DiagnosticOk = bright_green.
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base24 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#2e2e2e",
    base01 = "#2e2e2e",
    base02 = "#454545",
    base03 = "#737373",
    base04 = "#a1a2a2",
    base05 = "#cfd0d0",
    base06 = "#feffff",
    base07 = "#feffff",
    base08 = "#fc6d26",
    base09 = "#fca121",
    base0A = "#db501f",
    base0B = "#3eb383",
    base0C = "#6e49cb",
    base0D = "#db3b21",
    base0E = "#380d75",
    base0F = "#7e3613",
    base10 = "#2e2e2e",
    base11 = "#171717",
    base12 = "#ff6517",
    base13 = "#fca012",
    base14 = "#52e9a8",
    base15 = "#7d53e7",
    base16 = "#db501f",
    base17 = "#441090",

    palette = {
        black = {
            normal = "#2e2e2e",
            bright = "#2e2e2e",
        },
        gray = {
            dim = "#454545",
            normal = "#737373",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#a1a2a2",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#feffff",
            normal = "#cfd0d0",
            bright = "#feffff",
        },
        red = { normal = "#fc6d26", bright = "#ff6517" },
        -- base24 has no bright_orange slot; orange.bright falls back to .normal.
        orange = { normal = "#fca121", bright = "#fca121" },
        yellow = { normal = "#db501f", bright = "#fca012" },
        green = { normal = "#3eb383", bright = "#52e9a8" },
        cyan = { normal = "#6e49cb", bright = "#7d53e7" },
        blue = { normal = "#db3b21", bright = "#db501f" },
        magenta = { normal = "#380d75", bright = "#441090" },
        brown = { normal = "#7e3613" },
    },

    ui = {
        global = {
            background = { normal = "#2e2e2e" },
            foreground = { normal = "#cfd0d0" },
        },
        cursor = {
            background = { normal = "#cfd0d0" },
            foreground = { normal = "#2e2e2e" },
        },
        gutter = { foreground = "#454545" },
        border = { normal = "#737373" },
        chrome = {
            background = {
                normal = "#454545",
                dark = "#2e2e2e",
            },
            foreground = {
                normal = "#cfd0d0",
                dark = "#a1a2a2",
            },
        },
        selection = { background = "#2e2e2e" },
        highlight = {
            line = { background = "#2e2e2e" },
            text = { background = "#454545" },
            search = {
                background = "#2e2e2e",
                foreground = "#db501f",
            },
        },
        status = {
            error = "#fc6d26",
            warning = "#fca121",
            info = "#db501f",
            -- DiagnosticOk uses bright_green (base14) in current code; preserve.
            success = "#52e9a8",
        },
    },

    syntax = {
        comment = "#737373",

        string = {
            default = "#3eb383",
            regexp = "#3eb383",
            other = "#3eb383",
        },

        constant = {
            default = "#fca121",
            character = {
                default = "#fc6d26",
                escape = "#6e49cb",
            },
            language = "#fca121",
            numeric = {
                default = "#fca121",
                float = "#fca121",
            },
        },

        entity = {
            name = {
                class = "#db501f",
                type = "#db501f",
                ["function"] = {
                    default = "#db3b21",
                    constructor = "#db3b21",
                },
                label = "#db501f",
                namespace = "#fc6d26",
                tag = "#db501f",
            },
            other = {
                ["attribute-name"] = "#db501f",
            },
        },

        keyword = {
            default = "#380d75",
            control = {
                default = "#380d75",
                import = "#db3b21",
                flow = "#db501f",
            },
            operator = "#380d75",
            declaration = "#380d75",
        },

        storage = {
            type = "#380d75",
            modifier = "#db501f",
        },

        variable = {
            default = "#cfd0d0",
            parameter = "#cfd0d0",
            other = {
                property = "#cfd0d0",
            },
        },

        punctuation = {
            separator = "#7e3613",
            section = "#7e3613",
        },

        markup = {
            default = "#cfd0d0",
            heading = "#db3b21",
            raw = "#fca121",
            link = "#fca121",
            list = "#db501f",
            inserted = "#3eb383",
            deleted = "#fc6d26",
        },

        meta = {
            preprocessor = "#db501f",
        },
    },
}
