-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "light",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#f4fbf4",
    base01 = "#cfe8cf",
    base02 = "#8ca68c",
    base03 = "#809980",
    base04 = "#687d68",
    base05 = "#5e6e5e",
    base06 = "#242924",
    base07 = "#131513",
    base08 = "#e6193c",
    base09 = "#87711d",
    base0A = "#98981b",
    base0B = "#29a329",
    base0C = "#1999b3",
    base0D = "#3d62f5",
    base0E = "#ad2bee",
    base0F = "#e619c3",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#f4fbf4",
            bright = "#cfe8cf",
        },
        gray = {
            dim = "#8ca68c",
            normal = "#809980",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#687d68",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#242924",
            normal = "#5e6e5e",
            bright = "#131513",
        },
        red = { normal = "#e6193c", bright = "#e6193c" },
        orange = { normal = "#87711d", bright = "#87711d" },
        yellow = { normal = "#98981b", bright = "#98981b" },
        green = { normal = "#29a329", bright = "#29a329" },
        cyan = { normal = "#1999b3", bright = "#1999b3" },
        blue = { normal = "#3d62f5", bright = "#3d62f5" },
        magenta = { normal = "#ad2bee", bright = "#ad2bee" },
        brown = { normal = "#e619c3" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#f4fbf4" },
            foreground = { normal = "#5e6e5e" },
        },
        cursor = {
            background = { normal = "#5e6e5e" },
            foreground = { normal = "#f4fbf4" },
        },
        gutter = { foreground = "#8ca68c" },
        border = { normal = "#809980" },
        chrome = {
            background = {
                normal = "#8ca68c",
                dark = "#cfe8cf",
            },
            foreground = {
                normal = "#5e6e5e",
                dark = "#687d68",
            },
        },
        selection = { background = "#cfe8cf" },
        highlight = {
            line = { background = "#cfe8cf" },
            text = { background = "#8ca68c" },
            search = {
                background = "#cfe8cf",
                foreground = "#98981b",
            },
        },
        status = {
            error = "#e6193c",
            warning = "#87711d",
            info = "#98981b",
            success = "#29a329",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#809980",

        string = {
            default = "#29a329",
            regexp = "#29a329",
            other = "#29a329",
        },

        constant = {
            default = "#87711d",
            character = {
                default = "#e6193c",
                escape = "#1999b3",
            },
            language = "#87711d",
            numeric = {
                default = "#87711d",
                float = "#87711d",
            },
        },

        entity = {
            name = {
                class = "#98981b",
                type = "#98981b",
                ["function"] = {
                    default = "#3d62f5",
                    constructor = "#3d62f5",
                },
                label = "#98981b",
                namespace = "#e6193c",
                tag = "#98981b",
            },
            other = {
                ["attribute-name"] = "#98981b",
            },
        },

        keyword = {
            default = "#ad2bee",
            control = {
                default = "#ad2bee",
                import = "#3d62f5",
                flow = "#98981b",
            },
            operator = "#ad2bee",
            declaration = "#ad2bee",
        },

        storage = {
            type = "#ad2bee",
            modifier = "#98981b",
        },

        variable = {
            default = "#5e6e5e",
            parameter = "#5e6e5e",
            other = {
                property = "#5e6e5e",
            },
        },

        punctuation = {
            separator = "#e619c3",
            section = "#e619c3",
        },

        markup = {
            default = "#5e6e5e",
            heading = "#3d62f5",
            raw = "#87711d",
            link = "#87711d",
            list = "#98981b",
            inserted = "#29a329",
            deleted = "#e6193c",
        },

        meta = {
            preprocessor = "#98981b",
        },
    },
}
