-- Auto-generated by tinted-builder-rust from a base24 scheme.
-- Translates base24 slots into tinted8-shaped keys. Mirrors base16.lua.mustache
-- exactly, plus brights from base12-17 and DiagnosticOk = bright_green.
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base24 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#1c1c1c",
    base01 = "#3d352a",
    base02 = "#554444",
    base03 = "#6e5d59",
    base04 = "#88776e",
    base05 = "#a19083",
    base06 = "#bbaa99",
    base07 = "#ddccbb",
    base08 = "#cd5c5c",
    base09 = "#e8ae5b",
    base0A = "#87ceeb",
    base0B = "#86af80",
    base0C = "#b0c4de",
    base0D = "#6495ed",
    base0E = "#deb887",
    base0F = "#662e2e",
    base10 = "#382d2d",
    base11 = "#1c1616",
    base12 = "#cc5533",
    base13 = "#ffa75d",
    base14 = "#88aa22",
    base15 = "#b0c4de",
    base16 = "#87ceeb",
    base17 = "#996600",

    palette = {
        black = {
            normal = "#1c1c1c",
            bright = "#3d352a",
        },
        gray = {
            dim = "#554444",
            normal = "#6e5d59",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#88776e",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#bbaa99",
            normal = "#a19083",
            bright = "#ddccbb",
        },
        red     = { normal = "#cd5c5c", bright = "#cc5533" },
        -- base24 has no bright_orange slot; orange.bright falls back to .normal.
        orange  = { normal = "#e8ae5b", bright = "#e8ae5b" },
        yellow  = { normal = "#87ceeb", bright = "#ffa75d" },
        green   = { normal = "#86af80", bright = "#88aa22" },
        cyan    = { normal = "#b0c4de", bright = "#b0c4de" },
        blue    = { normal = "#6495ed", bright = "#87ceeb" },
        magenta = { normal = "#deb887", bright = "#996600" },
        brown   = { normal = "#662e2e" },
    },

    ui = {
        global = {
            background = { normal = "#1c1c1c" },
            foreground = { normal = "#a19083" },
        },
        cursor = {
            background = { normal = "#a19083" },
            foreground = { normal = "#1c1c1c" },
        },
        gutter = { foreground = "#554444" },
        border = { normal = "#6e5d59" },
        chrome = {
            background = {
                normal = "#554444",
                dark = "#3d352a",
            },
            foreground = {
                normal = "#a19083",
                dark = "#88776e",
            },
        },
        selection = { background = "#3d352a" },
        highlight = {
            line = { background = "#3d352a" },
            text = { background = "#554444" },
            search = {
                background = "#3d352a",
                foreground = "#87ceeb",
            },
        },
        status = {
            error = "#cd5c5c",
            warning = "#e8ae5b",
            info = "#87ceeb",
            -- DiagnosticOk uses bright_green (base14) in current code; preserve.
            success = "#88aa22",
        },
    },

    syntax = {
        comment = "#6e5d59",

        string = {
            default = "#86af80",
            regexp = "#86af80",
            other = "#86af80",
        },

        constant = {
            default = "#e8ae5b",
            character = {
                default = "#cd5c5c",
                escape = "#b0c4de",
            },
            language = "#e8ae5b",
            numeric = {
                default = "#e8ae5b",
                float = "#e8ae5b",
            },
        },

        entity = {
            name = {
                class = "#87ceeb",
                type = "#87ceeb",
                ["function"] = {
                    default = "#6495ed",
                    constructor = "#6495ed",
                },
                label = "#87ceeb",
                namespace = "#cd5c5c",
                tag = "#87ceeb",
            },
            other = {
                ["attribute-name"] = "#87ceeb",
            },
        },

        keyword = {
            default = "#deb887",
            control = {
                default = "#deb887",
                import = "#6495ed",
                flow = "#87ceeb",
            },
            operator = "#deb887",
            declaration = "#deb887",
        },

        storage = {
            type = "#deb887",
            modifier = "#87ceeb",
        },

        variable = {
            default = "#a19083",
            parameter = "#a19083",
            other = {
                property = "#a19083",
            },
        },

        punctuation = {
            separator = "#662e2e",
            section = "#662e2e",
        },

        markup = {
            default = "#a19083",
            heading = "#6495ed",
            raw = "#e8ae5b",
            link = "#e8ae5b",
            list = "#87ceeb",
            inserted = "#86af80",
            deleted = "#cd5c5c",
        },

        meta = {
            preprocessor = "#87ceeb",
        },
    },
}
