-- Auto-generated by tinted-builder-rust from a base24 scheme.
-- Translates base24 slots into tinted8-shaped keys. Mirrors base16.lua.mustache
-- exactly, plus brights from base12-17 and DiagnosticOk = bright_green.
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base24 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#0a1e24",
    base01 = "#6e5246",
    base02 = "#674c31",
    base03 = "#897558",
    base04 = "#ab9e7f",
    base05 = "#cdc7a6",
    base06 = "#f0f1ce",
    base07 = "#fefff0",
    base08 = "#e35a00",
    base09 = "#e3cd7b",
    base0A = "#67a0cd",
    base0B = "#5cab96",
    base0C = "#06afc7",
    base0D = "#0e548b",
    base0E = "#e35a00",
    base0F = "#712d00",
    base10 = "#443220",
    base11 = "#221910",
    base12 = "#ff8a39",
    base13 = "#ffc777",
    base14 = "#adcab8",
    base15 = "#83a6b3",
    base16 = "#67a0cd",
    base17 = "#ff8a39",

    palette = {
        black = {
            normal = "#0a1e24",
            bright = "#6e5246",
        },
        gray = {
            dim = "#674c31",
            normal = "#897558",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#ab9e7f",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#f0f1ce",
            normal = "#cdc7a6",
            bright = "#fefff0",
        },
        red = { normal = "#e35a00", bright = "#ff8a39" },
        -- base24 has no bright_orange slot; orange.bright falls back to .normal.
        orange = { normal = "#e3cd7b", bright = "#e3cd7b" },
        yellow = { normal = "#67a0cd", bright = "#ffc777" },
        green = { normal = "#5cab96", bright = "#adcab8" },
        cyan = { normal = "#06afc7", bright = "#83a6b3" },
        blue = { normal = "#0e548b", bright = "#67a0cd" },
        magenta = { normal = "#e35a00", bright = "#ff8a39" },
        brown = { normal = "#712d00" },
    },

    ui = {
        global = {
            background = { normal = "#0a1e24" },
            foreground = { normal = "#cdc7a6" },
        },
        cursor = {
            background = { normal = "#cdc7a6" },
            foreground = { normal = "#0a1e24" },
        },
        gutter = { foreground = "#674c31" },
        border = { normal = "#897558" },
        chrome = {
            background = {
                normal = "#674c31",
                dark = "#6e5246",
            },
            foreground = {
                normal = "#cdc7a6",
                dark = "#ab9e7f",
            },
        },
        selection = { background = "#6e5246" },
        highlight = {
            line = { background = "#6e5246" },
            text = { background = "#674c31" },
            search = {
                background = "#6e5246",
                foreground = "#67a0cd",
            },
        },
        status = {
            error = "#e35a00",
            warning = "#e3cd7b",
            info = "#67a0cd",
            -- DiagnosticOk uses bright_green (base14) in current code; preserve.
            success = "#adcab8",
        },
    },

    syntax = {
        comment = "#897558",

        string = {
            default = "#5cab96",
            regexp = "#5cab96",
            other = "#5cab96",
        },

        constant = {
            default = "#e3cd7b",
            character = {
                default = "#e35a00",
                escape = "#06afc7",
            },
            language = "#e3cd7b",
            numeric = {
                default = "#e3cd7b",
                float = "#e3cd7b",
            },
        },

        entity = {
            name = {
                class = "#67a0cd",
                type = "#67a0cd",
                ["function"] = {
                    default = "#0e548b",
                    constructor = "#0e548b",
                },
                label = "#67a0cd",
                namespace = "#e35a00",
                tag = "#67a0cd",
            },
            other = {
                ["attribute-name"] = "#67a0cd",
            },
        },

        keyword = {
            default = "#e35a00",
            control = {
                default = "#e35a00",
                import = "#0e548b",
                flow = "#67a0cd",
            },
            operator = "#e35a00",
            declaration = "#e35a00",
        },

        storage = {
            type = "#e35a00",
            modifier = "#67a0cd",
        },

        variable = {
            default = "#cdc7a6",
            parameter = "#cdc7a6",
            other = {
                property = "#cdc7a6",
            },
        },

        punctuation = {
            separator = "#712d00",
            section = "#712d00",
        },

        markup = {
            default = "#cdc7a6",
            heading = "#0e548b",
            raw = "#e3cd7b",
            link = "#e3cd7b",
            list = "#67a0cd",
            inserted = "#5cab96",
            deleted = "#e35a00",
        },

        meta = {
            preprocessor = "#67a0cd",
        },
    },
}
