-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#292d3e",
    base01 = "#444267",
    base02 = "#5c598b",
    base03 = "#676e95",
    base04 = "#8796b0",
    base05 = "#959dcb",
    base06 = "#959dcb",
    base07 = "#ffffff",
    base08 = "#6e98e1",
    base09 = "#f78c6c",
    base0A = "#e0a557",
    base0B = "#78c06e",
    base0C = "#83b7e5",
    base0D = "#82aaff",
    base0E = "#c792ea",
    base0F = "#ff5370",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#292d3e",
            bright = "#444267",
        },
        gray = {
            dim = "#5c598b",
            normal = "#676e95",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#8796b0",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#959dcb",
            normal = "#959dcb",
            bright = "#ffffff",
        },
        red = { normal = "#6e98e1", bright = "#6e98e1" },
        orange = { normal = "#f78c6c", bright = "#f78c6c" },
        yellow = { normal = "#e0a557", bright = "#e0a557" },
        green = { normal = "#78c06e", bright = "#78c06e" },
        cyan = { normal = "#83b7e5", bright = "#83b7e5" },
        blue = { normal = "#82aaff", bright = "#82aaff" },
        magenta = { normal = "#c792ea", bright = "#c792ea" },
        brown = { normal = "#ff5370" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#292d3e" },
            foreground = { normal = "#959dcb" },
        },
        cursor = {
            background = { normal = "#959dcb" },
            foreground = { normal = "#292d3e" },
        },
        gutter = { foreground = "#5c598b" },
        border = { normal = "#676e95" },
        chrome = {
            background = {
                normal = "#5c598b",
                dark = "#444267",
            },
            foreground = {
                normal = "#959dcb",
                dark = "#8796b0",
            },
        },
        selection = { background = "#444267" },
        highlight = {
            line = { background = "#444267" },
            text = { background = "#5c598b" },
            search = {
                background = "#444267",
                foreground = "#e0a557",
            },
        },
        status = {
            error = "#6e98e1",
            warning = "#f78c6c",
            info = "#e0a557",
            success = "#78c06e",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#676e95",

        string = {
            default = "#78c06e",
            regexp = "#78c06e",
            other = "#78c06e",
        },

        constant = {
            default = "#f78c6c",
            character = {
                default = "#6e98e1",
                escape = "#83b7e5",
            },
            language = "#f78c6c",
            numeric = {
                default = "#f78c6c",
                float = "#f78c6c",
            },
        },

        entity = {
            name = {
                class = "#e0a557",
                type = "#e0a557",
                ["function"] = {
                    default = "#82aaff",
                    constructor = "#82aaff",
                },
                label = "#e0a557",
                namespace = "#6e98e1",
                tag = "#e0a557",
            },
            other = {
                ["attribute-name"] = "#e0a557",
            },
        },

        keyword = {
            default = "#c792ea",
            control = {
                default = "#c792ea",
                import = "#82aaff",
                flow = "#e0a557",
            },
            operator = "#c792ea",
            declaration = "#c792ea",
        },

        storage = {
            type = "#c792ea",
            modifier = "#e0a557",
        },

        variable = {
            default = "#959dcb",
            parameter = "#959dcb",
            other = {
                property = "#959dcb",
            },
        },

        punctuation = {
            separator = "#ff5370",
            section = "#ff5370",
        },

        markup = {
            default = "#959dcb",
            heading = "#82aaff",
            raw = "#f78c6c",
            link = "#f78c6c",
            list = "#e0a557",
            inserted = "#78c06e",
            deleted = "#6e98e1",
        },

        meta = {
            preprocessor = "#e0a557",
        },
    },
}
