-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#222222",
    base01 = "#313131",
    base02 = "#555d55",
    base03 = "#644646",
    base04 = "#5a5a5a",
    base05 = "#dedee7",
    base06 = "#c3c3b4",
    base07 = "#ffffe6",
    base08 = "#c88c8c",
    base09 = "#476c88",
    base0A = "#d8b56d",
    base0B = "#99c899",
    base0C = "#78b4b4",
    base0D = "#537c9c",
    base0E = "#86cacd",
    base0F = "#704f4f",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#222222",
            bright = "#313131",
        },
        gray = {
            dim = "#555d55",
            normal = "#644646",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#5a5a5a",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#c3c3b4",
            normal = "#dedee7",
            bright = "#ffffe6",
        },
        red     = { normal = "#c88c8c", bright = "#c88c8c" },
        orange  = { normal = "#476c88", bright = "#476c88" },
        yellow  = { normal = "#d8b56d", bright = "#d8b56d" },
        green   = { normal = "#99c899", bright = "#99c899" },
        cyan    = { normal = "#78b4b4", bright = "#78b4b4" },
        blue    = { normal = "#537c9c", bright = "#537c9c" },
        magenta = { normal = "#86cacd", bright = "#86cacd" },
        brown   = { normal = "#704f4f" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#222222" },
            foreground = { normal = "#dedee7" },
        },
        cursor = {
            background = { normal = "#dedee7" },
            foreground = { normal = "#222222" },
        },
        gutter = { foreground = "#555d55" },
        border = { normal = "#644646" },
        chrome = {
            background = {
                normal = "#555d55",
                dark = "#313131",
            },
            foreground = {
                normal = "#dedee7",
                dark = "#5a5a5a",
            },
        },
        selection = { background = "#313131" },
        highlight = {
            line = { background = "#313131" },
            text = { background = "#555d55" },
            search = {
                background = "#313131",
                foreground = "#d8b56d",
            },
        },
        status = {
            error = "#c88c8c",
            warning = "#476c88",
            info = "#d8b56d",
            success = "#99c899",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#644646",

        string = {
            default = "#99c899",
            regexp = "#99c899",
            other = "#99c899",
        },

        constant = {
            default = "#476c88",
            character = {
                default = "#c88c8c",
                escape = "#78b4b4",
            },
            language = "#476c88",
            numeric = {
                default = "#476c88",
                float = "#476c88",
            },
        },

        entity = {
            name = {
                class = "#d8b56d",
                type = "#d8b56d",
                ["function"] = {
                    default = "#537c9c",
                    constructor = "#537c9c",
                },
                label = "#d8b56d",
                namespace = "#c88c8c",
                tag = "#d8b56d",
            },
            other = {
                ["attribute-name"] = "#d8b56d",
            },
        },

        keyword = {
            default = "#86cacd",
            control = {
                default = "#86cacd",
                import = "#537c9c",
                flow = "#d8b56d",
            },
            operator = "#86cacd",
            declaration = "#86cacd",
        },

        storage = {
            type = "#86cacd",
            modifier = "#d8b56d",
        },

        variable = {
            default = "#dedee7",
            parameter = "#dedee7",
            other = {
                property = "#dedee7",
            },
        },

        punctuation = {
            separator = "#704f4f",
            section = "#704f4f",
        },

        markup = {
            default = "#dedee7",
            heading = "#537c9c",
            raw = "#476c88",
            link = "#476c88",
            list = "#d8b56d",
            inserted = "#99c899",
            deleted = "#c88c8c",
        },

        meta = {
            preprocessor = "#d8b56d",
        },
    },
}
