-- Auto-generated by tinted-builder-rust from a base24 scheme.
-- Translates base24 slots into tinted8-shaped keys. Mirrors base16.lua.mustache
-- exactly, plus brights from base12-17 and DiagnosticOk = bright_green.
-- Do not edit by hand.

return {
    variant = "light",

    -- Legacy base24 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#fbf1c7",
    base01 = "#ebdbb2",
    base02 = "#d5c4a1",
    base03 = "#bdae93",
    base04 = "#7c6f64",
    base05 = "#3c3836",
    base06 = "#282828",
    base07 = "#1d2021",
    base08 = "#cc241d",
    base09 = "#d65d0e",
    base0A = "#d79921",
    base0B = "#98971a",
    base0C = "#689d6a",
    base0D = "#458588",
    base0E = "#b16286",
    base0F = "#9d0006",
    base10 = "#f9f6d7",
    base11 = "#fbf9e4",
    base12 = "#9d0006",
    base13 = "#b57614",
    base14 = "#79740e",
    base15 = "#427b58",
    base16 = "#076678",
    base17 = "#8f3f71",

    palette = {
        black = {
            normal = "#fbf1c7",
            bright = "#ebdbb2",
        },
        gray = {
            dim = "#d5c4a1",
            normal = "#bdae93",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#7c6f64",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#282828",
            normal = "#3c3836",
            bright = "#1d2021",
        },
        red = { normal = "#cc241d", bright = "#9d0006" },
        -- base24 has no bright_orange slot; orange.bright falls back to .normal.
        orange = { normal = "#d65d0e", bright = "#d65d0e" },
        yellow = { normal = "#d79921", bright = "#b57614" },
        green = { normal = "#98971a", bright = "#79740e" },
        cyan = { normal = "#689d6a", bright = "#427b58" },
        blue = { normal = "#458588", bright = "#076678" },
        magenta = { normal = "#b16286", bright = "#8f3f71" },
        brown = { normal = "#9d0006" },
    },

    ui = {
        global = {
            background = { normal = "#fbf1c7" },
            foreground = { normal = "#3c3836" },
        },
        cursor = {
            background = { normal = "#3c3836" },
            foreground = { normal = "#fbf1c7" },
        },
        gutter = { foreground = "#d5c4a1" },
        border = { normal = "#bdae93" },
        chrome = {
            background = {
                normal = "#d5c4a1",
                dark = "#ebdbb2",
            },
            foreground = {
                normal = "#3c3836",
                dark = "#7c6f64",
            },
        },
        selection = { background = "#ebdbb2" },
        highlight = {
            line = { background = "#ebdbb2" },
            text = { background = "#d5c4a1" },
            search = {
                background = "#ebdbb2",
                foreground = "#d79921",
            },
        },
        status = {
            error = "#cc241d",
            warning = "#d65d0e",
            info = "#d79921",
            -- DiagnosticOk uses bright_green (base14) in current code; preserve.
            success = "#79740e",
        },
    },

    syntax = {
        comment = "#bdae93",

        string = {
            default = "#98971a",
            regexp = "#98971a",
            other = "#98971a",
        },

        constant = {
            default = "#d65d0e",
            character = {
                default = "#cc241d",
                escape = "#689d6a",
            },
            language = "#d65d0e",
            numeric = {
                default = "#d65d0e",
                float = "#d65d0e",
            },
        },

        entity = {
            name = {
                class = "#d79921",
                type = "#d79921",
                ["function"] = {
                    default = "#458588",
                    constructor = "#458588",
                },
                label = "#d79921",
                namespace = "#cc241d",
                tag = "#d79921",
            },
            other = {
                ["attribute-name"] = "#d79921",
            },
        },

        keyword = {
            default = "#b16286",
            control = {
                default = "#b16286",
                import = "#458588",
                flow = "#d79921",
            },
            operator = "#b16286",
            declaration = "#b16286",
        },

        storage = {
            type = "#b16286",
            modifier = "#d79921",
        },

        variable = {
            default = "#3c3836",
            parameter = "#3c3836",
            other = {
                property = "#3c3836",
            },
        },

        punctuation = {
            separator = "#9d0006",
            section = "#9d0006",
        },

        markup = {
            default = "#3c3836",
            heading = "#458588",
            raw = "#d65d0e",
            link = "#d65d0e",
            list = "#d79921",
            inserted = "#98971a",
            deleted = "#cc241d",
        },

        meta = {
            preprocessor = "#d79921",
        },
    },
}
