-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#1d1d1d",
    base01 = "#282828",
    base02 = "#373737",
    base03 = "#918072",
    base04 = "#bdaead",
    base05 = "#c4cbcf",
    base06 = "#eee7f2",
    base07 = "#fffef9",
    base08 = "#ed5a56",
    base09 = "#fc8c23",
    base0A = "#fbb957",
    base0B = "#aeb831",
    base0C = "#88b68d",
    base0D = "#81a2a2",
    base0E = "#cf8997",
    base0F = "#cd6227",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#1d1d1d",
            bright = "#282828",
        },
        gray = {
            dim = "#373737",
            normal = "#918072",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#bdaead",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#eee7f2",
            normal = "#c4cbcf",
            bright = "#fffef9",
        },
        red = { normal = "#ed5a56", bright = "#ed5a56" },
        orange = { normal = "#fc8c23", bright = "#fc8c23" },
        yellow = { normal = "#fbb957", bright = "#fbb957" },
        green = { normal = "#aeb831", bright = "#aeb831" },
        cyan = { normal = "#88b68d", bright = "#88b68d" },
        blue = { normal = "#81a2a2", bright = "#81a2a2" },
        magenta = { normal = "#cf8997", bright = "#cf8997" },
        brown = { normal = "#cd6227" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#1d1d1d" },
            foreground = { normal = "#c4cbcf" },
        },
        cursor = {
            background = { normal = "#c4cbcf" },
            foreground = { normal = "#1d1d1d" },
        },
        gutter = { foreground = "#373737" },
        border = { normal = "#918072" },
        chrome = {
            background = {
                normal = "#373737",
                dark = "#282828",
            },
            foreground = {
                normal = "#c4cbcf",
                dark = "#bdaead",
            },
        },
        selection = { background = "#282828" },
        highlight = {
            line = { background = "#282828" },
            text = { background = "#373737" },
            search = {
                background = "#282828",
                foreground = "#fbb957",
            },
        },
        status = {
            error = "#ed5a56",
            warning = "#fc8c23",
            info = "#fbb957",
            success = "#aeb831",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#918072",

        string = {
            default = "#aeb831",
            regexp = "#aeb831",
            other = "#aeb831",
        },

        constant = {
            default = "#fc8c23",
            character = {
                default = "#ed5a56",
                escape = "#88b68d",
            },
            language = "#fc8c23",
            numeric = {
                default = "#fc8c23",
                float = "#fc8c23",
            },
        },

        entity = {
            name = {
                class = "#fbb957",
                type = "#fbb957",
                ["function"] = {
                    default = "#81a2a2",
                    constructor = "#81a2a2",
                },
                label = "#fbb957",
                namespace = "#ed5a56",
                tag = "#fbb957",
            },
            other = {
                ["attribute-name"] = "#fbb957",
            },
        },

        keyword = {
            default = "#cf8997",
            control = {
                default = "#cf8997",
                import = "#81a2a2",
                flow = "#fbb957",
            },
            operator = "#cf8997",
            declaration = "#cf8997",
        },

        storage = {
            type = "#cf8997",
            modifier = "#fbb957",
        },

        variable = {
            default = "#c4cbcf",
            parameter = "#c4cbcf",
            other = {
                property = "#c4cbcf",
            },
        },

        punctuation = {
            separator = "#cd6227",
            section = "#cd6227",
        },

        markup = {
            default = "#c4cbcf",
            heading = "#81a2a2",
            raw = "#fc8c23",
            link = "#fc8c23",
            list = "#fbb957",
            inserted = "#aeb831",
            deleted = "#ed5a56",
        },

        meta = {
            preprocessor = "#fbb957",
        },
    },
}
