-- Auto-generated by tinted-builder-rust from a base24 scheme.
-- Translates base24 slots into tinted8-shaped keys. Mirrors base16.lua.mustache
-- exactly, plus brights from base12-17 and DiagnosticOk = bright_green.
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base24 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#1a1a1a",
    base01 = "#2a2a2a",
    base02 = "#353535",
    base03 = "#6272a4",
    base04 = "#989898",
    base05 = "#ffffff",
    base06 = "#ffffff",
    base07 = "#ffffff",
    base08 = "#ff5555",
    base09 = "#ff9c7c",
    base0A = "#ffe4a3",
    base0B = "#b8e6a0",
    base0C = "#8be9fd",
    base0D = "#bd93f9",
    base0E = "#ff9aa2",
    base0F = "#af6e5a",
    base10 = "#181818",
    base11 = "#161616",
    base12 = "#ff6e6e",
    base13 = "#ffe4a3",
    base14 = "#b8e6a0",
    base15 = "#a4ffff",
    base16 = "#d6acff",
    base17 = "#ff9aa2",

    palette = {
        black = {
            normal = "#1a1a1a",
            bright = "#2a2a2a",
        },
        gray = {
            dim = "#353535",
            normal = "#6272a4",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#989898",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#ffffff",
            normal = "#ffffff",
            bright = "#ffffff",
        },
        red = { normal = "#ff5555", bright = "#ff6e6e" },
        -- base24 has no bright_orange slot; orange.bright falls back to .normal.
        orange = { normal = "#ff9c7c", bright = "#ff9c7c" },
        yellow = { normal = "#ffe4a3", bright = "#ffe4a3" },
        green = { normal = "#b8e6a0", bright = "#b8e6a0" },
        cyan = { normal = "#8be9fd", bright = "#a4ffff" },
        blue = { normal = "#bd93f9", bright = "#d6acff" },
        magenta = { normal = "#ff9aa2", bright = "#ff9aa2" },
        brown = { normal = "#af6e5a" },
    },

    ui = {
        global = {
            background = { normal = "#1a1a1a" },
            foreground = { normal = "#ffffff" },
        },
        cursor = {
            background = { normal = "#ffffff" },
            foreground = { normal = "#1a1a1a" },
        },
        gutter = { foreground = "#353535" },
        border = { normal = "#6272a4" },
        chrome = {
            background = {
                normal = "#353535",
                dark = "#2a2a2a",
            },
            foreground = {
                normal = "#ffffff",
                dark = "#989898",
            },
        },
        selection = { background = "#2a2a2a" },
        highlight = {
            line = { background = "#2a2a2a" },
            text = { background = "#353535" },
            search = {
                background = "#2a2a2a",
                foreground = "#ffe4a3",
            },
        },
        status = {
            error = "#ff5555",
            warning = "#ff9c7c",
            info = "#ffe4a3",
            -- DiagnosticOk uses bright_green (base14) in current code; preserve.
            success = "#b8e6a0",
        },
    },

    syntax = {
        comment = "#6272a4",

        string = {
            default = "#b8e6a0",
            regexp = "#b8e6a0",
            other = "#b8e6a0",
        },

        constant = {
            default = "#ff9c7c",
            character = {
                default = "#ff5555",
                escape = "#8be9fd",
            },
            language = "#ff9c7c",
            numeric = {
                default = "#ff9c7c",
                float = "#ff9c7c",
            },
        },

        entity = {
            name = {
                class = "#ffe4a3",
                type = "#ffe4a3",
                ["function"] = {
                    default = "#bd93f9",
                    constructor = "#bd93f9",
                },
                label = "#ffe4a3",
                namespace = "#ff5555",
                tag = "#ffe4a3",
            },
            other = {
                ["attribute-name"] = "#ffe4a3",
            },
        },

        keyword = {
            default = "#ff9aa2",
            control = {
                default = "#ff9aa2",
                import = "#bd93f9",
                flow = "#ffe4a3",
            },
            operator = "#ff9aa2",
            declaration = "#ff9aa2",
        },

        storage = {
            type = "#ff9aa2",
            modifier = "#ffe4a3",
        },

        variable = {
            default = "#ffffff",
            parameter = "#ffffff",
            other = {
                property = "#ffffff",
            },
        },

        punctuation = {
            separator = "#af6e5a",
            section = "#af6e5a",
        },

        markup = {
            default = "#ffffff",
            heading = "#bd93f9",
            raw = "#ff9c7c",
            link = "#ff9c7c",
            list = "#ffe4a3",
            inserted = "#b8e6a0",
            deleted = "#ff5555",
        },

        meta = {
            preprocessor = "#ffe4a3",
        },
    },
}
