-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#0f0f0f",
    base01 = "#191919",
    base02 = "#262626",
    base03 = "#393939",
    base04 = "#4c4c4c",
    base05 = "#cacaca",
    base06 = "#e7e7e7",
    base07 = "#f0f0f0",
    base08 = "#ac8a8c",
    base09 = "#ceb188",
    base0A = "#aca98a",
    base0B = "#8aac8b",
    base0C = "#8aabac",
    base0D = "#8f8aac",
    base0E = "#ac8aac",
    base0F = "#ac8a8c",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#0f0f0f",
            bright = "#191919",
        },
        gray = {
            dim = "#262626",
            normal = "#393939",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#4c4c4c",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#e7e7e7",
            normal = "#cacaca",
            bright = "#f0f0f0",
        },
        red     = { normal = "#ac8a8c", bright = "#ac8a8c" },
        orange  = { normal = "#ceb188", bright = "#ceb188" },
        yellow  = { normal = "#aca98a", bright = "#aca98a" },
        green   = { normal = "#8aac8b", bright = "#8aac8b" },
        cyan    = { normal = "#8aabac", bright = "#8aabac" },
        blue    = { normal = "#8f8aac", bright = "#8f8aac" },
        magenta = { normal = "#ac8aac", bright = "#ac8aac" },
        brown   = { normal = "#ac8a8c" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#0f0f0f" },
            foreground = { normal = "#cacaca" },
        },
        cursor = {
            background = { normal = "#cacaca" },
            foreground = { normal = "#0f0f0f" },
        },
        gutter = { foreground = "#262626" },
        border = { normal = "#393939" },
        chrome = {
            background = {
                normal = "#262626",
                dark = "#191919",
            },
            foreground = {
                normal = "#cacaca",
                dark = "#4c4c4c",
            },
        },
        selection = { background = "#191919" },
        highlight = {
            line = { background = "#191919" },
            text = { background = "#262626" },
            search = {
                background = "#191919",
                foreground = "#aca98a",
            },
        },
        status = {
            error = "#ac8a8c",
            warning = "#ceb188",
            info = "#aca98a",
            success = "#8aac8b",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#393939",

        string = {
            default = "#8aac8b",
            regexp = "#8aac8b",
            other = "#8aac8b",
        },

        constant = {
            default = "#ceb188",
            character = {
                default = "#ac8a8c",
                escape = "#8aabac",
            },
            language = "#ceb188",
            numeric = {
                default = "#ceb188",
                float = "#ceb188",
            },
        },

        entity = {
            name = {
                class = "#aca98a",
                type = "#aca98a",
                ["function"] = {
                    default = "#8f8aac",
                    constructor = "#8f8aac",
                },
                label = "#aca98a",
                namespace = "#ac8a8c",
                tag = "#aca98a",
            },
            other = {
                ["attribute-name"] = "#aca98a",
            },
        },

        keyword = {
            default = "#ac8aac",
            control = {
                default = "#ac8aac",
                import = "#8f8aac",
                flow = "#aca98a",
            },
            operator = "#ac8aac",
            declaration = "#ac8aac",
        },

        storage = {
            type = "#ac8aac",
            modifier = "#aca98a",
        },

        variable = {
            default = "#cacaca",
            parameter = "#cacaca",
            other = {
                property = "#cacaca",
            },
        },

        punctuation = {
            separator = "#ac8a8c",
            section = "#ac8a8c",
        },

        markup = {
            default = "#cacaca",
            heading = "#8f8aac",
            raw = "#ceb188",
            link = "#ceb188",
            list = "#aca98a",
            inserted = "#8aac8b",
            deleted = "#ac8a8c",
        },

        meta = {
            preprocessor = "#aca98a",
        },
    },
}
