-- Auto-generated by tinted-builder-rust from a base24 scheme.
-- Translates base24 slots into tinted8-shaped keys. Mirrors base16.lua.mustache
-- exactly, plus brights from base12-17 and DiagnosticOk = bright_green.
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base24 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#762423",
    base01 = "#000000",
    base02 = "#262626",
    base03 = "#525252",
    base04 = "#7e7e7e",
    base05 = "#aaaaaa",
    base06 = "#d6d6d6",
    base07 = "#ffffff",
    base08 = "#d52e4d",
    base09 = "#beb86b",
    base0A = "#65a9f0",
    base0B = "#71be6b",
    base0C = "#6bbeb8",
    base0D = "#479bed",
    base0E = "#e878d6",
    base0F = "#6a1726",
    base10 = "#191919",
    base11 = "#0c0c0c",
    base12 = "#e02453",
    base13 = "#dfddb7",
    base14 = "#aff08b",
    base15 = "#b7dfdd",
    base16 = "#65a9f0",
    base17 = "#ddb7df",

    palette = {
        black = {
            normal = "#762423",
            bright = "#000000",
        },
        gray = {
            dim = "#262626",
            normal = "#525252",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#7e7e7e",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#d6d6d6",
            normal = "#aaaaaa",
            bright = "#ffffff",
        },
        red = { normal = "#d52e4d", bright = "#e02453" },
        -- base24 has no bright_orange slot; orange.bright falls back to .normal.
        orange = { normal = "#beb86b", bright = "#beb86b" },
        yellow = { normal = "#65a9f0", bright = "#dfddb7" },
        green = { normal = "#71be6b", bright = "#aff08b" },
        cyan = { normal = "#6bbeb8", bright = "#b7dfdd" },
        blue = { normal = "#479bed", bright = "#65a9f0" },
        magenta = { normal = "#e878d6", bright = "#ddb7df" },
        brown = { normal = "#6a1726" },
    },

    ui = {
        global = {
            background = { normal = "#762423" },
            foreground = { normal = "#aaaaaa" },
        },
        cursor = {
            background = { normal = "#aaaaaa" },
            foreground = { normal = "#762423" },
        },
        gutter = { foreground = "#262626" },
        border = { normal = "#525252" },
        chrome = {
            background = {
                normal = "#262626",
                dark = "#000000",
            },
            foreground = {
                normal = "#aaaaaa",
                dark = "#7e7e7e",
            },
        },
        selection = { background = "#000000" },
        highlight = {
            line = { background = "#000000" },
            text = { background = "#262626" },
            search = {
                background = "#000000",
                foreground = "#65a9f0",
            },
        },
        status = {
            error = "#d52e4d",
            warning = "#beb86b",
            info = "#65a9f0",
            -- DiagnosticOk uses bright_green (base14) in current code; preserve.
            success = "#aff08b",
        },
    },

    syntax = {
        comment = "#525252",

        string = {
            default = "#71be6b",
            regexp = "#71be6b",
            other = "#71be6b",
        },

        constant = {
            default = "#beb86b",
            character = {
                default = "#d52e4d",
                escape = "#6bbeb8",
            },
            language = "#beb86b",
            numeric = {
                default = "#beb86b",
                float = "#beb86b",
            },
        },

        entity = {
            name = {
                class = "#65a9f0",
                type = "#65a9f0",
                ["function"] = {
                    default = "#479bed",
                    constructor = "#479bed",
                },
                label = "#65a9f0",
                namespace = "#d52e4d",
                tag = "#65a9f0",
            },
            other = {
                ["attribute-name"] = "#65a9f0",
            },
        },

        keyword = {
            default = "#e878d6",
            control = {
                default = "#e878d6",
                import = "#479bed",
                flow = "#65a9f0",
            },
            operator = "#e878d6",
            declaration = "#e878d6",
        },

        storage = {
            type = "#e878d6",
            modifier = "#65a9f0",
        },

        variable = {
            default = "#aaaaaa",
            parameter = "#aaaaaa",
            other = {
                property = "#aaaaaa",
            },
        },

        punctuation = {
            separator = "#6a1726",
            section = "#6a1726",
        },

        markup = {
            default = "#aaaaaa",
            heading = "#479bed",
            raw = "#beb86b",
            link = "#beb86b",
            list = "#65a9f0",
            inserted = "#71be6b",
            deleted = "#d52e4d",
        },

        meta = {
            preprocessor = "#65a9f0",
        },
    },
}
