-- Auto-generated by tinted-builder-rust from a base24 scheme.
-- Translates base24 slots into tinted8-shaped keys. Mirrors base16.lua.mustache
-- exactly, plus brights from base12-17 and DiagnosticOk = bright_green.
-- Do not edit by hand.

return {
    variant = "light",

    -- Legacy base24 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#ffffff",
    base01 = "#e5e6e6",
    base02 = "#cbcdcd",
    base03 = "#b1b4b4",
    base04 = "#717575",
    base05 = "#585b5b",
    base06 = "#3f4141",
    base07 = "#011627",
    base08 = "#d3423e",
    base09 = "#daaa01",
    base0A = "#dac801",
    base0B = "#2aa298",
    base0C = "#08916a",
    base0D = "#4876d6",
    base0E = "#403f53",
    base0F = "#69211f",
    base10 = "#515656",
    base11 = "#282b2b",
    base12 = "#f76e6e",
    base13 = "#dac26b",
    base14 = "#49d0c5",
    base15 = "#00c990",
    base16 = "#5ca7e4",
    base17 = "#697098",

    palette = {
        black = {
            normal = "#ffffff",
            bright = "#e5e6e6",
        },
        gray = {
            dim = "#cbcdcd",
            normal = "#b1b4b4",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#717575",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#3f4141",
            normal = "#585b5b",
            bright = "#011627",
        },
        red = { normal = "#d3423e", bright = "#f76e6e" },
        -- base24 has no bright_orange slot; orange.bright falls back to .normal.
        orange = { normal = "#daaa01", bright = "#daaa01" },
        yellow = { normal = "#dac801", bright = "#dac26b" },
        green = { normal = "#2aa298", bright = "#49d0c5" },
        cyan = { normal = "#08916a", bright = "#00c990" },
        blue = { normal = "#4876d6", bright = "#5ca7e4" },
        magenta = { normal = "#403f53", bright = "#697098" },
        brown = { normal = "#69211f" },
    },

    ui = {
        global = {
            background = { normal = "#ffffff" },
            foreground = { normal = "#585b5b" },
        },
        cursor = {
            background = { normal = "#585b5b" },
            foreground = { normal = "#ffffff" },
        },
        gutter = { foreground = "#cbcdcd" },
        border = { normal = "#b1b4b4" },
        chrome = {
            background = {
                normal = "#cbcdcd",
                dark = "#e5e6e6",
            },
            foreground = {
                normal = "#585b5b",
                dark = "#717575",
            },
        },
        selection = { background = "#e5e6e6" },
        highlight = {
            line = { background = "#e5e6e6" },
            text = { background = "#cbcdcd" },
            search = {
                background = "#e5e6e6",
                foreground = "#dac801",
            },
        },
        status = {
            error = "#d3423e",
            warning = "#daaa01",
            info = "#dac801",
            -- DiagnosticOk uses bright_green (base14) in current code; preserve.
            success = "#49d0c5",
        },
    },

    syntax = {
        comment = "#b1b4b4",

        string = {
            default = "#2aa298",
            regexp = "#2aa298",
            other = "#2aa298",
        },

        constant = {
            default = "#daaa01",
            character = {
                default = "#d3423e",
                escape = "#08916a",
            },
            language = "#daaa01",
            numeric = {
                default = "#daaa01",
                float = "#daaa01",
            },
        },

        entity = {
            name = {
                class = "#dac801",
                type = "#dac801",
                ["function"] = {
                    default = "#4876d6",
                    constructor = "#4876d6",
                },
                label = "#dac801",
                namespace = "#d3423e",
                tag = "#dac801",
            },
            other = {
                ["attribute-name"] = "#dac801",
            },
        },

        keyword = {
            default = "#403f53",
            control = {
                default = "#403f53",
                import = "#4876d6",
                flow = "#dac801",
            },
            operator = "#403f53",
            declaration = "#403f53",
        },

        storage = {
            type = "#403f53",
            modifier = "#dac801",
        },

        variable = {
            default = "#585b5b",
            parameter = "#585b5b",
            other = {
                property = "#585b5b",
            },
        },

        punctuation = {
            separator = "#69211f",
            section = "#69211f",
        },

        markup = {
            default = "#585b5b",
            heading = "#4876d6",
            raw = "#daaa01",
            link = "#daaa01",
            list = "#dac801",
            inserted = "#2aa298",
            deleted = "#d3423e",
        },

        meta = {
            preprocessor = "#dac801",
        },
    },
}
