-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "light",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#f6f6f6",
    base01 = "#dedede",
    base02 = "#bde5f2",
    base03 = "#898989",
    base04 = "#767676",
    base05 = "#181818",
    base06 = "#e8e8e8",
    base07 = "#f8f8f8",
    base08 = "#9c5a02",
    base09 = "#c43e18",
    base0A = "#c48218",
    base0B = "#38781c",
    base0C = "#2d6bb1",
    base0D = "#48bac2",
    base0E = "#a94598",
    base0F = "#8b6c37",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#f6f6f6",
            bright = "#dedede",
        },
        gray = {
            dim = "#bde5f2",
            normal = "#898989",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#767676",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#e8e8e8",
            normal = "#181818",
            bright = "#f8f8f8",
        },
        red = { normal = "#9c5a02", bright = "#9c5a02" },
        orange = { normal = "#c43e18", bright = "#c43e18" },
        yellow = { normal = "#c48218", bright = "#c48218" },
        green = { normal = "#38781c", bright = "#38781c" },
        cyan = { normal = "#2d6bb1", bright = "#2d6bb1" },
        blue = { normal = "#48bac2", bright = "#48bac2" },
        magenta = { normal = "#a94598", bright = "#a94598" },
        brown = { normal = "#8b6c37" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#f6f6f6" },
            foreground = { normal = "#181818" },
        },
        cursor = {
            background = { normal = "#181818" },
            foreground = { normal = "#f6f6f6" },
        },
        gutter = { foreground = "#bde5f2" },
        border = { normal = "#898989" },
        chrome = {
            background = {
                normal = "#bde5f2",
                dark = "#dedede",
            },
            foreground = {
                normal = "#181818",
                dark = "#767676",
            },
        },
        selection = { background = "#dedede" },
        highlight = {
            line = { background = "#dedede" },
            text = { background = "#bde5f2" },
            search = {
                background = "#dedede",
                foreground = "#c48218",
            },
        },
        status = {
            error = "#9c5a02",
            warning = "#c43e18",
            info = "#c48218",
            success = "#38781c",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#898989",

        string = {
            default = "#38781c",
            regexp = "#38781c",
            other = "#38781c",
        },

        constant = {
            default = "#c43e18",
            character = {
                default = "#9c5a02",
                escape = "#2d6bb1",
            },
            language = "#c43e18",
            numeric = {
                default = "#c43e18",
                float = "#c43e18",
            },
        },

        entity = {
            name = {
                class = "#c48218",
                type = "#c48218",
                ["function"] = {
                    default = "#48bac2",
                    constructor = "#48bac2",
                },
                label = "#c48218",
                namespace = "#9c5a02",
                tag = "#c48218",
            },
            other = {
                ["attribute-name"] = "#c48218",
            },
        },

        keyword = {
            default = "#a94598",
            control = {
                default = "#a94598",
                import = "#48bac2",
                flow = "#c48218",
            },
            operator = "#a94598",
            declaration = "#a94598",
        },

        storage = {
            type = "#a94598",
            modifier = "#c48218",
        },

        variable = {
            default = "#181818",
            parameter = "#181818",
            other = {
                property = "#181818",
            },
        },

        punctuation = {
            separator = "#8b6c37",
            section = "#8b6c37",
        },

        markup = {
            default = "#181818",
            heading = "#48bac2",
            raw = "#c43e18",
            link = "#c43e18",
            list = "#c48218",
            inserted = "#38781c",
            deleted = "#9c5a02",
        },

        meta = {
            preprocessor = "#c48218",
        },
    },
}
