-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#0c0c0c",
    base01 = "#2f2f2f",
    base02 = "#535353",
    base03 = "#767676",
    base04 = "#b9b9b9",
    base05 = "#cccccc",
    base06 = "#dfdfdf",
    base07 = "#f2f2f2",
    base08 = "#e74856",
    base09 = "#c19c00",
    base0A = "#f9f1a5",
    base0B = "#16c60c",
    base0C = "#61d6d6",
    base0D = "#3b78ff",
    base0E = "#b4009e",
    base0F = "#13a10e",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#0c0c0c",
            bright = "#2f2f2f",
        },
        gray = {
            dim = "#535353",
            normal = "#767676",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#b9b9b9",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#dfdfdf",
            normal = "#cccccc",
            bright = "#f2f2f2",
        },
        red = { normal = "#e74856", bright = "#e74856" },
        orange = { normal = "#c19c00", bright = "#c19c00" },
        yellow = { normal = "#f9f1a5", bright = "#f9f1a5" },
        green = { normal = "#16c60c", bright = "#16c60c" },
        cyan = { normal = "#61d6d6", bright = "#61d6d6" },
        blue = { normal = "#3b78ff", bright = "#3b78ff" },
        magenta = { normal = "#b4009e", bright = "#b4009e" },
        brown = { normal = "#13a10e" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#0c0c0c" },
            foreground = { normal = "#cccccc" },
        },
        cursor = {
            background = { normal = "#cccccc" },
            foreground = { normal = "#0c0c0c" },
        },
        gutter = { foreground = "#535353" },
        border = { normal = "#767676" },
        chrome = {
            background = {
                normal = "#535353",
                dark = "#2f2f2f",
            },
            foreground = {
                normal = "#cccccc",
                dark = "#b9b9b9",
            },
        },
        selection = { background = "#2f2f2f" },
        highlight = {
            line = { background = "#2f2f2f" },
            text = { background = "#535353" },
            search = {
                background = "#2f2f2f",
                foreground = "#f9f1a5",
            },
        },
        status = {
            error = "#e74856",
            warning = "#c19c00",
            info = "#f9f1a5",
            success = "#16c60c",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#767676",

        string = {
            default = "#16c60c",
            regexp = "#16c60c",
            other = "#16c60c",
        },

        constant = {
            default = "#c19c00",
            character = {
                default = "#e74856",
                escape = "#61d6d6",
            },
            language = "#c19c00",
            numeric = {
                default = "#c19c00",
                float = "#c19c00",
            },
        },

        entity = {
            name = {
                class = "#f9f1a5",
                type = "#f9f1a5",
                ["function"] = {
                    default = "#3b78ff",
                    constructor = "#3b78ff",
                },
                label = "#f9f1a5",
                namespace = "#e74856",
                tag = "#f9f1a5",
            },
            other = {
                ["attribute-name"] = "#f9f1a5",
            },
        },

        keyword = {
            default = "#b4009e",
            control = {
                default = "#b4009e",
                import = "#3b78ff",
                flow = "#f9f1a5",
            },
            operator = "#b4009e",
            declaration = "#b4009e",
        },

        storage = {
            type = "#b4009e",
            modifier = "#f9f1a5",
        },

        variable = {
            default = "#cccccc",
            parameter = "#cccccc",
            other = {
                property = "#cccccc",
            },
        },

        punctuation = {
            separator = "#13a10e",
            section = "#13a10e",
        },

        markup = {
            default = "#cccccc",
            heading = "#3b78ff",
            raw = "#c19c00",
            link = "#c19c00",
            list = "#f9f1a5",
            inserted = "#16c60c",
            deleted = "#e74856",
        },

        meta = {
            preprocessor = "#f9f1a5",
        },
    },
}
