-- Auto-generated by tinted-builder-rust from a base24 scheme.
-- Translates base24 slots into tinted8-shaped keys. Mirrors base16.lua.mustache
-- exactly, plus brights from base12-17 and DiagnosticOk = bright_green.
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base24 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#1b1d1e",
    base01 = "#1b1d1e",
    base02 = "#505354",
    base03 = "#6d6f6e",
    base04 = "#8a8c89",
    base05 = "#a7a8a3",
    base06 = "#c5c5be",
    base07 = "#dadad5",
    base08 = "#e6db43",
    base09 = "#f3fd21",
    base0A = "#909495",
    base0B = "#c8be46",
    base0C = "#615f5e",
    base0D = "#737074",
    base0E = "#737271",
    base0F = "#736d21",
    base10 = "#353738",
    base11 = "#1a1b1c",
    base12 = "#fff68d",
    base13 = "#feed6c",
    base14 = "#fff27c",
    base15 = "#a2a2a5",
    base16 = "#909495",
    base17 = "#9a999d",

    palette = {
        black = {
            normal = "#1b1d1e",
            bright = "#1b1d1e",
        },
        gray = {
            dim = "#505354",
            normal = "#6d6f6e",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#8a8c89",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#c5c5be",
            normal = "#a7a8a3",
            bright = "#dadad5",
        },
        red     = { normal = "#e6db43", bright = "#fff68d" },
        -- base24 has no bright_orange slot; orange.bright falls back to .normal.
        orange  = { normal = "#f3fd21", bright = "#f3fd21" },
        yellow  = { normal = "#909495", bright = "#feed6c" },
        green   = { normal = "#c8be46", bright = "#fff27c" },
        cyan    = { normal = "#615f5e", bright = "#a2a2a5" },
        blue    = { normal = "#737074", bright = "#909495" },
        magenta = { normal = "#737271", bright = "#9a999d" },
        brown   = { normal = "#736d21" },
    },

    ui = {
        global = {
            background = { normal = "#1b1d1e" },
            foreground = { normal = "#a7a8a3" },
        },
        cursor = {
            background = { normal = "#a7a8a3" },
            foreground = { normal = "#1b1d1e" },
        },
        gutter = { foreground = "#505354" },
        border = { normal = "#6d6f6e" },
        chrome = {
            background = {
                normal = "#505354",
                dark = "#1b1d1e",
            },
            foreground = {
                normal = "#a7a8a3",
                dark = "#8a8c89",
            },
        },
        selection = { background = "#1b1d1e" },
        highlight = {
            line = { background = "#1b1d1e" },
            text = { background = "#505354" },
            search = {
                background = "#1b1d1e",
                foreground = "#909495",
            },
        },
        status = {
            error = "#e6db43",
            warning = "#f3fd21",
            info = "#909495",
            -- DiagnosticOk uses bright_green (base14) in current code; preserve.
            success = "#fff27c",
        },
    },

    syntax = {
        comment = "#6d6f6e",

        string = {
            default = "#c8be46",
            regexp = "#c8be46",
            other = "#c8be46",
        },

        constant = {
            default = "#f3fd21",
            character = {
                default = "#e6db43",
                escape = "#615f5e",
            },
            language = "#f3fd21",
            numeric = {
                default = "#f3fd21",
                float = "#f3fd21",
            },
        },

        entity = {
            name = {
                class = "#909495",
                type = "#909495",
                ["function"] = {
                    default = "#737074",
                    constructor = "#737074",
                },
                label = "#909495",
                namespace = "#e6db43",
                tag = "#909495",
            },
            other = {
                ["attribute-name"] = "#909495",
            },
        },

        keyword = {
            default = "#737271",
            control = {
                default = "#737271",
                import = "#737074",
                flow = "#909495",
            },
            operator = "#737271",
            declaration = "#737271",
        },

        storage = {
            type = "#737271",
            modifier = "#909495",
        },

        variable = {
            default = "#a7a8a3",
            parameter = "#a7a8a3",
            other = {
                property = "#a7a8a3",
            },
        },

        punctuation = {
            separator = "#736d21",
            section = "#736d21",
        },

        markup = {
            default = "#a7a8a3",
            heading = "#737074",
            raw = "#f3fd21",
            link = "#f3fd21",
            list = "#909495",
            inserted = "#c8be46",
            deleted = "#e6db43",
        },

        meta = {
            preprocessor = "#909495",
        },
    },
}
