-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#202020",
    base01 = "#2a2827",
    base02 = "#504945",
    base03 = "#5a524c",
    base04 = "#bdae93",
    base05 = "#ddc7a1",
    base06 = "#ebdbb2",
    base07 = "#fbf1c7",
    base08 = "#ea6962",
    base09 = "#e78a4e",
    base0A = "#d8a657",
    base0B = "#a9b665",
    base0C = "#89b482",
    base0D = "#7daea3",
    base0E = "#d3869b",
    base0F = "#bd6f3e",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#202020",
            bright = "#2a2827",
        },
        gray = {
            dim = "#504945",
            normal = "#5a524c",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#bdae93",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#ebdbb2",
            normal = "#ddc7a1",
            bright = "#fbf1c7",
        },
        red     = { normal = "#ea6962", bright = "#ea6962" },
        orange  = { normal = "#e78a4e", bright = "#e78a4e" },
        yellow  = { normal = "#d8a657", bright = "#d8a657" },
        green   = { normal = "#a9b665", bright = "#a9b665" },
        cyan    = { normal = "#89b482", bright = "#89b482" },
        blue    = { normal = "#7daea3", bright = "#7daea3" },
        magenta = { normal = "#d3869b", bright = "#d3869b" },
        brown   = { normal = "#bd6f3e" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#202020" },
            foreground = { normal = "#ddc7a1" },
        },
        cursor = {
            background = { normal = "#ddc7a1" },
            foreground = { normal = "#202020" },
        },
        gutter = { foreground = "#504945" },
        border = { normal = "#5a524c" },
        chrome = {
            background = {
                normal = "#504945",
                dark = "#2a2827",
            },
            foreground = {
                normal = "#ddc7a1",
                dark = "#bdae93",
            },
        },
        selection = { background = "#2a2827" },
        highlight = {
            line = { background = "#2a2827" },
            text = { background = "#504945" },
            search = {
                background = "#2a2827",
                foreground = "#d8a657",
            },
        },
        status = {
            error = "#ea6962",
            warning = "#e78a4e",
            info = "#d8a657",
            success = "#a9b665",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#5a524c",

        string = {
            default = "#a9b665",
            regexp = "#a9b665",
            other = "#a9b665",
        },

        constant = {
            default = "#e78a4e",
            character = {
                default = "#ea6962",
                escape = "#89b482",
            },
            language = "#e78a4e",
            numeric = {
                default = "#e78a4e",
                float = "#e78a4e",
            },
        },

        entity = {
            name = {
                class = "#d8a657",
                type = "#d8a657",
                ["function"] = {
                    default = "#7daea3",
                    constructor = "#7daea3",
                },
                label = "#d8a657",
                namespace = "#ea6962",
                tag = "#d8a657",
            },
            other = {
                ["attribute-name"] = "#d8a657",
            },
        },

        keyword = {
            default = "#d3869b",
            control = {
                default = "#d3869b",
                import = "#7daea3",
                flow = "#d8a657",
            },
            operator = "#d3869b",
            declaration = "#d3869b",
        },

        storage = {
            type = "#d3869b",
            modifier = "#d8a657",
        },

        variable = {
            default = "#ddc7a1",
            parameter = "#ddc7a1",
            other = {
                property = "#ddc7a1",
            },
        },

        punctuation = {
            separator = "#bd6f3e",
            section = "#bd6f3e",
        },

        markup = {
            default = "#ddc7a1",
            heading = "#7daea3",
            raw = "#e78a4e",
            link = "#e78a4e",
            list = "#d8a657",
            inserted = "#a9b665",
            deleted = "#ea6962",
        },

        meta = {
            preprocessor = "#d8a657",
        },
    },
}
