-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "light",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#ebf8ff",
    base01 = "#c1e4f6",
    base02 = "#7ea2b4",
    base03 = "#7195a8",
    base04 = "#5a7b8c",
    base05 = "#516d7b",
    base06 = "#1f292e",
    base07 = "#161b1d",
    base08 = "#d22d72",
    base09 = "#935c25",
    base0A = "#8a8a0f",
    base0B = "#568c3b",
    base0C = "#2d8f6f",
    base0D = "#257fad",
    base0E = "#6b6bb8",
    base0F = "#b72dd2",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#ebf8ff",
            bright = "#c1e4f6",
        },
        gray = {
            dim = "#7ea2b4",
            normal = "#7195a8",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#5a7b8c",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#1f292e",
            normal = "#516d7b",
            bright = "#161b1d",
        },
        red     = { normal = "#d22d72", bright = "#d22d72" },
        orange  = { normal = "#935c25", bright = "#935c25" },
        yellow  = { normal = "#8a8a0f", bright = "#8a8a0f" },
        green   = { normal = "#568c3b", bright = "#568c3b" },
        cyan    = { normal = "#2d8f6f", bright = "#2d8f6f" },
        blue    = { normal = "#257fad", bright = "#257fad" },
        magenta = { normal = "#6b6bb8", bright = "#6b6bb8" },
        brown   = { normal = "#b72dd2" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#ebf8ff" },
            foreground = { normal = "#516d7b" },
        },
        cursor = {
            background = { normal = "#516d7b" },
            foreground = { normal = "#ebf8ff" },
        },
        gutter = { foreground = "#7ea2b4" },
        border = { normal = "#7195a8" },
        chrome = {
            background = {
                normal = "#7ea2b4",
                dark = "#c1e4f6",
            },
            foreground = {
                normal = "#516d7b",
                dark = "#5a7b8c",
            },
        },
        selection = { background = "#c1e4f6" },
        highlight = {
            line = { background = "#c1e4f6" },
            text = { background = "#7ea2b4" },
            search = {
                background = "#c1e4f6",
                foreground = "#8a8a0f",
            },
        },
        status = {
            error = "#d22d72",
            warning = "#935c25",
            info = "#8a8a0f",
            success = "#568c3b",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#7195a8",

        string = {
            default = "#568c3b",
            regexp = "#568c3b",
            other = "#568c3b",
        },

        constant = {
            default = "#935c25",
            character = {
                default = "#d22d72",
                escape = "#2d8f6f",
            },
            language = "#935c25",
            numeric = {
                default = "#935c25",
                float = "#935c25",
            },
        },

        entity = {
            name = {
                class = "#8a8a0f",
                type = "#8a8a0f",
                ["function"] = {
                    default = "#257fad",
                    constructor = "#257fad",
                },
                label = "#8a8a0f",
                namespace = "#d22d72",
                tag = "#8a8a0f",
            },
            other = {
                ["attribute-name"] = "#8a8a0f",
            },
        },

        keyword = {
            default = "#6b6bb8",
            control = {
                default = "#6b6bb8",
                import = "#257fad",
                flow = "#8a8a0f",
            },
            operator = "#6b6bb8",
            declaration = "#6b6bb8",
        },

        storage = {
            type = "#6b6bb8",
            modifier = "#8a8a0f",
        },

        variable = {
            default = "#516d7b",
            parameter = "#516d7b",
            other = {
                property = "#516d7b",
            },
        },

        punctuation = {
            separator = "#b72dd2",
            section = "#b72dd2",
        },

        markup = {
            default = "#516d7b",
            heading = "#257fad",
            raw = "#935c25",
            link = "#935c25",
            list = "#8a8a0f",
            inserted = "#568c3b",
            deleted = "#d22d72",
        },

        meta = {
            preprocessor = "#8a8a0f",
        },
    },
}
