-- Auto-generated by tinted-builder-rust from a base24 scheme.
-- Translates base24 slots into tinted8-shaped keys. Mirrors base16.lua.mustache
-- exactly, plus brights from base12-17 and DiagnosticOk = bright_green.
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base24 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#212121",
    base01 = "#212121",
    base02 = "#ffffff",
    base03 = "#c0f1f8",
    base04 = "#81e2f0",
    base05 = "#42d3e8",
    base06 = "#02c4e0",
    base07 = "#e0e0e0",
    base08 = "#e1a7bf",
    base09 = "#c4c9bf",
    base0A = "#79afd2",
    base0B = "#80d778",
    base0C = "#14ab9c",
    base0D = "#254a49",
    base0E = "#a380d3",
    base0F = "#70535f",
    base10 = "#aaaaaa",
    base11 = "#555555",
    base12 = "#ffccd8",
    base13 = "#d0cbc9",
    base14 = "#bdffa8",
    base15 = "#8bdee0",
    base16 = "#79afd2",
    base17 = "#c4a7d8",

    palette = {
        black = {
            normal = "#212121",
            bright = "#212121",
        },
        gray = {
            dim = "#ffffff",
            normal = "#c0f1f8",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#81e2f0",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#02c4e0",
            normal = "#42d3e8",
            bright = "#e0e0e0",
        },
        red     = { normal = "#e1a7bf", bright = "#ffccd8" },
        -- base24 has no bright_orange slot; orange.bright falls back to .normal.
        orange  = { normal = "#c4c9bf", bright = "#c4c9bf" },
        yellow  = { normal = "#79afd2", bright = "#d0cbc9" },
        green   = { normal = "#80d778", bright = "#bdffa8" },
        cyan    = { normal = "#14ab9c", bright = "#8bdee0" },
        blue    = { normal = "#254a49", bright = "#79afd2" },
        magenta = { normal = "#a380d3", bright = "#c4a7d8" },
        brown   = { normal = "#70535f" },
    },

    ui = {
        global = {
            background = { normal = "#212121" },
            foreground = { normal = "#42d3e8" },
        },
        cursor = {
            background = { normal = "#42d3e8" },
            foreground = { normal = "#212121" },
        },
        gutter = { foreground = "#ffffff" },
        border = { normal = "#c0f1f8" },
        chrome = {
            background = {
                normal = "#ffffff",
                dark = "#212121",
            },
            foreground = {
                normal = "#42d3e8",
                dark = "#81e2f0",
            },
        },
        selection = { background = "#212121" },
        highlight = {
            line = { background = "#212121" },
            text = { background = "#ffffff" },
            search = {
                background = "#212121",
                foreground = "#79afd2",
            },
        },
        status = {
            error = "#e1a7bf",
            warning = "#c4c9bf",
            info = "#79afd2",
            -- DiagnosticOk uses bright_green (base14) in current code; preserve.
            success = "#bdffa8",
        },
    },

    syntax = {
        comment = "#c0f1f8",

        string = {
            default = "#80d778",
            regexp = "#80d778",
            other = "#80d778",
        },

        constant = {
            default = "#c4c9bf",
            character = {
                default = "#e1a7bf",
                escape = "#14ab9c",
            },
            language = "#c4c9bf",
            numeric = {
                default = "#c4c9bf",
                float = "#c4c9bf",
            },
        },

        entity = {
            name = {
                class = "#79afd2",
                type = "#79afd2",
                ["function"] = {
                    default = "#254a49",
                    constructor = "#254a49",
                },
                label = "#79afd2",
                namespace = "#e1a7bf",
                tag = "#79afd2",
            },
            other = {
                ["attribute-name"] = "#79afd2",
            },
        },

        keyword = {
            default = "#a380d3",
            control = {
                default = "#a380d3",
                import = "#254a49",
                flow = "#79afd2",
            },
            operator = "#a380d3",
            declaration = "#a380d3",
        },

        storage = {
            type = "#a380d3",
            modifier = "#79afd2",
        },

        variable = {
            default = "#42d3e8",
            parameter = "#42d3e8",
            other = {
                property = "#42d3e8",
            },
        },

        punctuation = {
            separator = "#70535f",
            section = "#70535f",
        },

        markup = {
            default = "#42d3e8",
            heading = "#254a49",
            raw = "#c4c9bf",
            link = "#c4c9bf",
            list = "#79afd2",
            inserted = "#80d778",
            deleted = "#e1a7bf",
        },

        meta = {
            preprocessor = "#79afd2",
        },
    },
}
