-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#303446",
    base01 = "#292c3c",
    base02 = "#414559",
    base03 = "#51576d",
    base04 = "#626880",
    base05 = "#c6d0f5",
    base06 = "#f2d5cf",
    base07 = "#babbf1",
    base08 = "#e78284",
    base09 = "#ef9f76",
    base0A = "#e5c890",
    base0B = "#a6d189",
    base0C = "#81c8be",
    base0D = "#8caaee",
    base0E = "#ca9ee6",
    base0F = "#eebebe",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#303446",
            bright = "#292c3c",
        },
        gray = {
            dim = "#414559",
            normal = "#51576d",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#626880",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#f2d5cf",
            normal = "#c6d0f5",
            bright = "#babbf1",
        },
        red     = { normal = "#e78284", bright = "#e78284" },
        orange  = { normal = "#ef9f76", bright = "#ef9f76" },
        yellow  = { normal = "#e5c890", bright = "#e5c890" },
        green   = { normal = "#a6d189", bright = "#a6d189" },
        cyan    = { normal = "#81c8be", bright = "#81c8be" },
        blue    = { normal = "#8caaee", bright = "#8caaee" },
        magenta = { normal = "#ca9ee6", bright = "#ca9ee6" },
        brown   = { normal = "#eebebe" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#303446" },
            foreground = { normal = "#c6d0f5" },
        },
        cursor = {
            background = { normal = "#c6d0f5" },
            foreground = { normal = "#303446" },
        },
        gutter = { foreground = "#414559" },
        border = { normal = "#51576d" },
        chrome = {
            background = {
                normal = "#414559",
                dark = "#292c3c",
            },
            foreground = {
                normal = "#c6d0f5",
                dark = "#626880",
            },
        },
        selection = { background = "#292c3c" },
        highlight = {
            line = { background = "#292c3c" },
            text = { background = "#414559" },
            search = {
                background = "#292c3c",
                foreground = "#e5c890",
            },
        },
        status = {
            error = "#e78284",
            warning = "#ef9f76",
            info = "#e5c890",
            success = "#a6d189",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#51576d",

        string = {
            default = "#a6d189",
            regexp = "#a6d189",
            other = "#a6d189",
        },

        constant = {
            default = "#ef9f76",
            character = {
                default = "#e78284",
                escape = "#81c8be",
            },
            language = "#ef9f76",
            numeric = {
                default = "#ef9f76",
                float = "#ef9f76",
            },
        },

        entity = {
            name = {
                class = "#e5c890",
                type = "#e5c890",
                ["function"] = {
                    default = "#8caaee",
                    constructor = "#8caaee",
                },
                label = "#e5c890",
                namespace = "#e78284",
                tag = "#e5c890",
            },
            other = {
                ["attribute-name"] = "#e5c890",
            },
        },

        keyword = {
            default = "#ca9ee6",
            control = {
                default = "#ca9ee6",
                import = "#8caaee",
                flow = "#e5c890",
            },
            operator = "#ca9ee6",
            declaration = "#ca9ee6",
        },

        storage = {
            type = "#ca9ee6",
            modifier = "#e5c890",
        },

        variable = {
            default = "#c6d0f5",
            parameter = "#c6d0f5",
            other = {
                property = "#c6d0f5",
            },
        },

        punctuation = {
            separator = "#eebebe",
            section = "#eebebe",
        },

        markup = {
            default = "#c6d0f5",
            heading = "#8caaee",
            raw = "#ef9f76",
            link = "#ef9f76",
            list = "#e5c890",
            inserted = "#a6d189",
            deleted = "#e78284",
        },

        meta = {
            preprocessor = "#e5c890",
        },
    },
}
