-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#17191e",
    base01 = "#22262d",
    base02 = "#3c3f4c",
    base03 = "#383a47",
    base04 = "#555e70",
    base05 = "#8b9cbe",
    base06 = "#b2bfd9",
    base07 = "#f4f4f7",
    base08 = "#ff29a8",
    base09 = "#85ffe0",
    base0A = "#f0ffaa",
    base0B = "#0badff",
    base0C = "#8265ff",
    base0D = "#00eaff",
    base0E = "#00f6d9",
    base0F = "#ff3d81",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#17191e",
            bright = "#22262d",
        },
        gray = {
            dim = "#3c3f4c",
            normal = "#383a47",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#555e70",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#b2bfd9",
            normal = "#8b9cbe",
            bright = "#f4f4f7",
        },
        red     = { normal = "#ff29a8", bright = "#ff29a8" },
        orange  = { normal = "#85ffe0", bright = "#85ffe0" },
        yellow  = { normal = "#f0ffaa", bright = "#f0ffaa" },
        green   = { normal = "#0badff", bright = "#0badff" },
        cyan    = { normal = "#8265ff", bright = "#8265ff" },
        blue    = { normal = "#00eaff", bright = "#00eaff" },
        magenta = { normal = "#00f6d9", bright = "#00f6d9" },
        brown   = { normal = "#ff3d81" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#17191e" },
            foreground = { normal = "#8b9cbe" },
        },
        cursor = {
            background = { normal = "#8b9cbe" },
            foreground = { normal = "#17191e" },
        },
        gutter = { foreground = "#3c3f4c" },
        border = { normal = "#383a47" },
        chrome = {
            background = {
                normal = "#3c3f4c",
                dark = "#22262d",
            },
            foreground = {
                normal = "#8b9cbe",
                dark = "#555e70",
            },
        },
        selection = { background = "#22262d" },
        highlight = {
            line = { background = "#22262d" },
            text = { background = "#3c3f4c" },
            search = {
                background = "#22262d",
                foreground = "#f0ffaa",
            },
        },
        status = {
            error = "#ff29a8",
            warning = "#85ffe0",
            info = "#f0ffaa",
            success = "#0badff",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#383a47",

        string = {
            default = "#0badff",
            regexp = "#0badff",
            other = "#0badff",
        },

        constant = {
            default = "#85ffe0",
            character = {
                default = "#ff29a8",
                escape = "#8265ff",
            },
            language = "#85ffe0",
            numeric = {
                default = "#85ffe0",
                float = "#85ffe0",
            },
        },

        entity = {
            name = {
                class = "#f0ffaa",
                type = "#f0ffaa",
                ["function"] = {
                    default = "#00eaff",
                    constructor = "#00eaff",
                },
                label = "#f0ffaa",
                namespace = "#ff29a8",
                tag = "#f0ffaa",
            },
            other = {
                ["attribute-name"] = "#f0ffaa",
            },
        },

        keyword = {
            default = "#00f6d9",
            control = {
                default = "#00f6d9",
                import = "#00eaff",
                flow = "#f0ffaa",
            },
            operator = "#00f6d9",
            declaration = "#00f6d9",
        },

        storage = {
            type = "#00f6d9",
            modifier = "#f0ffaa",
        },

        variable = {
            default = "#8b9cbe",
            parameter = "#8b9cbe",
            other = {
                property = "#8b9cbe",
            },
        },

        punctuation = {
            separator = "#ff3d81",
            section = "#ff3d81",
        },

        markup = {
            default = "#8b9cbe",
            heading = "#00eaff",
            raw = "#85ffe0",
            link = "#85ffe0",
            list = "#f0ffaa",
            inserted = "#0badff",
            deleted = "#ff29a8",
        },

        meta = {
            preprocessor = "#f0ffaa",
        },
    },
}
