-- Auto-generated by tinted-builder-rust from a base24 scheme.
-- Translates base24 slots into tinted8-shaped keys. Mirrors base16.lua.mustache
-- exactly, plus brights from base12-17 and DiagnosticOk = bright_green.
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base24 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#000000",
    base01 = "#000000",
    base02 = "#555555",
    base03 = "#6e6e6e",
    base04 = "#888888",
    base05 = "#a1a1a1",
    base06 = "#bbbbbb",
    base07 = "#ffffff",
    base08 = "#9f0000",
    base09 = "#ffcf00",
    base0A = "#0000ff",
    base0B = "#008b00",
    base0C = "#008b8b",
    base0D = "#0081ff",
    base0E = "#bc00ca",
    base0F = "#4f0000",
    base10 = "#383838",
    base11 = "#1c1c1c",
    base12 = "#ff0000",
    base13 = "#ffff00",
    base14 = "#00ee00",
    base15 = "#00cdcd",
    base16 = "#0000ff",
    base17 = "#ff00ff",

    palette = {
        black = {
            normal = "#000000",
            bright = "#000000",
        },
        gray = {
            dim = "#555555",
            normal = "#6e6e6e",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#888888",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#bbbbbb",
            normal = "#a1a1a1",
            bright = "#ffffff",
        },
        red = { normal = "#9f0000", bright = "#ff0000" },
        -- base24 has no bright_orange slot; orange.bright falls back to .normal.
        orange = { normal = "#ffcf00", bright = "#ffcf00" },
        yellow = { normal = "#0000ff", bright = "#ffff00" },
        green = { normal = "#008b00", bright = "#00ee00" },
        cyan = { normal = "#008b8b", bright = "#00cdcd" },
        blue = { normal = "#0081ff", bright = "#0000ff" },
        magenta = { normal = "#bc00ca", bright = "#ff00ff" },
        brown = { normal = "#4f0000" },
    },

    ui = {
        global = {
            background = { normal = "#000000" },
            foreground = { normal = "#a1a1a1" },
        },
        cursor = {
            background = { normal = "#a1a1a1" },
            foreground = { normal = "#000000" },
        },
        gutter = { foreground = "#555555" },
        border = { normal = "#6e6e6e" },
        chrome = {
            background = {
                normal = "#555555",
                dark = "#000000",
            },
            foreground = {
                normal = "#a1a1a1",
                dark = "#888888",
            },
        },
        selection = { background = "#000000" },
        highlight = {
            line = { background = "#000000" },
            text = { background = "#555555" },
            search = {
                background = "#000000",
                foreground = "#0000ff",
            },
        },
        status = {
            error = "#9f0000",
            warning = "#ffcf00",
            info = "#0000ff",
            -- DiagnosticOk uses bright_green (base14) in current code; preserve.
            success = "#00ee00",
        },
    },

    syntax = {
        comment = "#6e6e6e",

        string = {
            default = "#008b00",
            regexp = "#008b00",
            other = "#008b00",
        },

        constant = {
            default = "#ffcf00",
            character = {
                default = "#9f0000",
                escape = "#008b8b",
            },
            language = "#ffcf00",
            numeric = {
                default = "#ffcf00",
                float = "#ffcf00",
            },
        },

        entity = {
            name = {
                class = "#0000ff",
                type = "#0000ff",
                ["function"] = {
                    default = "#0081ff",
                    constructor = "#0081ff",
                },
                label = "#0000ff",
                namespace = "#9f0000",
                tag = "#0000ff",
            },
            other = {
                ["attribute-name"] = "#0000ff",
            },
        },

        keyword = {
            default = "#bc00ca",
            control = {
                default = "#bc00ca",
                import = "#0081ff",
                flow = "#0000ff",
            },
            operator = "#bc00ca",
            declaration = "#bc00ca",
        },

        storage = {
            type = "#bc00ca",
            modifier = "#0000ff",
        },

        variable = {
            default = "#a1a1a1",
            parameter = "#a1a1a1",
            other = {
                property = "#a1a1a1",
            },
        },

        punctuation = {
            separator = "#4f0000",
            section = "#4f0000",
        },

        markup = {
            default = "#a1a1a1",
            heading = "#0081ff",
            raw = "#ffcf00",
            link = "#ffcf00",
            list = "#0000ff",
            inserted = "#008b00",
            deleted = "#9f0000",
        },

        meta = {
            preprocessor = "#0000ff",
        },
    },
}
