-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#171e1f",
    base01 = "#252c2d",
    base02 = "#373c3d",
    base03 = "#555e5f",
    base04 = "#818f80",
    base05 = "#c7c7a5",
    base06 = "#e3e3c8",
    base07 = "#e1eaef",
    base08 = "#ff4658",
    base09 = "#e6db74",
    base0A = "#fdb11f",
    base0B = "#499180",
    base0C = "#66d9ef",
    base0D = "#498091",
    base0E = "#9bc0c8",
    base0F = "#d27b53",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#171e1f",
            bright = "#252c2d",
        },
        gray = {
            dim = "#373c3d",
            normal = "#555e5f",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#818f80",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#e3e3c8",
            normal = "#c7c7a5",
            bright = "#e1eaef",
        },
        red     = { normal = "#ff4658", bright = "#ff4658" },
        orange  = { normal = "#e6db74", bright = "#e6db74" },
        yellow  = { normal = "#fdb11f", bright = "#fdb11f" },
        green   = { normal = "#499180", bright = "#499180" },
        cyan    = { normal = "#66d9ef", bright = "#66d9ef" },
        blue    = { normal = "#498091", bright = "#498091" },
        magenta = { normal = "#9bc0c8", bright = "#9bc0c8" },
        brown   = { normal = "#d27b53" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#171e1f" },
            foreground = { normal = "#c7c7a5" },
        },
        cursor = {
            background = { normal = "#c7c7a5" },
            foreground = { normal = "#171e1f" },
        },
        gutter = { foreground = "#373c3d" },
        border = { normal = "#555e5f" },
        chrome = {
            background = {
                normal = "#373c3d",
                dark = "#252c2d",
            },
            foreground = {
                normal = "#c7c7a5",
                dark = "#818f80",
            },
        },
        selection = { background = "#252c2d" },
        highlight = {
            line = { background = "#252c2d" },
            text = { background = "#373c3d" },
            search = {
                background = "#252c2d",
                foreground = "#fdb11f",
            },
        },
        status = {
            error = "#ff4658",
            warning = "#e6db74",
            info = "#fdb11f",
            success = "#499180",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#555e5f",

        string = {
            default = "#499180",
            regexp = "#499180",
            other = "#499180",
        },

        constant = {
            default = "#e6db74",
            character = {
                default = "#ff4658",
                escape = "#66d9ef",
            },
            language = "#e6db74",
            numeric = {
                default = "#e6db74",
                float = "#e6db74",
            },
        },

        entity = {
            name = {
                class = "#fdb11f",
                type = "#fdb11f",
                ["function"] = {
                    default = "#498091",
                    constructor = "#498091",
                },
                label = "#fdb11f",
                namespace = "#ff4658",
                tag = "#fdb11f",
            },
            other = {
                ["attribute-name"] = "#fdb11f",
            },
        },

        keyword = {
            default = "#9bc0c8",
            control = {
                default = "#9bc0c8",
                import = "#498091",
                flow = "#fdb11f",
            },
            operator = "#9bc0c8",
            declaration = "#9bc0c8",
        },

        storage = {
            type = "#9bc0c8",
            modifier = "#fdb11f",
        },

        variable = {
            default = "#c7c7a5",
            parameter = "#c7c7a5",
            other = {
                property = "#c7c7a5",
            },
        },

        punctuation = {
            separator = "#d27b53",
            section = "#d27b53",
        },

        markup = {
            default = "#c7c7a5",
            heading = "#498091",
            raw = "#e6db74",
            link = "#e6db74",
            list = "#fdb11f",
            inserted = "#499180",
            deleted = "#ff4658",
        },

        meta = {
            preprocessor = "#fdb11f",
        },
    },
}
