-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#151515",
    base01 = "#202020",
    base02 = "#303030",
    base03 = "#505050",
    base04 = "#b0b0b0",
    base05 = "#d0d0d0",
    base06 = "#e0e0e0",
    base07 = "#f5f5f5",
    base08 = "#ac4142",
    base09 = "#d28445",
    base0A = "#f4bf75",
    base0B = "#90a959",
    base0C = "#75b5aa",
    base0D = "#6a9fb5",
    base0E = "#aa759f",
    base0F = "#8f5536",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#151515",
            bright = "#202020",
        },
        gray = {
            dim = "#303030",
            normal = "#505050",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#b0b0b0",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#e0e0e0",
            normal = "#d0d0d0",
            bright = "#f5f5f5",
        },
        red     = { normal = "#ac4142", bright = "#ac4142" },
        orange  = { normal = "#d28445", bright = "#d28445" },
        yellow  = { normal = "#f4bf75", bright = "#f4bf75" },
        green   = { normal = "#90a959", bright = "#90a959" },
        cyan    = { normal = "#75b5aa", bright = "#75b5aa" },
        blue    = { normal = "#6a9fb5", bright = "#6a9fb5" },
        magenta = { normal = "#aa759f", bright = "#aa759f" },
        brown   = { normal = "#8f5536" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#151515" },
            foreground = { normal = "#d0d0d0" },
        },
        cursor = {
            background = { normal = "#d0d0d0" },
            foreground = { normal = "#151515" },
        },
        gutter = { foreground = "#303030" },
        border = { normal = "#505050" },
        chrome = {
            background = {
                normal = "#303030",
                dark = "#202020",
            },
            foreground = {
                normal = "#d0d0d0",
                dark = "#b0b0b0",
            },
        },
        selection = { background = "#202020" },
        highlight = {
            line = { background = "#202020" },
            text = { background = "#303030" },
            search = {
                background = "#202020",
                foreground = "#f4bf75",
            },
        },
        status = {
            error = "#ac4142",
            warning = "#d28445",
            info = "#f4bf75",
            success = "#90a959",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#505050",

        string = {
            default = "#90a959",
            regexp = "#90a959",
            other = "#90a959",
        },

        constant = {
            default = "#d28445",
            character = {
                default = "#ac4142",
                escape = "#75b5aa",
            },
            language = "#d28445",
            numeric = {
                default = "#d28445",
                float = "#d28445",
            },
        },

        entity = {
            name = {
                class = "#f4bf75",
                type = "#f4bf75",
                ["function"] = {
                    default = "#6a9fb5",
                    constructor = "#6a9fb5",
                },
                label = "#f4bf75",
                namespace = "#ac4142",
                tag = "#f4bf75",
            },
            other = {
                ["attribute-name"] = "#f4bf75",
            },
        },

        keyword = {
            default = "#aa759f",
            control = {
                default = "#aa759f",
                import = "#6a9fb5",
                flow = "#f4bf75",
            },
            operator = "#aa759f",
            declaration = "#aa759f",
        },

        storage = {
            type = "#aa759f",
            modifier = "#f4bf75",
        },

        variable = {
            default = "#d0d0d0",
            parameter = "#d0d0d0",
            other = {
                property = "#d0d0d0",
            },
        },

        punctuation = {
            separator = "#8f5536",
            section = "#8f5536",
        },

        markup = {
            default = "#d0d0d0",
            heading = "#6a9fb5",
            raw = "#d28445",
            link = "#d28445",
            list = "#f4bf75",
            inserted = "#90a959",
            deleted = "#ac4142",
        },

        meta = {
            preprocessor = "#f4bf75",
        },
    },
}
