-- Auto-generated by tinted-builder-rust from a base24 scheme.
-- Translates base24 slots into tinted8-shaped keys. Mirrors base16.lua.mustache
-- exactly, plus brights from base12-17 and DiagnosticOk = bright_green.
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base24 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#001e26",
    base01 = "#002731",
    base02 = "#465a61",
    base03 = "#6e7c7b",
    base04 = "#979e96",
    base05 = "#c0c0b0",
    base06 = "#e9e2cb",
    base07 = "#fcf4dc",
    base08 = "#d01b24",
    base09 = "#a57705",
    base0A = "#708183",
    base0B = "#728905",
    base0C = "#259185",
    base0D = "#2075c7",
    base0E = "#c61b6e",
    base0F = "#680d12",
    base10 = "#2e3c40",
    base11 = "#171e20",
    base12 = "#bd3612",
    base13 = "#52676f",
    base14 = "#465a61",
    base15 = "#81908f",
    base16 = "#708183",
    base17 = "#5856b9",

    palette = {
        black = {
            normal = "#001e26",
            bright = "#002731",
        },
        gray = {
            dim = "#465a61",
            normal = "#6e7c7b",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#979e96",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#e9e2cb",
            normal = "#c0c0b0",
            bright = "#fcf4dc",
        },
        red     = { normal = "#d01b24", bright = "#bd3612" },
        -- base24 has no bright_orange slot; orange.bright falls back to .normal.
        orange  = { normal = "#a57705", bright = "#a57705" },
        yellow  = { normal = "#708183", bright = "#52676f" },
        green   = { normal = "#728905", bright = "#465a61" },
        cyan    = { normal = "#259185", bright = "#81908f" },
        blue    = { normal = "#2075c7", bright = "#708183" },
        magenta = { normal = "#c61b6e", bright = "#5856b9" },
        brown   = { normal = "#680d12" },
    },

    ui = {
        global = {
            background = { normal = "#001e26" },
            foreground = { normal = "#c0c0b0" },
        },
        cursor = {
            background = { normal = "#c0c0b0" },
            foreground = { normal = "#001e26" },
        },
        gutter = { foreground = "#465a61" },
        border = { normal = "#6e7c7b" },
        chrome = {
            background = {
                normal = "#465a61",
                dark = "#002731",
            },
            foreground = {
                normal = "#c0c0b0",
                dark = "#979e96",
            },
        },
        selection = { background = "#002731" },
        highlight = {
            line = { background = "#002731" },
            text = { background = "#465a61" },
            search = {
                background = "#002731",
                foreground = "#708183",
            },
        },
        status = {
            error = "#d01b24",
            warning = "#a57705",
            info = "#708183",
            -- DiagnosticOk uses bright_green (base14) in current code; preserve.
            success = "#465a61",
        },
    },

    syntax = {
        comment = "#6e7c7b",

        string = {
            default = "#728905",
            regexp = "#728905",
            other = "#728905",
        },

        constant = {
            default = "#a57705",
            character = {
                default = "#d01b24",
                escape = "#259185",
            },
            language = "#a57705",
            numeric = {
                default = "#a57705",
                float = "#a57705",
            },
        },

        entity = {
            name = {
                class = "#708183",
                type = "#708183",
                ["function"] = {
                    default = "#2075c7",
                    constructor = "#2075c7",
                },
                label = "#708183",
                namespace = "#d01b24",
                tag = "#708183",
            },
            other = {
                ["attribute-name"] = "#708183",
            },
        },

        keyword = {
            default = "#c61b6e",
            control = {
                default = "#c61b6e",
                import = "#2075c7",
                flow = "#708183",
            },
            operator = "#c61b6e",
            declaration = "#c61b6e",
        },

        storage = {
            type = "#c61b6e",
            modifier = "#708183",
        },

        variable = {
            default = "#c0c0b0",
            parameter = "#c0c0b0",
            other = {
                property = "#c0c0b0",
            },
        },

        punctuation = {
            separator = "#680d12",
            section = "#680d12",
        },

        markup = {
            default = "#c0c0b0",
            heading = "#2075c7",
            raw = "#a57705",
            link = "#a57705",
            list = "#708183",
            inserted = "#728905",
            deleted = "#d01b24",
        },

        meta = {
            preprocessor = "#708183",
        },
    },
}
