-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#010409",
    base01 = "#21262d",
    base02 = "#30363d",
    base03 = "#484f58",
    base04 = "#8b949e",
    base05 = "#b1bac4",
    base06 = "#c9d1d9",
    base07 = "#f0f6fc",
    base08 = "#ff7b72",
    base09 = "#f0883e",
    base0A = "#d29922",
    base0B = "#3fb950",
    base0C = "#a5d6ff",
    base0D = "#58a6ff",
    base0E = "#f778ba",
    base0F = "#bd561d",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#010409",
            bright = "#21262d",
        },
        gray = {
            dim = "#30363d",
            normal = "#484f58",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#8b949e",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#c9d1d9",
            normal = "#b1bac4",
            bright = "#f0f6fc",
        },
        red     = { normal = "#ff7b72", bright = "#ff7b72" },
        orange  = { normal = "#f0883e", bright = "#f0883e" },
        yellow  = { normal = "#d29922", bright = "#d29922" },
        green   = { normal = "#3fb950", bright = "#3fb950" },
        cyan    = { normal = "#a5d6ff", bright = "#a5d6ff" },
        blue    = { normal = "#58a6ff", bright = "#58a6ff" },
        magenta = { normal = "#f778ba", bright = "#f778ba" },
        brown   = { normal = "#bd561d" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#010409" },
            foreground = { normal = "#b1bac4" },
        },
        cursor = {
            background = { normal = "#b1bac4" },
            foreground = { normal = "#010409" },
        },
        gutter = { foreground = "#30363d" },
        border = { normal = "#484f58" },
        chrome = {
            background = {
                normal = "#30363d",
                dark = "#21262d",
            },
            foreground = {
                normal = "#b1bac4",
                dark = "#8b949e",
            },
        },
        selection = { background = "#21262d" },
        highlight = {
            line = { background = "#21262d" },
            text = { background = "#30363d" },
            search = {
                background = "#21262d",
                foreground = "#d29922",
            },
        },
        status = {
            error = "#ff7b72",
            warning = "#f0883e",
            info = "#d29922",
            success = "#3fb950",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#484f58",

        string = {
            default = "#3fb950",
            regexp = "#3fb950",
            other = "#3fb950",
        },

        constant = {
            default = "#f0883e",
            character = {
                default = "#ff7b72",
                escape = "#a5d6ff",
            },
            language = "#f0883e",
            numeric = {
                default = "#f0883e",
                float = "#f0883e",
            },
        },

        entity = {
            name = {
                class = "#d29922",
                type = "#d29922",
                ["function"] = {
                    default = "#58a6ff",
                    constructor = "#58a6ff",
                },
                label = "#d29922",
                namespace = "#ff7b72",
                tag = "#d29922",
            },
            other = {
                ["attribute-name"] = "#d29922",
            },
        },

        keyword = {
            default = "#f778ba",
            control = {
                default = "#f778ba",
                import = "#58a6ff",
                flow = "#d29922",
            },
            operator = "#f778ba",
            declaration = "#f778ba",
        },

        storage = {
            type = "#f778ba",
            modifier = "#d29922",
        },

        variable = {
            default = "#b1bac4",
            parameter = "#b1bac4",
            other = {
                property = "#b1bac4",
            },
        },

        punctuation = {
            separator = "#bd561d",
            section = "#bd561d",
        },

        markup = {
            default = "#b1bac4",
            heading = "#58a6ff",
            raw = "#f0883e",
            link = "#f0883e",
            list = "#d29922",
            inserted = "#3fb950",
            deleted = "#ff7b72",
        },

        meta = {
            preprocessor = "#d29922",
        },
    },
}
