-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#272822",
    base01 = "#383830",
    base02 = "#49483e",
    base03 = "#75715e",
    base04 = "#a59f85",
    base05 = "#f8f8f2",
    base06 = "#f5f4f1",
    base07 = "#f9f8f5",
    base08 = "#f92672",
    base09 = "#fd971f",
    base0A = "#f4bf75",
    base0B = "#a6e22e",
    base0C = "#a1efe4",
    base0D = "#66d9ef",
    base0E = "#ae81ff",
    base0F = "#cc6633",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#272822",
            bright = "#383830",
        },
        gray = {
            dim = "#49483e",
            normal = "#75715e",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#a59f85",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#f5f4f1",
            normal = "#f8f8f2",
            bright = "#f9f8f5",
        },
        red = { normal = "#f92672", bright = "#f92672" },
        orange = { normal = "#fd971f", bright = "#fd971f" },
        yellow = { normal = "#f4bf75", bright = "#f4bf75" },
        green = { normal = "#a6e22e", bright = "#a6e22e" },
        cyan = { normal = "#a1efe4", bright = "#a1efe4" },
        blue = { normal = "#66d9ef", bright = "#66d9ef" },
        magenta = { normal = "#ae81ff", bright = "#ae81ff" },
        brown = { normal = "#cc6633" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#272822" },
            foreground = { normal = "#f8f8f2" },
        },
        cursor = {
            background = { normal = "#f8f8f2" },
            foreground = { normal = "#272822" },
        },
        gutter = { foreground = "#49483e" },
        border = { normal = "#75715e" },
        chrome = {
            background = {
                normal = "#49483e",
                dark = "#383830",
            },
            foreground = {
                normal = "#f8f8f2",
                dark = "#a59f85",
            },
        },
        selection = { background = "#383830" },
        highlight = {
            line = { background = "#383830" },
            text = { background = "#49483e" },
            search = {
                background = "#383830",
                foreground = "#f4bf75",
            },
        },
        status = {
            error = "#f92672",
            warning = "#fd971f",
            info = "#f4bf75",
            success = "#a6e22e",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#75715e",

        string = {
            default = "#a6e22e",
            regexp = "#a6e22e",
            other = "#a6e22e",
        },

        constant = {
            default = "#fd971f",
            character = {
                default = "#f92672",
                escape = "#a1efe4",
            },
            language = "#fd971f",
            numeric = {
                default = "#fd971f",
                float = "#fd971f",
            },
        },

        entity = {
            name = {
                class = "#f4bf75",
                type = "#f4bf75",
                ["function"] = {
                    default = "#66d9ef",
                    constructor = "#66d9ef",
                },
                label = "#f4bf75",
                namespace = "#f92672",
                tag = "#f4bf75",
            },
            other = {
                ["attribute-name"] = "#f4bf75",
            },
        },

        keyword = {
            default = "#ae81ff",
            control = {
                default = "#ae81ff",
                import = "#66d9ef",
                flow = "#f4bf75",
            },
            operator = "#ae81ff",
            declaration = "#ae81ff",
        },

        storage = {
            type = "#ae81ff",
            modifier = "#f4bf75",
        },

        variable = {
            default = "#f8f8f2",
            parameter = "#f8f8f2",
            other = {
                property = "#f8f8f2",
            },
        },

        punctuation = {
            separator = "#cc6633",
            section = "#cc6633",
        },

        markup = {
            default = "#f8f8f2",
            heading = "#66d9ef",
            raw = "#fd971f",
            link = "#fd971f",
            list = "#f4bf75",
            inserted = "#a6e22e",
            deleted = "#f92672",
        },

        meta = {
            preprocessor = "#f4bf75",
        },
    },
}
