-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#000000",
    base01 = "#0e0e0e",
    base02 = "#181818",
    base03 = "#333333",
    base04 = "#707070",
    base05 = "#cccccc",
    base06 = "#d6d6d6",
    base07 = "#ffffff",
    base08 = "#999999",
    base09 = "#bbbbbb",
    base0A = "#dddddd",
    base0B = "#bbbbbb",
    base0C = "#cccccc",
    base0D = "#888888",
    base0E = "#aaaaaa",
    base0F = "#7a7a7a",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#000000",
            bright = "#0e0e0e",
        },
        gray = {
            dim = "#181818",
            normal = "#333333",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#707070",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#d6d6d6",
            normal = "#cccccc",
            bright = "#ffffff",
        },
        red = { normal = "#999999", bright = "#999999" },
        orange = { normal = "#bbbbbb", bright = "#bbbbbb" },
        yellow = { normal = "#dddddd", bright = "#dddddd" },
        green = { normal = "#bbbbbb", bright = "#bbbbbb" },
        cyan = { normal = "#cccccc", bright = "#cccccc" },
        blue = { normal = "#888888", bright = "#888888" },
        magenta = { normal = "#aaaaaa", bright = "#aaaaaa" },
        brown = { normal = "#7a7a7a" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#000000" },
            foreground = { normal = "#cccccc" },
        },
        cursor = {
            background = { normal = "#cccccc" },
            foreground = { normal = "#000000" },
        },
        gutter = { foreground = "#181818" },
        border = { normal = "#333333" },
        chrome = {
            background = {
                normal = "#181818",
                dark = "#0e0e0e",
            },
            foreground = {
                normal = "#cccccc",
                dark = "#707070",
            },
        },
        selection = { background = "#0e0e0e" },
        highlight = {
            line = { background = "#0e0e0e" },
            text = { background = "#181818" },
            search = {
                background = "#0e0e0e",
                foreground = "#dddddd",
            },
        },
        status = {
            error = "#999999",
            warning = "#bbbbbb",
            info = "#dddddd",
            success = "#bbbbbb",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#333333",

        string = {
            default = "#bbbbbb",
            regexp = "#bbbbbb",
            other = "#bbbbbb",
        },

        constant = {
            default = "#bbbbbb",
            character = {
                default = "#999999",
                escape = "#cccccc",
            },
            language = "#bbbbbb",
            numeric = {
                default = "#bbbbbb",
                float = "#bbbbbb",
            },
        },

        entity = {
            name = {
                class = "#dddddd",
                type = "#dddddd",
                ["function"] = {
                    default = "#888888",
                    constructor = "#888888",
                },
                label = "#dddddd",
                namespace = "#999999",
                tag = "#dddddd",
            },
            other = {
                ["attribute-name"] = "#dddddd",
            },
        },

        keyword = {
            default = "#aaaaaa",
            control = {
                default = "#aaaaaa",
                import = "#888888",
                flow = "#dddddd",
            },
            operator = "#aaaaaa",
            declaration = "#aaaaaa",
        },

        storage = {
            type = "#aaaaaa",
            modifier = "#dddddd",
        },

        variable = {
            default = "#cccccc",
            parameter = "#cccccc",
            other = {
                property = "#cccccc",
            },
        },

        punctuation = {
            separator = "#7a7a7a",
            section = "#7a7a7a",
        },

        markup = {
            default = "#cccccc",
            heading = "#888888",
            raw = "#bbbbbb",
            link = "#bbbbbb",
            list = "#dddddd",
            inserted = "#bbbbbb",
            deleted = "#999999",
        },

        meta = {
            preprocessor = "#dddddd",
        },
    },
}
