-- Auto-generated by tinted-builder-rust from a base24 scheme.
-- Translates base24 slots into tinted8-shaped keys. Mirrors base16.lua.mustache
-- exactly, plus brights from base12-17 and DiagnosticOk = bright_green.
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base24 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#1b1d1f",
    base01 = "#56595c",
    base02 = "#45484b",
    base03 = "#656767",
    base04 = "#868683",
    base05 = "#a7a59f",
    base06 = "#c8c5bc",
    base07 = "#c8c5bd",
    base08 = "#c94c22",
    base09 = "#b4881d",
    base0A = "#2075c7",
    base0B = "#85981c",
    base0C = "#32a198",
    base0D = "#2e8bce",
    base0E = "#d13a82",
    base0F = "#642611",
    base10 = "#2e3032",
    base11 = "#171819",
    base12 = "#bd3612",
    base13 = "#a57704",
    base14 = "#728903",
    base15 = "#259185",
    base16 = "#2075c7",
    base17 = "#c61b6e",

    palette = {
        black = {
            normal = "#1b1d1f",
            bright = "#56595c",
        },
        gray = {
            dim = "#45484b",
            normal = "#656767",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#868683",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#c8c5bc",
            normal = "#a7a59f",
            bright = "#c8c5bd",
        },
        red     = { normal = "#c94c22", bright = "#bd3612" },
        -- base24 has no bright_orange slot; orange.bright falls back to .normal.
        orange  = { normal = "#b4881d", bright = "#b4881d" },
        yellow  = { normal = "#2075c7", bright = "#a57704" },
        green   = { normal = "#85981c", bright = "#728903" },
        cyan    = { normal = "#32a198", bright = "#259185" },
        blue    = { normal = "#2e8bce", bright = "#2075c7" },
        magenta = { normal = "#d13a82", bright = "#c61b6e" },
        brown   = { normal = "#642611" },
    },

    ui = {
        global = {
            background = { normal = "#1b1d1f" },
            foreground = { normal = "#a7a59f" },
        },
        cursor = {
            background = { normal = "#a7a59f" },
            foreground = { normal = "#1b1d1f" },
        },
        gutter = { foreground = "#45484b" },
        border = { normal = "#656767" },
        chrome = {
            background = {
                normal = "#45484b",
                dark = "#56595c",
            },
            foreground = {
                normal = "#a7a59f",
                dark = "#868683",
            },
        },
        selection = { background = "#56595c" },
        highlight = {
            line = { background = "#56595c" },
            text = { background = "#45484b" },
            search = {
                background = "#56595c",
                foreground = "#2075c7",
            },
        },
        status = {
            error = "#c94c22",
            warning = "#b4881d",
            info = "#2075c7",
            -- DiagnosticOk uses bright_green (base14) in current code; preserve.
            success = "#728903",
        },
    },

    syntax = {
        comment = "#656767",

        string = {
            default = "#85981c",
            regexp = "#85981c",
            other = "#85981c",
        },

        constant = {
            default = "#b4881d",
            character = {
                default = "#c94c22",
                escape = "#32a198",
            },
            language = "#b4881d",
            numeric = {
                default = "#b4881d",
                float = "#b4881d",
            },
        },

        entity = {
            name = {
                class = "#2075c7",
                type = "#2075c7",
                ["function"] = {
                    default = "#2e8bce",
                    constructor = "#2e8bce",
                },
                label = "#2075c7",
                namespace = "#c94c22",
                tag = "#2075c7",
            },
            other = {
                ["attribute-name"] = "#2075c7",
            },
        },

        keyword = {
            default = "#d13a82",
            control = {
                default = "#d13a82",
                import = "#2e8bce",
                flow = "#2075c7",
            },
            operator = "#d13a82",
            declaration = "#d13a82",
        },

        storage = {
            type = "#d13a82",
            modifier = "#2075c7",
        },

        variable = {
            default = "#a7a59f",
            parameter = "#a7a59f",
            other = {
                property = "#a7a59f",
            },
        },

        punctuation = {
            separator = "#642611",
            section = "#642611",
        },

        markup = {
            default = "#a7a59f",
            heading = "#2e8bce",
            raw = "#b4881d",
            link = "#b4881d",
            list = "#2075c7",
            inserted = "#85981c",
            deleted = "#c94c22",
        },

        meta = {
            preprocessor = "#2075c7",
        },
    },
}
