-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#1d1f21",
    base01 = "#282a2e",
    base02 = "#373b41",
    base03 = "#969896",
    base04 = "#b4b7b4",
    base05 = "#c5c8c6",
    base06 = "#e0e0e0",
    base07 = "#ffffff",
    base08 = "#cc342b",
    base09 = "#f96a38",
    base0A = "#fba922",
    base0B = "#198844",
    base0C = "#3971ed",
    base0D = "#3971ed",
    base0E = "#a36ac7",
    base0F = "#3971ed",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#1d1f21",
            bright = "#282a2e",
        },
        gray = {
            dim = "#373b41",
            normal = "#969896",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#b4b7b4",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#e0e0e0",
            normal = "#c5c8c6",
            bright = "#ffffff",
        },
        red     = { normal = "#cc342b", bright = "#cc342b" },
        orange  = { normal = "#f96a38", bright = "#f96a38" },
        yellow  = { normal = "#fba922", bright = "#fba922" },
        green   = { normal = "#198844", bright = "#198844" },
        cyan    = { normal = "#3971ed", bright = "#3971ed" },
        blue    = { normal = "#3971ed", bright = "#3971ed" },
        magenta = { normal = "#a36ac7", bright = "#a36ac7" },
        brown   = { normal = "#3971ed" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#1d1f21" },
            foreground = { normal = "#c5c8c6" },
        },
        cursor = {
            background = { normal = "#c5c8c6" },
            foreground = { normal = "#1d1f21" },
        },
        gutter = { foreground = "#373b41" },
        border = { normal = "#969896" },
        chrome = {
            background = {
                normal = "#373b41",
                dark = "#282a2e",
            },
            foreground = {
                normal = "#c5c8c6",
                dark = "#b4b7b4",
            },
        },
        selection = { background = "#282a2e" },
        highlight = {
            line = { background = "#282a2e" },
            text = { background = "#373b41" },
            search = {
                background = "#282a2e",
                foreground = "#fba922",
            },
        },
        status = {
            error = "#cc342b",
            warning = "#f96a38",
            info = "#fba922",
            success = "#198844",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#969896",

        string = {
            default = "#198844",
            regexp = "#198844",
            other = "#198844",
        },

        constant = {
            default = "#f96a38",
            character = {
                default = "#cc342b",
                escape = "#3971ed",
            },
            language = "#f96a38",
            numeric = {
                default = "#f96a38",
                float = "#f96a38",
            },
        },

        entity = {
            name = {
                class = "#fba922",
                type = "#fba922",
                ["function"] = {
                    default = "#3971ed",
                    constructor = "#3971ed",
                },
                label = "#fba922",
                namespace = "#cc342b",
                tag = "#fba922",
            },
            other = {
                ["attribute-name"] = "#fba922",
            },
        },

        keyword = {
            default = "#a36ac7",
            control = {
                default = "#a36ac7",
                import = "#3971ed",
                flow = "#fba922",
            },
            operator = "#a36ac7",
            declaration = "#a36ac7",
        },

        storage = {
            type = "#a36ac7",
            modifier = "#fba922",
        },

        variable = {
            default = "#c5c8c6",
            parameter = "#c5c8c6",
            other = {
                property = "#c5c8c6",
            },
        },

        punctuation = {
            separator = "#3971ed",
            section = "#3971ed",
        },

        markup = {
            default = "#c5c8c6",
            heading = "#3971ed",
            raw = "#f96a38",
            link = "#f96a38",
            list = "#fba922",
            inserted = "#198844",
            deleted = "#cc342b",
        },

        meta = {
            preprocessor = "#fba922",
        },
    },
}
