-- Auto-generated by tinted-builder-rust from a base24 scheme.
-- Translates base24 slots into tinted8-shaped keys. Mirrors base16.lua.mustache
-- exactly, plus brights from base12-17 and DiagnosticOk = bright_green.
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base24 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#0e0c15",
    base01 = "#08002e",
    base02 = "#331e4d",
    base03 = "#634e67",
    base04 = "#937f82",
    base05 = "#c3af9d",
    base06 = "#f3e0b8",
    base07 = "#fff5db",
    base08 = "#64002c",
    base09 = "#cd751c",
    base0A = "#40a4cf",
    base0B = "#5d731a",
    base0C = "#42a38c",
    base0D = "#1d6da1",
    base0E = "#b7077e",
    base0F = "#320016",
    base10 = "#221433",
    base11 = "#110a19",
    base12 = "#d02063",
    base13 = "#fac357",
    base14 = "#b4ce59",
    base15 = "#62caa8",
    base16 = "#40a4cf",
    base17 = "#f12aae",

    palette = {
        black = {
            normal = "#0e0c15",
            bright = "#08002e",
        },
        gray = {
            dim = "#331e4d",
            normal = "#634e67",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#937f82",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#f3e0b8",
            normal = "#c3af9d",
            bright = "#fff5db",
        },
        red = { normal = "#64002c", bright = "#d02063" },
        -- base24 has no bright_orange slot; orange.bright falls back to .normal.
        orange = { normal = "#cd751c", bright = "#cd751c" },
        yellow = { normal = "#40a4cf", bright = "#fac357" },
        green = { normal = "#5d731a", bright = "#b4ce59" },
        cyan = { normal = "#42a38c", bright = "#62caa8" },
        blue = { normal = "#1d6da1", bright = "#40a4cf" },
        magenta = { normal = "#b7077e", bright = "#f12aae" },
        brown = { normal = "#320016" },
    },

    ui = {
        global = {
            background = { normal = "#0e0c15" },
            foreground = { normal = "#c3af9d" },
        },
        cursor = {
            background = { normal = "#c3af9d" },
            foreground = { normal = "#0e0c15" },
        },
        gutter = { foreground = "#331e4d" },
        border = { normal = "#634e67" },
        chrome = {
            background = {
                normal = "#331e4d",
                dark = "#08002e",
            },
            foreground = {
                normal = "#c3af9d",
                dark = "#937f82",
            },
        },
        selection = { background = "#08002e" },
        highlight = {
            line = { background = "#08002e" },
            text = { background = "#331e4d" },
            search = {
                background = "#08002e",
                foreground = "#40a4cf",
            },
        },
        status = {
            error = "#64002c",
            warning = "#cd751c",
            info = "#40a4cf",
            -- DiagnosticOk uses bright_green (base14) in current code; preserve.
            success = "#b4ce59",
        },
    },

    syntax = {
        comment = "#634e67",

        string = {
            default = "#5d731a",
            regexp = "#5d731a",
            other = "#5d731a",
        },

        constant = {
            default = "#cd751c",
            character = {
                default = "#64002c",
                escape = "#42a38c",
            },
            language = "#cd751c",
            numeric = {
                default = "#cd751c",
                float = "#cd751c",
            },
        },

        entity = {
            name = {
                class = "#40a4cf",
                type = "#40a4cf",
                ["function"] = {
                    default = "#1d6da1",
                    constructor = "#1d6da1",
                },
                label = "#40a4cf",
                namespace = "#64002c",
                tag = "#40a4cf",
            },
            other = {
                ["attribute-name"] = "#40a4cf",
            },
        },

        keyword = {
            default = "#b7077e",
            control = {
                default = "#b7077e",
                import = "#1d6da1",
                flow = "#40a4cf",
            },
            operator = "#b7077e",
            declaration = "#b7077e",
        },

        storage = {
            type = "#b7077e",
            modifier = "#40a4cf",
        },

        variable = {
            default = "#c3af9d",
            parameter = "#c3af9d",
            other = {
                property = "#c3af9d",
            },
        },

        punctuation = {
            separator = "#320016",
            section = "#320016",
        },

        markup = {
            default = "#c3af9d",
            heading = "#1d6da1",
            raw = "#cd751c",
            link = "#cd751c",
            list = "#40a4cf",
            inserted = "#5d731a",
            deleted = "#64002c",
        },

        meta = {
            preprocessor = "#40a4cf",
        },
    },
}
