-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#212337",
    base01 = "#403c64",
    base02 = "#596399",
    base03 = "#748cd6",
    base04 = "#a1abe0",
    base05 = "#a3ace1",
    base06 = "#b4a4f4",
    base07 = "#ef43fa",
    base08 = "#ff5370",
    base09 = "#f67f81",
    base0A = "#ffc777",
    base0B = "#2df4c0",
    base0C = "#04d1f9",
    base0D = "#40ffff",
    base0E = "#b994f1",
    base0F = "#ecb2f0",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#212337",
            bright = "#403c64",
        },
        gray = {
            dim = "#596399",
            normal = "#748cd6",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#a1abe0",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#b4a4f4",
            normal = "#a3ace1",
            bright = "#ef43fa",
        },
        red     = { normal = "#ff5370", bright = "#ff5370" },
        orange  = { normal = "#f67f81", bright = "#f67f81" },
        yellow  = { normal = "#ffc777", bright = "#ffc777" },
        green   = { normal = "#2df4c0", bright = "#2df4c0" },
        cyan    = { normal = "#04d1f9", bright = "#04d1f9" },
        blue    = { normal = "#40ffff", bright = "#40ffff" },
        magenta = { normal = "#b994f1", bright = "#b994f1" },
        brown   = { normal = "#ecb2f0" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#212337" },
            foreground = { normal = "#a3ace1" },
        },
        cursor = {
            background = { normal = "#a3ace1" },
            foreground = { normal = "#212337" },
        },
        gutter = { foreground = "#596399" },
        border = { normal = "#748cd6" },
        chrome = {
            background = {
                normal = "#596399",
                dark = "#403c64",
            },
            foreground = {
                normal = "#a3ace1",
                dark = "#a1abe0",
            },
        },
        selection = { background = "#403c64" },
        highlight = {
            line = { background = "#403c64" },
            text = { background = "#596399" },
            search = {
                background = "#403c64",
                foreground = "#ffc777",
            },
        },
        status = {
            error = "#ff5370",
            warning = "#f67f81",
            info = "#ffc777",
            success = "#2df4c0",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#748cd6",

        string = {
            default = "#2df4c0",
            regexp = "#2df4c0",
            other = "#2df4c0",
        },

        constant = {
            default = "#f67f81",
            character = {
                default = "#ff5370",
                escape = "#04d1f9",
            },
            language = "#f67f81",
            numeric = {
                default = "#f67f81",
                float = "#f67f81",
            },
        },

        entity = {
            name = {
                class = "#ffc777",
                type = "#ffc777",
                ["function"] = {
                    default = "#40ffff",
                    constructor = "#40ffff",
                },
                label = "#ffc777",
                namespace = "#ff5370",
                tag = "#ffc777",
            },
            other = {
                ["attribute-name"] = "#ffc777",
            },
        },

        keyword = {
            default = "#b994f1",
            control = {
                default = "#b994f1",
                import = "#40ffff",
                flow = "#ffc777",
            },
            operator = "#b994f1",
            declaration = "#b994f1",
        },

        storage = {
            type = "#b994f1",
            modifier = "#ffc777",
        },

        variable = {
            default = "#a3ace1",
            parameter = "#a3ace1",
            other = {
                property = "#a3ace1",
            },
        },

        punctuation = {
            separator = "#ecb2f0",
            section = "#ecb2f0",
        },

        markup = {
            default = "#a3ace1",
            heading = "#40ffff",
            raw = "#f67f81",
            link = "#f67f81",
            list = "#ffc777",
            inserted = "#2df4c0",
            deleted = "#ff5370",
        },

        meta = {
            preprocessor = "#ffc777",
        },
    },
}
