-- Auto-generated by tinted-builder-rust from a base24 scheme.
-- Translates base24 slots into tinted8-shaped keys. Mirrors base16.lua.mustache
-- exactly, plus brights from base12-17 and DiagnosticOk = bright_green.
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base24 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#323232",
    base01 = "#323232",
    base02 = "#535353",
    base03 = "#797979",
    base04 = "#a0a09f",
    base05 = "#c7c7c5",
    base06 = "#eeeeec",
    base07 = "#ffffff",
    base08 = "#d25252",
    base09 = "#ffc66d",
    base0A = "#5eb7f7",
    base0B = "#7fe173",
    base0C = "#bed6ff",
    base0D = "#4098ff",
    base0E = "#f57fff",
    base0F = "#692929",
    base10 = "#373737",
    base11 = "#1b1b1b",
    base12 = "#f07070",
    base13 = "#ffe48b",
    base14 = "#9dff90",
    base15 = "#dcf4ff",
    base16 = "#5eb7f7",
    base17 = "#ff9dff",

    palette = {
        black = {
            normal = "#323232",
            bright = "#323232",
        },
        gray = {
            dim = "#535353",
            normal = "#797979",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#a0a09f",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#eeeeec",
            normal = "#c7c7c5",
            bright = "#ffffff",
        },
        red     = { normal = "#d25252", bright = "#f07070" },
        -- base24 has no bright_orange slot; orange.bright falls back to .normal.
        orange  = { normal = "#ffc66d", bright = "#ffc66d" },
        yellow  = { normal = "#5eb7f7", bright = "#ffe48b" },
        green   = { normal = "#7fe173", bright = "#9dff90" },
        cyan    = { normal = "#bed6ff", bright = "#dcf4ff" },
        blue    = { normal = "#4098ff", bright = "#5eb7f7" },
        magenta = { normal = "#f57fff", bright = "#ff9dff" },
        brown   = { normal = "#692929" },
    },

    ui = {
        global = {
            background = { normal = "#323232" },
            foreground = { normal = "#c7c7c5" },
        },
        cursor = {
            background = { normal = "#c7c7c5" },
            foreground = { normal = "#323232" },
        },
        gutter = { foreground = "#535353" },
        border = { normal = "#797979" },
        chrome = {
            background = {
                normal = "#535353",
                dark = "#323232",
            },
            foreground = {
                normal = "#c7c7c5",
                dark = "#a0a09f",
            },
        },
        selection = { background = "#323232" },
        highlight = {
            line = { background = "#323232" },
            text = { background = "#535353" },
            search = {
                background = "#323232",
                foreground = "#5eb7f7",
            },
        },
        status = {
            error = "#d25252",
            warning = "#ffc66d",
            info = "#5eb7f7",
            -- DiagnosticOk uses bright_green (base14) in current code; preserve.
            success = "#9dff90",
        },
    },

    syntax = {
        comment = "#797979",

        string = {
            default = "#7fe173",
            regexp = "#7fe173",
            other = "#7fe173",
        },

        constant = {
            default = "#ffc66d",
            character = {
                default = "#d25252",
                escape = "#bed6ff",
            },
            language = "#ffc66d",
            numeric = {
                default = "#ffc66d",
                float = "#ffc66d",
            },
        },

        entity = {
            name = {
                class = "#5eb7f7",
                type = "#5eb7f7",
                ["function"] = {
                    default = "#4098ff",
                    constructor = "#4098ff",
                },
                label = "#5eb7f7",
                namespace = "#d25252",
                tag = "#5eb7f7",
            },
            other = {
                ["attribute-name"] = "#5eb7f7",
            },
        },

        keyword = {
            default = "#f57fff",
            control = {
                default = "#f57fff",
                import = "#4098ff",
                flow = "#5eb7f7",
            },
            operator = "#f57fff",
            declaration = "#f57fff",
        },

        storage = {
            type = "#f57fff",
            modifier = "#5eb7f7",
        },

        variable = {
            default = "#c7c7c5",
            parameter = "#c7c7c5",
            other = {
                property = "#c7c7c5",
            },
        },

        punctuation = {
            separator = "#692929",
            section = "#692929",
        },

        markup = {
            default = "#c7c7c5",
            heading = "#4098ff",
            raw = "#ffc66d",
            link = "#ffc66d",
            list = "#5eb7f7",
            inserted = "#7fe173",
            deleted = "#d25252",
        },

        meta = {
            preprocessor = "#5eb7f7",
        },
    },
}
