-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "light",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#f2f4f8",
    base01 = "#dde1e6",
    base02 = "#bec6cf",
    base03 = "#a1acba",
    base04 = "#68788d",
    base05 = "#525f70",
    base06 = "#3d4652",
    base07 = "#272d35",
    base08 = "#ff7eb6",
    base09 = "#ee5396",
    base0A = "#ff6f00",
    base0B = "#42be65",
    base0C = "#673ab7",
    base0D = "#0f62fe",
    base0E = "#be95ff",
    base0F = "#803800",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#f2f4f8",
            bright = "#dde1e6",
        },
        gray = {
            dim = "#bec6cf",
            normal = "#a1acba",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#68788d",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#3d4652",
            normal = "#525f70",
            bright = "#272d35",
        },
        red     = { normal = "#ff7eb6", bright = "#ff7eb6" },
        orange  = { normal = "#ee5396", bright = "#ee5396" },
        yellow  = { normal = "#ff6f00", bright = "#ff6f00" },
        green   = { normal = "#42be65", bright = "#42be65" },
        cyan    = { normal = "#673ab7", bright = "#673ab7" },
        blue    = { normal = "#0f62fe", bright = "#0f62fe" },
        magenta = { normal = "#be95ff", bright = "#be95ff" },
        brown   = { normal = "#803800" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#f2f4f8" },
            foreground = { normal = "#525f70" },
        },
        cursor = {
            background = { normal = "#525f70" },
            foreground = { normal = "#f2f4f8" },
        },
        gutter = { foreground = "#bec6cf" },
        border = { normal = "#a1acba" },
        chrome = {
            background = {
                normal = "#bec6cf",
                dark = "#dde1e6",
            },
            foreground = {
                normal = "#525f70",
                dark = "#68788d",
            },
        },
        selection = { background = "#dde1e6" },
        highlight = {
            line = { background = "#dde1e6" },
            text = { background = "#bec6cf" },
            search = {
                background = "#dde1e6",
                foreground = "#ff6f00",
            },
        },
        status = {
            error = "#ff7eb6",
            warning = "#ee5396",
            info = "#ff6f00",
            success = "#42be65",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#a1acba",

        string = {
            default = "#42be65",
            regexp = "#42be65",
            other = "#42be65",
        },

        constant = {
            default = "#ee5396",
            character = {
                default = "#ff7eb6",
                escape = "#673ab7",
            },
            language = "#ee5396",
            numeric = {
                default = "#ee5396",
                float = "#ee5396",
            },
        },

        entity = {
            name = {
                class = "#ff6f00",
                type = "#ff6f00",
                ["function"] = {
                    default = "#0f62fe",
                    constructor = "#0f62fe",
                },
                label = "#ff6f00",
                namespace = "#ff7eb6",
                tag = "#ff6f00",
            },
            other = {
                ["attribute-name"] = "#ff6f00",
            },
        },

        keyword = {
            default = "#be95ff",
            control = {
                default = "#be95ff",
                import = "#0f62fe",
                flow = "#ff6f00",
            },
            operator = "#be95ff",
            declaration = "#be95ff",
        },

        storage = {
            type = "#be95ff",
            modifier = "#ff6f00",
        },

        variable = {
            default = "#525f70",
            parameter = "#525f70",
            other = {
                property = "#525f70",
            },
        },

        punctuation = {
            separator = "#803800",
            section = "#803800",
        },

        markup = {
            default = "#525f70",
            heading = "#0f62fe",
            raw = "#ee5396",
            link = "#ee5396",
            list = "#ff6f00",
            inserted = "#42be65",
            deleted = "#ff7eb6",
        },

        meta = {
            preprocessor = "#ff6f00",
        },
    },
}
