-- Auto-generated by tinted-builder-rust from a base24 scheme.
-- Translates base24 slots into tinted8-shaped keys. Mirrors base16.lua.mustache
-- exactly, plus brights from base12-17 and DiagnosticOk = bright_green.
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base24 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#22272e",
    base01 = "#2d333b",
    base02 = "#545d68",
    base03 = "#636e7b",
    base04 = "#768390",
    base05 = "#adbac7",
    base06 = "#cdd9e5",
    base07 = "#ffffff",
    base08 = "#f69d50",
    base09 = "#6cb6ff",
    base0A = "#ae7c14",
    base0B = "#96d0ff",
    base0C = "#8ddb8c",
    base0D = "#dcbdfb",
    base0E = "#f47067",
    base0F = "#ff938a",
    base10 = "#1c2128",
    base11 = "#000000",
    base12 = "#f47067",
    base13 = "#c69026",
    base14 = "#57ab5a",
    base15 = "#33b3ae",
    base16 = "#539bf5",
    base17 = "#b083f0",

    palette = {
        black = {
            normal = "#22272e",
            bright = "#2d333b",
        },
        gray = {
            dim = "#545d68",
            normal = "#636e7b",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#768390",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#cdd9e5",
            normal = "#adbac7",
            bright = "#ffffff",
        },
        red     = { normal = "#f69d50", bright = "#f47067" },
        -- base24 has no bright_orange slot; orange.bright falls back to .normal.
        orange  = { normal = "#6cb6ff", bright = "#6cb6ff" },
        yellow  = { normal = "#ae7c14", bright = "#c69026" },
        green   = { normal = "#96d0ff", bright = "#57ab5a" },
        cyan    = { normal = "#8ddb8c", bright = "#33b3ae" },
        blue    = { normal = "#dcbdfb", bright = "#539bf5" },
        magenta = { normal = "#f47067", bright = "#b083f0" },
        brown   = { normal = "#ff938a" },
    },

    ui = {
        global = {
            background = { normal = "#22272e" },
            foreground = { normal = "#adbac7" },
        },
        cursor = {
            background = { normal = "#adbac7" },
            foreground = { normal = "#22272e" },
        },
        gutter = { foreground = "#545d68" },
        border = { normal = "#636e7b" },
        chrome = {
            background = {
                normal = "#545d68",
                dark = "#2d333b",
            },
            foreground = {
                normal = "#adbac7",
                dark = "#768390",
            },
        },
        selection = { background = "#2d333b" },
        highlight = {
            line = { background = "#2d333b" },
            text = { background = "#545d68" },
            search = {
                background = "#2d333b",
                foreground = "#ae7c14",
            },
        },
        status = {
            error = "#f69d50",
            warning = "#6cb6ff",
            info = "#ae7c14",
            -- DiagnosticOk uses bright_green (base14) in current code; preserve.
            success = "#57ab5a",
        },
    },

    syntax = {
        comment = "#636e7b",

        string = {
            default = "#96d0ff",
            regexp = "#96d0ff",
            other = "#96d0ff",
        },

        constant = {
            default = "#6cb6ff",
            character = {
                default = "#f69d50",
                escape = "#8ddb8c",
            },
            language = "#6cb6ff",
            numeric = {
                default = "#6cb6ff",
                float = "#6cb6ff",
            },
        },

        entity = {
            name = {
                class = "#ae7c14",
                type = "#ae7c14",
                ["function"] = {
                    default = "#dcbdfb",
                    constructor = "#dcbdfb",
                },
                label = "#ae7c14",
                namespace = "#f69d50",
                tag = "#ae7c14",
            },
            other = {
                ["attribute-name"] = "#ae7c14",
            },
        },

        keyword = {
            default = "#f47067",
            control = {
                default = "#f47067",
                import = "#dcbdfb",
                flow = "#ae7c14",
            },
            operator = "#f47067",
            declaration = "#f47067",
        },

        storage = {
            type = "#f47067",
            modifier = "#ae7c14",
        },

        variable = {
            default = "#adbac7",
            parameter = "#adbac7",
            other = {
                property = "#adbac7",
            },
        },

        punctuation = {
            separator = "#ff938a",
            section = "#ff938a",
        },

        markup = {
            default = "#adbac7",
            heading = "#dcbdfb",
            raw = "#6cb6ff",
            link = "#6cb6ff",
            list = "#ae7c14",
            inserted = "#96d0ff",
            deleted = "#f69d50",
        },

        meta = {
            preprocessor = "#ae7c14",
        },
    },
}
