-- Auto-generated by tinted-builder-rust from a base24 scheme.
-- Translates base24 slots into tinted8-shaped keys. Mirrors base16.lua.mustache
-- exactly, plus brights from base12-17 and DiagnosticOk = bright_green.
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base24 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#151144",
    base01 = "#080808",
    base02 = "#2d2d2d",
    base03 = "#5e5e5e",
    base04 = "#8f8f8f",
    base05 = "#c0c0c0",
    base06 = "#f1f1f1",
    base07 = "#feffff",
    base08 = "#ff8272",
    base09 = "#d2a700",
    base0A = "#c1e3fe",
    base0B = "#00c172",
    base0C = "#6bffdc",
    base0D = "#0071cf",
    base0E = "#ff8ffd",
    base0F = "#7f4139",
    base10 = "#1e1e1e",
    base11 = "#0f0f0f",
    base12 = "#ffc4bd",
    base13 = "#fefdd5",
    base14 = "#d6fcb9",
    base15 = "#e5e6fe",
    base16 = "#c1e3fe",
    base17 = "#ffb1fe",

    palette = {
        black = {
            normal = "#151144",
            bright = "#080808",
        },
        gray = {
            dim = "#2d2d2d",
            normal = "#5e5e5e",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#8f8f8f",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#f1f1f1",
            normal = "#c0c0c0",
            bright = "#feffff",
        },
        red = { normal = "#ff8272", bright = "#ffc4bd" },
        -- base24 has no bright_orange slot; orange.bright falls back to .normal.
        orange = { normal = "#d2a700", bright = "#d2a700" },
        yellow = { normal = "#c1e3fe", bright = "#fefdd5" },
        green = { normal = "#00c172", bright = "#d6fcb9" },
        cyan = { normal = "#6bffdc", bright = "#e5e6fe" },
        blue = { normal = "#0071cf", bright = "#c1e3fe" },
        magenta = { normal = "#ff8ffd", bright = "#ffb1fe" },
        brown = { normal = "#7f4139" },
    },

    ui = {
        global = {
            background = { normal = "#151144" },
            foreground = { normal = "#c0c0c0" },
        },
        cursor = {
            background = { normal = "#c0c0c0" },
            foreground = { normal = "#151144" },
        },
        gutter = { foreground = "#2d2d2d" },
        border = { normal = "#5e5e5e" },
        chrome = {
            background = {
                normal = "#2d2d2d",
                dark = "#080808",
            },
            foreground = {
                normal = "#c0c0c0",
                dark = "#8f8f8f",
            },
        },
        selection = { background = "#080808" },
        highlight = {
            line = { background = "#080808" },
            text = { background = "#2d2d2d" },
            search = {
                background = "#080808",
                foreground = "#c1e3fe",
            },
        },
        status = {
            error = "#ff8272",
            warning = "#d2a700",
            info = "#c1e3fe",
            -- DiagnosticOk uses bright_green (base14) in current code; preserve.
            success = "#d6fcb9",
        },
    },

    syntax = {
        comment = "#5e5e5e",

        string = {
            default = "#00c172",
            regexp = "#00c172",
            other = "#00c172",
        },

        constant = {
            default = "#d2a700",
            character = {
                default = "#ff8272",
                escape = "#6bffdc",
            },
            language = "#d2a700",
            numeric = {
                default = "#d2a700",
                float = "#d2a700",
            },
        },

        entity = {
            name = {
                class = "#c1e3fe",
                type = "#c1e3fe",
                ["function"] = {
                    default = "#0071cf",
                    constructor = "#0071cf",
                },
                label = "#c1e3fe",
                namespace = "#ff8272",
                tag = "#c1e3fe",
            },
            other = {
                ["attribute-name"] = "#c1e3fe",
            },
        },

        keyword = {
            default = "#ff8ffd",
            control = {
                default = "#ff8ffd",
                import = "#0071cf",
                flow = "#c1e3fe",
            },
            operator = "#ff8ffd",
            declaration = "#ff8ffd",
        },

        storage = {
            type = "#ff8ffd",
            modifier = "#c1e3fe",
        },

        variable = {
            default = "#c0c0c0",
            parameter = "#c0c0c0",
            other = {
                property = "#c0c0c0",
            },
        },

        punctuation = {
            separator = "#7f4139",
            section = "#7f4139",
        },

        markup = {
            default = "#c0c0c0",
            heading = "#0071cf",
            raw = "#d2a700",
            link = "#d2a700",
            list = "#c1e3fe",
            inserted = "#00c172",
            deleted = "#ff8272",
        },

        meta = {
            preprocessor = "#c1e3fe",
        },
    },
}
