-- Auto-generated by tinted-builder-rust from a base24 scheme.
-- Translates base24 slots into tinted8-shaped keys. Mirrors base16.lua.mustache
-- exactly, plus brights from base12-17 and DiagnosticOk = bright_green.
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base24 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#1e1e2e",
    base01 = "#181825",
    base02 = "#313244",
    base03 = "#45475a",
    base04 = "#585b70",
    base05 = "#cdd6f4",
    base06 = "#f5e0dc",
    base07 = "#b4befe",
    base08 = "#f38ba8",
    base09 = "#fab387",
    base0A = "#f9e2af",
    base0B = "#a6e3a1",
    base0C = "#94e2d5",
    base0D = "#89b4fa",
    base0E = "#cba6f7",
    base0F = "#f2cdcd",
    base10 = "#181825",
    base11 = "#11111b",
    base12 = "#eba0ac",
    base13 = "#f5e0dc",
    base14 = "#a6e3a1",
    base15 = "#89dceb",
    base16 = "#74c7ec",
    base17 = "#f5c2e7",

    palette = {
        black = {
            normal = "#1e1e2e",
            bright = "#181825",
        },
        gray = {
            dim = "#313244",
            normal = "#45475a",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#585b70",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#f5e0dc",
            normal = "#cdd6f4",
            bright = "#b4befe",
        },
        red = { normal = "#f38ba8", bright = "#eba0ac" },
        -- base24 has no bright_orange slot; orange.bright falls back to .normal.
        orange = { normal = "#fab387", bright = "#fab387" },
        yellow = { normal = "#f9e2af", bright = "#f5e0dc" },
        green = { normal = "#a6e3a1", bright = "#a6e3a1" },
        cyan = { normal = "#94e2d5", bright = "#89dceb" },
        blue = { normal = "#89b4fa", bright = "#74c7ec" },
        magenta = { normal = "#cba6f7", bright = "#f5c2e7" },
        brown = { normal = "#f2cdcd" },
    },

    ui = {
        global = {
            background = { normal = "#1e1e2e" },
            foreground = { normal = "#cdd6f4" },
        },
        cursor = {
            background = { normal = "#cdd6f4" },
            foreground = { normal = "#1e1e2e" },
        },
        gutter = { foreground = "#313244" },
        border = { normal = "#45475a" },
        chrome = {
            background = {
                normal = "#313244",
                dark = "#181825",
            },
            foreground = {
                normal = "#cdd6f4",
                dark = "#585b70",
            },
        },
        selection = { background = "#181825" },
        highlight = {
            line = { background = "#181825" },
            text = { background = "#313244" },
            search = {
                background = "#181825",
                foreground = "#f9e2af",
            },
        },
        status = {
            error = "#f38ba8",
            warning = "#fab387",
            info = "#f9e2af",
            -- DiagnosticOk uses bright_green (base14) in current code; preserve.
            success = "#a6e3a1",
        },
    },

    syntax = {
        comment = "#45475a",

        string = {
            default = "#a6e3a1",
            regexp = "#a6e3a1",
            other = "#a6e3a1",
        },

        constant = {
            default = "#fab387",
            character = {
                default = "#f38ba8",
                escape = "#94e2d5",
            },
            language = "#fab387",
            numeric = {
                default = "#fab387",
                float = "#fab387",
            },
        },

        entity = {
            name = {
                class = "#f9e2af",
                type = "#f9e2af",
                ["function"] = {
                    default = "#89b4fa",
                    constructor = "#89b4fa",
                },
                label = "#f9e2af",
                namespace = "#f38ba8",
                tag = "#f9e2af",
            },
            other = {
                ["attribute-name"] = "#f9e2af",
            },
        },

        keyword = {
            default = "#cba6f7",
            control = {
                default = "#cba6f7",
                import = "#89b4fa",
                flow = "#f9e2af",
            },
            operator = "#cba6f7",
            declaration = "#cba6f7",
        },

        storage = {
            type = "#cba6f7",
            modifier = "#f9e2af",
        },

        variable = {
            default = "#cdd6f4",
            parameter = "#cdd6f4",
            other = {
                property = "#cdd6f4",
            },
        },

        punctuation = {
            separator = "#f2cdcd",
            section = "#f2cdcd",
        },

        markup = {
            default = "#cdd6f4",
            heading = "#89b4fa",
            raw = "#fab387",
            link = "#fab387",
            list = "#f9e2af",
            inserted = "#a6e3a1",
            deleted = "#f38ba8",
        },

        meta = {
            preprocessor = "#f9e2af",
        },
    },
}
