-- Auto-generated by tinted-builder-rust from a base24 scheme.
-- Translates base24 slots into tinted8-shaped keys. Mirrors base16.lua.mustache
-- exactly, plus brights from base12-17 and DiagnosticOk = bright_green.
-- Do not edit by hand.

return {
    variant = "light",

    -- Legacy base24 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#fffbeb",
    base01 = "#ceccc0",
    base02 = "#cfcfde",
    base03 = "#6c664b",
    base04 = "#4c4a3d",
    base05 = "#1f1f1f",
    base06 = "#1f1f1f",
    base07 = "#2c2b31",
    base08 = "#cb3a2a",
    base09 = "#a34d14",
    base0A = "#846e15",
    base0B = "#14710a",
    base0C = "#036a96",
    base0D = "#644ac9",
    base0E = "#a3144d",
    base0F = "#792219",
    base10 = "#fdf8e2",
    base11 = "#f5f0da",
    base12 = "#d74c3d",
    base13 = "#9e841a",
    base14 = "#198d0c",
    base15 = "#047fb4",
    base16 = "#7862d0",
    base17 = "#bf185a",

    palette = {
        black = {
            normal = "#fffbeb",
            bright = "#ceccc0",
        },
        gray = {
            dim = "#cfcfde",
            normal = "#6c664b",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#4c4a3d",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#1f1f1f",
            normal = "#1f1f1f",
            bright = "#2c2b31",
        },
        red = { normal = "#cb3a2a", bright = "#d74c3d" },
        -- base24 has no bright_orange slot; orange.bright falls back to .normal.
        orange = { normal = "#a34d14", bright = "#a34d14" },
        yellow = { normal = "#846e15", bright = "#9e841a" },
        green = { normal = "#14710a", bright = "#198d0c" },
        cyan = { normal = "#036a96", bright = "#047fb4" },
        blue = { normal = "#644ac9", bright = "#7862d0" },
        magenta = { normal = "#a3144d", bright = "#bf185a" },
        brown = { normal = "#792219" },
    },

    ui = {
        global = {
            background = { normal = "#fffbeb" },
            foreground = { normal = "#1f1f1f" },
        },
        cursor = {
            background = { normal = "#1f1f1f" },
            foreground = { normal = "#fffbeb" },
        },
        gutter = { foreground = "#cfcfde" },
        border = { normal = "#6c664b" },
        chrome = {
            background = {
                normal = "#cfcfde",
                dark = "#ceccc0",
            },
            foreground = {
                normal = "#1f1f1f",
                dark = "#4c4a3d",
            },
        },
        selection = { background = "#ceccc0" },
        highlight = {
            line = { background = "#ceccc0" },
            text = { background = "#cfcfde" },
            search = {
                background = "#ceccc0",
                foreground = "#846e15",
            },
        },
        status = {
            error = "#cb3a2a",
            warning = "#a34d14",
            info = "#846e15",
            -- DiagnosticOk uses bright_green (base14) in current code; preserve.
            success = "#198d0c",
        },
    },

    syntax = {
        comment = "#6c664b",

        string = {
            default = "#14710a",
            regexp = "#14710a",
            other = "#14710a",
        },

        constant = {
            default = "#a34d14",
            character = {
                default = "#cb3a2a",
                escape = "#036a96",
            },
            language = "#a34d14",
            numeric = {
                default = "#a34d14",
                float = "#a34d14",
            },
        },

        entity = {
            name = {
                class = "#846e15",
                type = "#846e15",
                ["function"] = {
                    default = "#644ac9",
                    constructor = "#644ac9",
                },
                label = "#846e15",
                namespace = "#cb3a2a",
                tag = "#846e15",
            },
            other = {
                ["attribute-name"] = "#846e15",
            },
        },

        keyword = {
            default = "#a3144d",
            control = {
                default = "#a3144d",
                import = "#644ac9",
                flow = "#846e15",
            },
            operator = "#a3144d",
            declaration = "#a3144d",
        },

        storage = {
            type = "#a3144d",
            modifier = "#846e15",
        },

        variable = {
            default = "#1f1f1f",
            parameter = "#1f1f1f",
            other = {
                property = "#1f1f1f",
            },
        },

        punctuation = {
            separator = "#792219",
            section = "#792219",
        },

        markup = {
            default = "#1f1f1f",
            heading = "#644ac9",
            raw = "#a34d14",
            link = "#a34d14",
            list = "#846e15",
            inserted = "#14710a",
            deleted = "#cb3a2a",
        },

        meta = {
            preprocessor = "#846e15",
        },
    },
}
