-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#000000",
    base01 = "#404040",
    base02 = "#404040",
    base03 = "#808080",
    base04 = "#808080",
    base05 = "#c0c0c0",
    base06 = "#c0c0c0",
    base07 = "#ffffff",
    base08 = "#dd0907",
    base09 = "#ff6403",
    base0A = "#fbf305",
    base0B = "#1fb714",
    base0C = "#02abea",
    base0D = "#0000d3",
    base0E = "#4700a5",
    base0F = "#90713a",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#000000",
            bright = "#404040",
        },
        gray = {
            dim = "#404040",
            normal = "#808080",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#808080",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#c0c0c0",
            normal = "#c0c0c0",
            bright = "#ffffff",
        },
        red     = { normal = "#dd0907", bright = "#dd0907" },
        orange  = { normal = "#ff6403", bright = "#ff6403" },
        yellow  = { normal = "#fbf305", bright = "#fbf305" },
        green   = { normal = "#1fb714", bright = "#1fb714" },
        cyan    = { normal = "#02abea", bright = "#02abea" },
        blue    = { normal = "#0000d3", bright = "#0000d3" },
        magenta = { normal = "#4700a5", bright = "#4700a5" },
        brown   = { normal = "#90713a" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#000000" },
            foreground = { normal = "#c0c0c0" },
        },
        cursor = {
            background = { normal = "#c0c0c0" },
            foreground = { normal = "#000000" },
        },
        gutter = { foreground = "#404040" },
        border = { normal = "#808080" },
        chrome = {
            background = {
                normal = "#404040",
                dark = "#404040",
            },
            foreground = {
                normal = "#c0c0c0",
                dark = "#808080",
            },
        },
        selection = { background = "#404040" },
        highlight = {
            line = { background = "#404040" },
            text = { background = "#404040" },
            search = {
                background = "#404040",
                foreground = "#fbf305",
            },
        },
        status = {
            error = "#dd0907",
            warning = "#ff6403",
            info = "#fbf305",
            success = "#1fb714",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#808080",

        string = {
            default = "#1fb714",
            regexp = "#1fb714",
            other = "#1fb714",
        },

        constant = {
            default = "#ff6403",
            character = {
                default = "#dd0907",
                escape = "#02abea",
            },
            language = "#ff6403",
            numeric = {
                default = "#ff6403",
                float = "#ff6403",
            },
        },

        entity = {
            name = {
                class = "#fbf305",
                type = "#fbf305",
                ["function"] = {
                    default = "#0000d3",
                    constructor = "#0000d3",
                },
                label = "#fbf305",
                namespace = "#dd0907",
                tag = "#fbf305",
            },
            other = {
                ["attribute-name"] = "#fbf305",
            },
        },

        keyword = {
            default = "#4700a5",
            control = {
                default = "#4700a5",
                import = "#0000d3",
                flow = "#fbf305",
            },
            operator = "#4700a5",
            declaration = "#4700a5",
        },

        storage = {
            type = "#4700a5",
            modifier = "#fbf305",
        },

        variable = {
            default = "#c0c0c0",
            parameter = "#c0c0c0",
            other = {
                property = "#c0c0c0",
            },
        },

        punctuation = {
            separator = "#90713a",
            section = "#90713a",
        },

        markup = {
            default = "#c0c0c0",
            heading = "#0000d3",
            raw = "#ff6403",
            link = "#ff6403",
            list = "#fbf305",
            inserted = "#1fb714",
            deleted = "#dd0907",
        },

        meta = {
            preprocessor = "#fbf305",
        },
    },
}
