-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#000000",
    base01 = "#303030",
    base02 = "#505050",
    base03 = "#b0b0b0",
    base04 = "#d0d0d0",
    base05 = "#e0e0e0",
    base06 = "#f5f5f5",
    base07 = "#ffffff",
    base08 = "#fb0120",
    base09 = "#fc6d24",
    base0A = "#fda331",
    base0B = "#a1c659",
    base0C = "#76c7b7",
    base0D = "#6fb3d2",
    base0E = "#d381c3",
    base0F = "#be643c",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#000000",
            bright = "#303030",
        },
        gray = {
            dim = "#505050",
            normal = "#b0b0b0",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#d0d0d0",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#f5f5f5",
            normal = "#e0e0e0",
            bright = "#ffffff",
        },
        red     = { normal = "#fb0120", bright = "#fb0120" },
        orange  = { normal = "#fc6d24", bright = "#fc6d24" },
        yellow  = { normal = "#fda331", bright = "#fda331" },
        green   = { normal = "#a1c659", bright = "#a1c659" },
        cyan    = { normal = "#76c7b7", bright = "#76c7b7" },
        blue    = { normal = "#6fb3d2", bright = "#6fb3d2" },
        magenta = { normal = "#d381c3", bright = "#d381c3" },
        brown   = { normal = "#be643c" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#000000" },
            foreground = { normal = "#e0e0e0" },
        },
        cursor = {
            background = { normal = "#e0e0e0" },
            foreground = { normal = "#000000" },
        },
        gutter = { foreground = "#505050" },
        border = { normal = "#b0b0b0" },
        chrome = {
            background = {
                normal = "#505050",
                dark = "#303030",
            },
            foreground = {
                normal = "#e0e0e0",
                dark = "#d0d0d0",
            },
        },
        selection = { background = "#303030" },
        highlight = {
            line = { background = "#303030" },
            text = { background = "#505050" },
            search = {
                background = "#303030",
                foreground = "#fda331",
            },
        },
        status = {
            error = "#fb0120",
            warning = "#fc6d24",
            info = "#fda331",
            success = "#a1c659",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#b0b0b0",

        string = {
            default = "#a1c659",
            regexp = "#a1c659",
            other = "#a1c659",
        },

        constant = {
            default = "#fc6d24",
            character = {
                default = "#fb0120",
                escape = "#76c7b7",
            },
            language = "#fc6d24",
            numeric = {
                default = "#fc6d24",
                float = "#fc6d24",
            },
        },

        entity = {
            name = {
                class = "#fda331",
                type = "#fda331",
                ["function"] = {
                    default = "#6fb3d2",
                    constructor = "#6fb3d2",
                },
                label = "#fda331",
                namespace = "#fb0120",
                tag = "#fda331",
            },
            other = {
                ["attribute-name"] = "#fda331",
            },
        },

        keyword = {
            default = "#d381c3",
            control = {
                default = "#d381c3",
                import = "#6fb3d2",
                flow = "#fda331",
            },
            operator = "#d381c3",
            declaration = "#d381c3",
        },

        storage = {
            type = "#d381c3",
            modifier = "#fda331",
        },

        variable = {
            default = "#e0e0e0",
            parameter = "#e0e0e0",
            other = {
                property = "#e0e0e0",
            },
        },

        punctuation = {
            separator = "#be643c",
            section = "#be643c",
        },

        markup = {
            default = "#e0e0e0",
            heading = "#6fb3d2",
            raw = "#fc6d24",
            link = "#fc6d24",
            list = "#fda331",
            inserted = "#a1c659",
            deleted = "#fb0120",
        },

        meta = {
            preprocessor = "#fda331",
        },
    },
}
