-- Auto-generated by tinted-builder-rust from a base24 scheme.
-- Translates base24 slots into tinted8-shaped keys. Mirrors base16.lua.mustache
-- exactly, plus brights from base12-17 and DiagnosticOk = bright_green.
-- Do not edit by hand.

return {
    variant = "light",

    -- Legacy base24 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#feffff",
    base01 = "#f1f1f1",
    base02 = "#dcdcdc",
    base03 = "#cccccc",
    base04 = "#757575",
    base05 = "#4f4f4f",
    base06 = "#323232",
    base07 = "#000000",
    base08 = "#e4492b",
    base09 = "#c58e40",
    base0A = "#c5c340",
    base0B = "#50d048",
    base0C = "#4ed1dd",
    base0D = "#3a75ff",
    base0E = "#ec65e7",
    base0F = "#722415",
    base10 = "#6a6a6a",
    base11 = "#353535",
    base12 = "#ff6640",
    base13 = "#f2f055",
    base14 = "#61ee56",
    base15 = "#60f6f8",
    base16 = "#0081ff",
    base17 = "#ff7dfe",

    palette = {
        black = {
            normal = "#feffff",
            bright = "#f1f1f1",
        },
        gray = {
            dim = "#dcdcdc",
            normal = "#cccccc",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#757575",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#323232",
            normal = "#4f4f4f",
            bright = "#000000",
        },
        red = { normal = "#e4492b", bright = "#ff6640" },
        -- base24 has no bright_orange slot; orange.bright falls back to .normal.
        orange = { normal = "#c58e40", bright = "#c58e40" },
        yellow = { normal = "#c5c340", bright = "#f2f055" },
        green = { normal = "#50d048", bright = "#61ee56" },
        cyan = { normal = "#4ed1dd", bright = "#60f6f8" },
        blue = { normal = "#3a75ff", bright = "#0081ff" },
        magenta = { normal = "#ec65e7", bright = "#ff7dfe" },
        brown = { normal = "#722415" },
    },

    ui = {
        global = {
            background = { normal = "#feffff" },
            foreground = { normal = "#4f4f4f" },
        },
        cursor = {
            background = { normal = "#4f4f4f" },
            foreground = { normal = "#feffff" },
        },
        gutter = { foreground = "#dcdcdc" },
        border = { normal = "#cccccc" },
        chrome = {
            background = {
                normal = "#dcdcdc",
                dark = "#f1f1f1",
            },
            foreground = {
                normal = "#4f4f4f",
                dark = "#757575",
            },
        },
        selection = { background = "#f1f1f1" },
        highlight = {
            line = { background = "#f1f1f1" },
            text = { background = "#dcdcdc" },
            search = {
                background = "#f1f1f1",
                foreground = "#c5c340",
            },
        },
        status = {
            error = "#e4492b",
            warning = "#c58e40",
            info = "#c5c340",
            -- DiagnosticOk uses bright_green (base14) in current code; preserve.
            success = "#61ee56",
        },
    },

    syntax = {
        comment = "#cccccc",

        string = {
            default = "#50d048",
            regexp = "#50d048",
            other = "#50d048",
        },

        constant = {
            default = "#c58e40",
            character = {
                default = "#e4492b",
                escape = "#4ed1dd",
            },
            language = "#c58e40",
            numeric = {
                default = "#c58e40",
                float = "#c58e40",
            },
        },

        entity = {
            name = {
                class = "#c5c340",
                type = "#c5c340",
                ["function"] = {
                    default = "#3a75ff",
                    constructor = "#3a75ff",
                },
                label = "#c5c340",
                namespace = "#e4492b",
                tag = "#c5c340",
            },
            other = {
                ["attribute-name"] = "#c5c340",
            },
        },

        keyword = {
            default = "#ec65e7",
            control = {
                default = "#ec65e7",
                import = "#3a75ff",
                flow = "#c5c340",
            },
            operator = "#ec65e7",
            declaration = "#ec65e7",
        },

        storage = {
            type = "#ec65e7",
            modifier = "#c5c340",
        },

        variable = {
            default = "#4f4f4f",
            parameter = "#4f4f4f",
            other = {
                property = "#4f4f4f",
            },
        },

        punctuation = {
            separator = "#722415",
            section = "#722415",
        },

        markup = {
            default = "#4f4f4f",
            heading = "#3a75ff",
            raw = "#c58e40",
            link = "#c58e40",
            list = "#c5c340",
            inserted = "#50d048",
            deleted = "#e4492b",
        },

        meta = {
            preprocessor = "#c5c340",
        },
    },
}
