-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "light",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#eeeeee",
    base01 = "#c4c4c4",
    base02 = "#9e9e9e",
    base03 = "#858585",
    base04 = "#6b6b6b",
    base05 = "#5e5e5e",
    base06 = "#525252",
    base07 = "#444444",
    base08 = "#d70000",
    base09 = "#d75f00",
    base0A = "#d75f00",
    base0B = "#008700",
    base0C = "#0087af",
    base0D = "#005f87",
    base0E = "#8700af",
    base0F = "#af0000",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#eeeeee",
            bright = "#c4c4c4",
        },
        gray = {
            dim = "#9e9e9e",
            normal = "#858585",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#6b6b6b",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#525252",
            normal = "#5e5e5e",
            bright = "#444444",
        },
        red     = { normal = "#d70000", bright = "#d70000" },
        orange  = { normal = "#d75f00", bright = "#d75f00" },
        yellow  = { normal = "#d75f00", bright = "#d75f00" },
        green   = { normal = "#008700", bright = "#008700" },
        cyan    = { normal = "#0087af", bright = "#0087af" },
        blue    = { normal = "#005f87", bright = "#005f87" },
        magenta = { normal = "#8700af", bright = "#8700af" },
        brown   = { normal = "#af0000" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#eeeeee" },
            foreground = { normal = "#5e5e5e" },
        },
        cursor = {
            background = { normal = "#5e5e5e" },
            foreground = { normal = "#eeeeee" },
        },
        gutter = { foreground = "#9e9e9e" },
        border = { normal = "#858585" },
        chrome = {
            background = {
                normal = "#9e9e9e",
                dark = "#c4c4c4",
            },
            foreground = {
                normal = "#5e5e5e",
                dark = "#6b6b6b",
            },
        },
        selection = { background = "#c4c4c4" },
        highlight = {
            line = { background = "#c4c4c4" },
            text = { background = "#9e9e9e" },
            search = {
                background = "#c4c4c4",
                foreground = "#d75f00",
            },
        },
        status = {
            error = "#d70000",
            warning = "#d75f00",
            info = "#d75f00",
            success = "#008700",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#858585",

        string = {
            default = "#008700",
            regexp = "#008700",
            other = "#008700",
        },

        constant = {
            default = "#d75f00",
            character = {
                default = "#d70000",
                escape = "#0087af",
            },
            language = "#d75f00",
            numeric = {
                default = "#d75f00",
                float = "#d75f00",
            },
        },

        entity = {
            name = {
                class = "#d75f00",
                type = "#d75f00",
                ["function"] = {
                    default = "#005f87",
                    constructor = "#005f87",
                },
                label = "#d75f00",
                namespace = "#d70000",
                tag = "#d75f00",
            },
            other = {
                ["attribute-name"] = "#d75f00",
            },
        },

        keyword = {
            default = "#8700af",
            control = {
                default = "#8700af",
                import = "#005f87",
                flow = "#d75f00",
            },
            operator = "#8700af",
            declaration = "#8700af",
        },

        storage = {
            type = "#8700af",
            modifier = "#d75f00",
        },

        variable = {
            default = "#5e5e5e",
            parameter = "#5e5e5e",
            other = {
                property = "#5e5e5e",
            },
        },

        punctuation = {
            separator = "#af0000",
            section = "#af0000",
        },

        markup = {
            default = "#5e5e5e",
            heading = "#005f87",
            raw = "#d75f00",
            link = "#d75f00",
            list = "#d75f00",
            inserted = "#008700",
            deleted = "#d70000",
        },

        meta = {
            preprocessor = "#d75f00",
        },
    },
}
