-- Auto-generated by tinted-builder-rust from a base24 scheme.
-- Translates base24 slots into tinted8-shaped keys. Mirrors base16.lua.mustache
-- exactly, plus brights from base12-17 and DiagnosticOk = bright_green.
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base24 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#1c0b28",
    base01 = "#0a4b61",
    base02 = "#1f1637",
    base03 = "#534a5e",
    base04 = "#877e86",
    base05 = "#bbb2ad",
    base06 = "#f0e7d5",
    base07 = "#0a6b7e",
    base08 = "#99236d",
    base09 = "#e9b8a7",
    base0A = "#38163d",
    base0B = "#5bb0b2",
    base0C = "#7e82cc",
    base0D = "#90a5bc",
    base0E = "#9d53a7",
    base0F = "#4c1136",
    base10 = "#140e24",
    base11 = "#0a0712",
    base12 = "#c77171",
    base13 = "#793188",
    base14 = "#0a6b7e",
    base15 = "#5d5f71",
    base16 = "#38163d",
    base17 = "#bc93b6",

    palette = {
        black = {
            normal = "#1c0b28",
            bright = "#0a4b61",
        },
        gray = {
            dim = "#1f1637",
            normal = "#534a5e",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#877e86",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#f0e7d5",
            normal = "#bbb2ad",
            bright = "#0a6b7e",
        },
        red = { normal = "#99236d", bright = "#c77171" },
        -- base24 has no bright_orange slot; orange.bright falls back to .normal.
        orange = { normal = "#e9b8a7", bright = "#e9b8a7" },
        yellow = { normal = "#38163d", bright = "#793188" },
        green = { normal = "#5bb0b2", bright = "#0a6b7e" },
        cyan = { normal = "#7e82cc", bright = "#5d5f71" },
        blue = { normal = "#90a5bc", bright = "#38163d" },
        magenta = { normal = "#9d53a7", bright = "#bc93b6" },
        brown = { normal = "#4c1136" },
    },

    ui = {
        global = {
            background = { normal = "#1c0b28" },
            foreground = { normal = "#bbb2ad" },
        },
        cursor = {
            background = { normal = "#bbb2ad" },
            foreground = { normal = "#1c0b28" },
        },
        gutter = { foreground = "#1f1637" },
        border = { normal = "#534a5e" },
        chrome = {
            background = {
                normal = "#1f1637",
                dark = "#0a4b61",
            },
            foreground = {
                normal = "#bbb2ad",
                dark = "#877e86",
            },
        },
        selection = { background = "#0a4b61" },
        highlight = {
            line = { background = "#0a4b61" },
            text = { background = "#1f1637" },
            search = {
                background = "#0a4b61",
                foreground = "#38163d",
            },
        },
        status = {
            error = "#99236d",
            warning = "#e9b8a7",
            info = "#38163d",
            -- DiagnosticOk uses bright_green (base14) in current code; preserve.
            success = "#0a6b7e",
        },
    },

    syntax = {
        comment = "#534a5e",

        string = {
            default = "#5bb0b2",
            regexp = "#5bb0b2",
            other = "#5bb0b2",
        },

        constant = {
            default = "#e9b8a7",
            character = {
                default = "#99236d",
                escape = "#7e82cc",
            },
            language = "#e9b8a7",
            numeric = {
                default = "#e9b8a7",
                float = "#e9b8a7",
            },
        },

        entity = {
            name = {
                class = "#38163d",
                type = "#38163d",
                ["function"] = {
                    default = "#90a5bc",
                    constructor = "#90a5bc",
                },
                label = "#38163d",
                namespace = "#99236d",
                tag = "#38163d",
            },
            other = {
                ["attribute-name"] = "#38163d",
            },
        },

        keyword = {
            default = "#9d53a7",
            control = {
                default = "#9d53a7",
                import = "#90a5bc",
                flow = "#38163d",
            },
            operator = "#9d53a7",
            declaration = "#9d53a7",
        },

        storage = {
            type = "#9d53a7",
            modifier = "#38163d",
        },

        variable = {
            default = "#bbb2ad",
            parameter = "#bbb2ad",
            other = {
                property = "#bbb2ad",
            },
        },

        punctuation = {
            separator = "#4c1136",
            section = "#4c1136",
        },

        markup = {
            default = "#bbb2ad",
            heading = "#90a5bc",
            raw = "#e9b8a7",
            link = "#e9b8a7",
            list = "#38163d",
            inserted = "#5bb0b2",
            deleted = "#99236d",
        },

        meta = {
            preprocessor = "#38163d",
        },
    },
}
