-- Auto-generated by tinted-builder-rust from a base24 scheme.
-- Translates base24 slots into tinted8-shaped keys. Mirrors base16.lua.mustache
-- exactly, plus brights from base12-17 and DiagnosticOk = bright_green.
-- Do not edit by hand.

return {
    variant = "light",

    -- Legacy base24 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#f7f9fc",
    base01 = "#eef4fb",
    base02 = "#dde7f1",
    base03 = "#637287",
    base04 = "#566579",
    base05 = "#232b38",
    base06 = "#202b3a",
    base07 = "#141d2a",
    base08 = "#b4233d",
    base09 = "#9a4f00",
    base0A = "#6f6300",
    base0B = "#17795e",
    base0C = "#00727e",
    base0D = "#006fa8",
    base0E = "#a0007d",
    base0F = "#7a4e3c",
    base10 = "#fbfdff",
    base11 = "#ffffff",
    base12 = "#c7354d",
    base13 = "#7b6500",
    base14 = "#247b4e",
    base15 = "#007787",
    base16 = "#0078b5",
    base17 = "#b5149e",

    palette = {
        black = {
            normal = "#f7f9fc",
            bright = "#eef4fb",
        },
        gray = {
            dim = "#dde7f1",
            normal = "#637287",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#566579",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#202b3a",
            normal = "#232b38",
            bright = "#141d2a",
        },
        red = { normal = "#b4233d", bright = "#c7354d" },
        -- base24 has no bright_orange slot; orange.bright falls back to .normal.
        orange = { normal = "#9a4f00", bright = "#9a4f00" },
        yellow = { normal = "#6f6300", bright = "#7b6500" },
        green = { normal = "#17795e", bright = "#247b4e" },
        cyan = { normal = "#00727e", bright = "#007787" },
        blue = { normal = "#006fa8", bright = "#0078b5" },
        magenta = { normal = "#a0007d", bright = "#b5149e" },
        brown = { normal = "#7a4e3c" },
    },

    ui = {
        global = {
            background = { normal = "#f7f9fc" },
            foreground = { normal = "#232b38" },
        },
        cursor = {
            background = { normal = "#232b38" },
            foreground = { normal = "#f7f9fc" },
        },
        gutter = { foreground = "#dde7f1" },
        border = { normal = "#637287" },
        chrome = {
            background = {
                normal = "#dde7f1",
                dark = "#eef4fb",
            },
            foreground = {
                normal = "#232b38",
                dark = "#566579",
            },
        },
        selection = { background = "#eef4fb" },
        highlight = {
            line = { background = "#eef4fb" },
            text = { background = "#dde7f1" },
            search = {
                background = "#eef4fb",
                foreground = "#6f6300",
            },
        },
        status = {
            error = "#b4233d",
            warning = "#9a4f00",
            info = "#6f6300",
            -- DiagnosticOk uses bright_green (base14) in current code; preserve.
            success = "#247b4e",
        },
    },

    syntax = {
        comment = "#637287",

        string = {
            default = "#17795e",
            regexp = "#17795e",
            other = "#17795e",
        },

        constant = {
            default = "#9a4f00",
            character = {
                default = "#b4233d",
                escape = "#00727e",
            },
            language = "#9a4f00",
            numeric = {
                default = "#9a4f00",
                float = "#9a4f00",
            },
        },

        entity = {
            name = {
                class = "#6f6300",
                type = "#6f6300",
                ["function"] = {
                    default = "#006fa8",
                    constructor = "#006fa8",
                },
                label = "#6f6300",
                namespace = "#b4233d",
                tag = "#6f6300",
            },
            other = {
                ["attribute-name"] = "#6f6300",
            },
        },

        keyword = {
            default = "#a0007d",
            control = {
                default = "#a0007d",
                import = "#006fa8",
                flow = "#6f6300",
            },
            operator = "#a0007d",
            declaration = "#a0007d",
        },

        storage = {
            type = "#a0007d",
            modifier = "#6f6300",
        },

        variable = {
            default = "#232b38",
            parameter = "#232b38",
            other = {
                property = "#232b38",
            },
        },

        punctuation = {
            separator = "#7a4e3c",
            section = "#7a4e3c",
        },

        markup = {
            default = "#232b38",
            heading = "#006fa8",
            raw = "#9a4f00",
            link = "#9a4f00",
            list = "#6f6300",
            inserted = "#17795e",
            deleted = "#b4233d",
        },

        meta = {
            preprocessor = "#6f6300",
        },
    },
}
