-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#181818",
    base01 = "#252525",
    base02 = "#3b3b3b",
    base03 = "#777777",
    base04 = "#777777",
    base05 = "#b9b9b9",
    base06 = "#dedede",
    base07 = "#dedede",
    base08 = "#ed4a46",
    base09 = "#e67f43",
    base0A = "#dbb32d",
    base0B = "#70b433",
    base0C = "#3fc5b7",
    base0D = "#368aeb",
    base0E = "#a580e2",
    base0F = "#eb6eb7",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#181818",
            bright = "#252525",
        },
        gray = {
            dim = "#3b3b3b",
            normal = "#777777",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#777777",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#dedede",
            normal = "#b9b9b9",
            bright = "#dedede",
        },
        red = { normal = "#ed4a46", bright = "#ed4a46" },
        orange = { normal = "#e67f43", bright = "#e67f43" },
        yellow = { normal = "#dbb32d", bright = "#dbb32d" },
        green = { normal = "#70b433", bright = "#70b433" },
        cyan = { normal = "#3fc5b7", bright = "#3fc5b7" },
        blue = { normal = "#368aeb", bright = "#368aeb" },
        magenta = { normal = "#a580e2", bright = "#a580e2" },
        brown = { normal = "#eb6eb7" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#181818" },
            foreground = { normal = "#b9b9b9" },
        },
        cursor = {
            background = { normal = "#b9b9b9" },
            foreground = { normal = "#181818" },
        },
        gutter = { foreground = "#3b3b3b" },
        border = { normal = "#777777" },
        chrome = {
            background = {
                normal = "#3b3b3b",
                dark = "#252525",
            },
            foreground = {
                normal = "#b9b9b9",
                dark = "#777777",
            },
        },
        selection = { background = "#252525" },
        highlight = {
            line = { background = "#252525" },
            text = { background = "#3b3b3b" },
            search = {
                background = "#252525",
                foreground = "#dbb32d",
            },
        },
        status = {
            error = "#ed4a46",
            warning = "#e67f43",
            info = "#dbb32d",
            success = "#70b433",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#777777",

        string = {
            default = "#70b433",
            regexp = "#70b433",
            other = "#70b433",
        },

        constant = {
            default = "#e67f43",
            character = {
                default = "#ed4a46",
                escape = "#3fc5b7",
            },
            language = "#e67f43",
            numeric = {
                default = "#e67f43",
                float = "#e67f43",
            },
        },

        entity = {
            name = {
                class = "#dbb32d",
                type = "#dbb32d",
                ["function"] = {
                    default = "#368aeb",
                    constructor = "#368aeb",
                },
                label = "#dbb32d",
                namespace = "#ed4a46",
                tag = "#dbb32d",
            },
            other = {
                ["attribute-name"] = "#dbb32d",
            },
        },

        keyword = {
            default = "#a580e2",
            control = {
                default = "#a580e2",
                import = "#368aeb",
                flow = "#dbb32d",
            },
            operator = "#a580e2",
            declaration = "#a580e2",
        },

        storage = {
            type = "#a580e2",
            modifier = "#dbb32d",
        },

        variable = {
            default = "#b9b9b9",
            parameter = "#b9b9b9",
            other = {
                property = "#b9b9b9",
            },
        },

        punctuation = {
            separator = "#eb6eb7",
            section = "#eb6eb7",
        },

        markup = {
            default = "#b9b9b9",
            heading = "#368aeb",
            raw = "#e67f43",
            link = "#e67f43",
            list = "#dbb32d",
            inserted = "#70b433",
            deleted = "#ed4a46",
        },

        meta = {
            preprocessor = "#dbb32d",
        },
    },
}
