-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#28211c",
    base01 = "#36312e",
    base02 = "#5e5d5c",
    base03 = "#666666",
    base04 = "#797977",
    base05 = "#8a8986",
    base06 = "#9d9b97",
    base07 = "#baae9e",
    base08 = "#cf6a4c",
    base09 = "#cf7d34",
    base0A = "#f9ee98",
    base0B = "#54be0d",
    base0C = "#afc4db",
    base0D = "#5ea6ea",
    base0E = "#9b859d",
    base0F = "#937121",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#28211c",
            bright = "#36312e",
        },
        gray = {
            dim = "#5e5d5c",
            normal = "#666666",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#797977",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#9d9b97",
            normal = "#8a8986",
            bright = "#baae9e",
        },
        red     = { normal = "#cf6a4c", bright = "#cf6a4c" },
        orange  = { normal = "#cf7d34", bright = "#cf7d34" },
        yellow  = { normal = "#f9ee98", bright = "#f9ee98" },
        green   = { normal = "#54be0d", bright = "#54be0d" },
        cyan    = { normal = "#afc4db", bright = "#afc4db" },
        blue    = { normal = "#5ea6ea", bright = "#5ea6ea" },
        magenta = { normal = "#9b859d", bright = "#9b859d" },
        brown   = { normal = "#937121" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#28211c" },
            foreground = { normal = "#8a8986" },
        },
        cursor = {
            background = { normal = "#8a8986" },
            foreground = { normal = "#28211c" },
        },
        gutter = { foreground = "#5e5d5c" },
        border = { normal = "#666666" },
        chrome = {
            background = {
                normal = "#5e5d5c",
                dark = "#36312e",
            },
            foreground = {
                normal = "#8a8986",
                dark = "#797977",
            },
        },
        selection = { background = "#36312e" },
        highlight = {
            line = { background = "#36312e" },
            text = { background = "#5e5d5c" },
            search = {
                background = "#36312e",
                foreground = "#f9ee98",
            },
        },
        status = {
            error = "#cf6a4c",
            warning = "#cf7d34",
            info = "#f9ee98",
            success = "#54be0d",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#666666",

        string = {
            default = "#54be0d",
            regexp = "#54be0d",
            other = "#54be0d",
        },

        constant = {
            default = "#cf7d34",
            character = {
                default = "#cf6a4c",
                escape = "#afc4db",
            },
            language = "#cf7d34",
            numeric = {
                default = "#cf7d34",
                float = "#cf7d34",
            },
        },

        entity = {
            name = {
                class = "#f9ee98",
                type = "#f9ee98",
                ["function"] = {
                    default = "#5ea6ea",
                    constructor = "#5ea6ea",
                },
                label = "#f9ee98",
                namespace = "#cf6a4c",
                tag = "#f9ee98",
            },
            other = {
                ["attribute-name"] = "#f9ee98",
            },
        },

        keyword = {
            default = "#9b859d",
            control = {
                default = "#9b859d",
                import = "#5ea6ea",
                flow = "#f9ee98",
            },
            operator = "#9b859d",
            declaration = "#9b859d",
        },

        storage = {
            type = "#9b859d",
            modifier = "#f9ee98",
        },

        variable = {
            default = "#8a8986",
            parameter = "#8a8986",
            other = {
                property = "#8a8986",
            },
        },

        punctuation = {
            separator = "#937121",
            section = "#937121",
        },

        markup = {
            default = "#8a8986",
            heading = "#5ea6ea",
            raw = "#cf7d34",
            link = "#cf7d34",
            list = "#f9ee98",
            inserted = "#54be0d",
            deleted = "#cf6a4c",
        },

        meta = {
            preprocessor = "#f9ee98",
        },
    },
}
