-- Auto-generated by tinted-builder-rust from a base24 scheme.
-- Translates base24 slots into tinted8-shaped keys. Mirrors base16.lua.mustache
-- exactly, plus brights from base12-17 and DiagnosticOk = bright_green.
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base24 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#21211c",
    base01 = "#3c3b30",
    base02 = "#545444",
    base03 = "#5f5d50",
    base04 = "#6a665c",
    base05 = "#756f68",
    base06 = "#807974",
    base07 = "#fff1e8",
    base08 = "#97280f",
    base09 = "#7f7110",
    base0A = "#78d8d8",
    base0B = "#479942",
    base0C = "#387f58",
    base0D = "#497f7d",
    base0E = "#7e4e2e",
    base0F = "#4b1407",
    base10 = "#38382d",
    base11 = "#1c1c16",
    base12 = "#df502a",
    base13 = "#d69827",
    base14 = "#60e06f",
    base15 = "#58d598",
    base16 = "#78d8d8",
    base17 = "#cd7c53",

    palette = {
        black = {
            normal = "#21211c",
            bright = "#3c3b30",
        },
        gray = {
            dim = "#545444",
            normal = "#5f5d50",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#6a665c",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#807974",
            normal = "#756f68",
            bright = "#fff1e8",
        },
        red = { normal = "#97280f", bright = "#df502a" },
        -- base24 has no bright_orange slot; orange.bright falls back to .normal.
        orange = { normal = "#7f7110", bright = "#7f7110" },
        yellow = { normal = "#78d8d8", bright = "#d69827" },
        green = { normal = "#479942", bright = "#60e06f" },
        cyan = { normal = "#387f58", bright = "#58d598" },
        blue = { normal = "#497f7d", bright = "#78d8d8" },
        magenta = { normal = "#7e4e2e", bright = "#cd7c53" },
        brown = { normal = "#4b1407" },
    },

    ui = {
        global = {
            background = { normal = "#21211c" },
            foreground = { normal = "#756f68" },
        },
        cursor = {
            background = { normal = "#756f68" },
            foreground = { normal = "#21211c" },
        },
        gutter = { foreground = "#545444" },
        border = { normal = "#5f5d50" },
        chrome = {
            background = {
                normal = "#545444",
                dark = "#3c3b30",
            },
            foreground = {
                normal = "#756f68",
                dark = "#6a665c",
            },
        },
        selection = { background = "#3c3b30" },
        highlight = {
            line = { background = "#3c3b30" },
            text = { background = "#545444" },
            search = {
                background = "#3c3b30",
                foreground = "#78d8d8",
            },
        },
        status = {
            error = "#97280f",
            warning = "#7f7110",
            info = "#78d8d8",
            -- DiagnosticOk uses bright_green (base14) in current code; preserve.
            success = "#60e06f",
        },
    },

    syntax = {
        comment = "#5f5d50",

        string = {
            default = "#479942",
            regexp = "#479942",
            other = "#479942",
        },

        constant = {
            default = "#7f7110",
            character = {
                default = "#97280f",
                escape = "#387f58",
            },
            language = "#7f7110",
            numeric = {
                default = "#7f7110",
                float = "#7f7110",
            },
        },

        entity = {
            name = {
                class = "#78d8d8",
                type = "#78d8d8",
                ["function"] = {
                    default = "#497f7d",
                    constructor = "#497f7d",
                },
                label = "#78d8d8",
                namespace = "#97280f",
                tag = "#78d8d8",
            },
            other = {
                ["attribute-name"] = "#78d8d8",
            },
        },

        keyword = {
            default = "#7e4e2e",
            control = {
                default = "#7e4e2e",
                import = "#497f7d",
                flow = "#78d8d8",
            },
            operator = "#7e4e2e",
            declaration = "#7e4e2e",
        },

        storage = {
            type = "#7e4e2e",
            modifier = "#78d8d8",
        },

        variable = {
            default = "#756f68",
            parameter = "#756f68",
            other = {
                property = "#756f68",
            },
        },

        punctuation = {
            separator = "#4b1407",
            section = "#4b1407",
        },

        markup = {
            default = "#756f68",
            heading = "#497f7d",
            raw = "#7f7110",
            link = "#7f7110",
            list = "#78d8d8",
            inserted = "#479942",
            deleted = "#97280f",
        },

        meta = {
            preprocessor = "#78d8d8",
        },
    },
}
