-- Auto-generated by tinted-builder-rust from a base24 scheme.
-- Translates base24 slots into tinted8-shaped keys. Mirrors base16.lua.mustache
-- exactly, plus brights from base12-17 and DiagnosticOk = bright_green.
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base24 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#79241e",
    base01 = "#000000",
    base02 = "#555555",
    base03 = "#6e6e6e",
    base04 = "#888888",
    base05 = "#a1a1a1",
    base06 = "#bbbbbb",
    base07 = "#ffffff",
    base08 = "#ff3f00",
    base09 = "#e7b000",
    base0A = "#0071ae",
    base0B = "#00bb00",
    base0C = "#00bbbb",
    base0D = "#0071ff",
    base0E = "#bb00bb",
    base0F = "#7f1f00",
    base10 = "#383838",
    base11 = "#1c1c1c",
    base12 = "#bb0000",
    base13 = "#e7b000",
    base14 = "#00bb00",
    base15 = "#55ffff",
    base16 = "#0071ae",
    base17 = "#ff55ff",

    palette = {
        black = {
            normal = "#79241e",
            bright = "#000000",
        },
        gray = {
            dim = "#555555",
            normal = "#6e6e6e",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#888888",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#bbbbbb",
            normal = "#a1a1a1",
            bright = "#ffffff",
        },
        red     = { normal = "#ff3f00", bright = "#bb0000" },
        -- base24 has no bright_orange slot; orange.bright falls back to .normal.
        orange  = { normal = "#e7b000", bright = "#e7b000" },
        yellow  = { normal = "#0071ae", bright = "#e7b000" },
        green   = { normal = "#00bb00", bright = "#00bb00" },
        cyan    = { normal = "#00bbbb", bright = "#55ffff" },
        blue    = { normal = "#0071ff", bright = "#0071ae" },
        magenta = { normal = "#bb00bb", bright = "#ff55ff" },
        brown   = { normal = "#7f1f00" },
    },

    ui = {
        global = {
            background = { normal = "#79241e" },
            foreground = { normal = "#a1a1a1" },
        },
        cursor = {
            background = { normal = "#a1a1a1" },
            foreground = { normal = "#79241e" },
        },
        gutter = { foreground = "#555555" },
        border = { normal = "#6e6e6e" },
        chrome = {
            background = {
                normal = "#555555",
                dark = "#000000",
            },
            foreground = {
                normal = "#a1a1a1",
                dark = "#888888",
            },
        },
        selection = { background = "#000000" },
        highlight = {
            line = { background = "#000000" },
            text = { background = "#555555" },
            search = {
                background = "#000000",
                foreground = "#0071ae",
            },
        },
        status = {
            error = "#ff3f00",
            warning = "#e7b000",
            info = "#0071ae",
            -- DiagnosticOk uses bright_green (base14) in current code; preserve.
            success = "#00bb00",
        },
    },

    syntax = {
        comment = "#6e6e6e",

        string = {
            default = "#00bb00",
            regexp = "#00bb00",
            other = "#00bb00",
        },

        constant = {
            default = "#e7b000",
            character = {
                default = "#ff3f00",
                escape = "#00bbbb",
            },
            language = "#e7b000",
            numeric = {
                default = "#e7b000",
                float = "#e7b000",
            },
        },

        entity = {
            name = {
                class = "#0071ae",
                type = "#0071ae",
                ["function"] = {
                    default = "#0071ff",
                    constructor = "#0071ff",
                },
                label = "#0071ae",
                namespace = "#ff3f00",
                tag = "#0071ae",
            },
            other = {
                ["attribute-name"] = "#0071ae",
            },
        },

        keyword = {
            default = "#bb00bb",
            control = {
                default = "#bb00bb",
                import = "#0071ff",
                flow = "#0071ae",
            },
            operator = "#bb00bb",
            declaration = "#bb00bb",
        },

        storage = {
            type = "#bb00bb",
            modifier = "#0071ae",
        },

        variable = {
            default = "#a1a1a1",
            parameter = "#a1a1a1",
            other = {
                property = "#a1a1a1",
            },
        },

        punctuation = {
            separator = "#7f1f00",
            section = "#7f1f00",
        },

        markup = {
            default = "#a1a1a1",
            heading = "#0071ff",
            raw = "#e7b000",
            link = "#e7b000",
            list = "#0071ae",
            inserted = "#00bb00",
            deleted = "#ff3f00",
        },

        meta = {
            preprocessor = "#0071ae",
        },
    },
}
