-- Auto-generated by tinted-builder-rust from a base24 scheme.
-- Translates base24 slots into tinted8-shaped keys. Mirrors base16.lua.mustache
-- exactly, plus brights from base12-17 and DiagnosticOk = bright_green.
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base24 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#131313",
    base01 = "#1f1f1f",
    base02 = "#2a3141",
    base03 = "#343d50",
    base04 = "#d6dae4",
    base05 = "#c1c8d7",
    base06 = "#e3e6ed",
    base07 = "#ffffff",
    base08 = "#f71118",
    base09 = "#ecb90f",
    base0A = "#0f80d5",
    base0B = "#2cc55d",
    base0C = "#0f80d5",
    base0D = "#2a84d2",
    base0E = "#4e59b7",
    base0F = "#7b080c",
    base10 = "#0a0a0a",
    base11 = "#020202",
    base12 = "#de342e",
    base13 = "#f2bd09",
    base14 = "#1dd260",
    base15 = "#289af0",
    base16 = "#509bdc",
    base17 = "#524fb9",

    palette = {
        black = {
            normal = "#131313",
            bright = "#1f1f1f",
        },
        gray = {
            dim = "#2a3141",
            normal = "#343d50",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#d6dae4",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#e3e6ed",
            normal = "#c1c8d7",
            bright = "#ffffff",
        },
        red     = { normal = "#f71118", bright = "#de342e" },
        -- base24 has no bright_orange slot; orange.bright falls back to .normal.
        orange  = { normal = "#ecb90f", bright = "#ecb90f" },
        yellow  = { normal = "#0f80d5", bright = "#f2bd09" },
        green   = { normal = "#2cc55d", bright = "#1dd260" },
        cyan    = { normal = "#0f80d5", bright = "#289af0" },
        blue    = { normal = "#2a84d2", bright = "#509bdc" },
        magenta = { normal = "#4e59b7", bright = "#524fb9" },
        brown   = { normal = "#7b080c" },
    },

    ui = {
        global = {
            background = { normal = "#131313" },
            foreground = { normal = "#c1c8d7" },
        },
        cursor = {
            background = { normal = "#c1c8d7" },
            foreground = { normal = "#131313" },
        },
        gutter = { foreground = "#2a3141" },
        border = { normal = "#343d50" },
        chrome = {
            background = {
                normal = "#2a3141",
                dark = "#1f1f1f",
            },
            foreground = {
                normal = "#c1c8d7",
                dark = "#d6dae4",
            },
        },
        selection = { background = "#1f1f1f" },
        highlight = {
            line = { background = "#1f1f1f" },
            text = { background = "#2a3141" },
            search = {
                background = "#1f1f1f",
                foreground = "#0f80d5",
            },
        },
        status = {
            error = "#f71118",
            warning = "#ecb90f",
            info = "#0f80d5",
            -- DiagnosticOk uses bright_green (base14) in current code; preserve.
            success = "#1dd260",
        },
    },

    syntax = {
        comment = "#343d50",

        string = {
            default = "#2cc55d",
            regexp = "#2cc55d",
            other = "#2cc55d",
        },

        constant = {
            default = "#ecb90f",
            character = {
                default = "#f71118",
                escape = "#0f80d5",
            },
            language = "#ecb90f",
            numeric = {
                default = "#ecb90f",
                float = "#ecb90f",
            },
        },

        entity = {
            name = {
                class = "#0f80d5",
                type = "#0f80d5",
                ["function"] = {
                    default = "#2a84d2",
                    constructor = "#2a84d2",
                },
                label = "#0f80d5",
                namespace = "#f71118",
                tag = "#0f80d5",
            },
            other = {
                ["attribute-name"] = "#0f80d5",
            },
        },

        keyword = {
            default = "#4e59b7",
            control = {
                default = "#4e59b7",
                import = "#2a84d2",
                flow = "#0f80d5",
            },
            operator = "#4e59b7",
            declaration = "#4e59b7",
        },

        storage = {
            type = "#4e59b7",
            modifier = "#0f80d5",
        },

        variable = {
            default = "#c1c8d7",
            parameter = "#c1c8d7",
            other = {
                property = "#c1c8d7",
            },
        },

        punctuation = {
            separator = "#7b080c",
            section = "#7b080c",
        },

        markup = {
            default = "#c1c8d7",
            heading = "#2a84d2",
            raw = "#ecb90f",
            link = "#ecb90f",
            list = "#0f80d5",
            inserted = "#2cc55d",
            deleted = "#f71118",
        },

        meta = {
            preprocessor = "#0f80d5",
        },
    },
}
