-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#202124",
    base01 = "#27292c",
    base02 = "#323639",
    base03 = "#44464d",
    base04 = "#676c71",
    base05 = "#80868b",
    base06 = "#9e9e9e",
    base07 = "#ffffff",
    base08 = "#f44336",
    base09 = "#ff9800",
    base0A = "#ffeb3b",
    base0B = "#00e676",
    base0C = "#00bcd4",
    base0D = "#2196f3",
    base0E = "#673ab7",
    base0F = "#8d6e63",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#202124",
            bright = "#27292c",
        },
        gray = {
            dim = "#323639",
            normal = "#44464d",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#676c71",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#9e9e9e",
            normal = "#80868b",
            bright = "#ffffff",
        },
        red     = { normal = "#f44336", bright = "#f44336" },
        orange  = { normal = "#ff9800", bright = "#ff9800" },
        yellow  = { normal = "#ffeb3b", bright = "#ffeb3b" },
        green   = { normal = "#00e676", bright = "#00e676" },
        cyan    = { normal = "#00bcd4", bright = "#00bcd4" },
        blue    = { normal = "#2196f3", bright = "#2196f3" },
        magenta = { normal = "#673ab7", bright = "#673ab7" },
        brown   = { normal = "#8d6e63" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#202124" },
            foreground = { normal = "#80868b" },
        },
        cursor = {
            background = { normal = "#80868b" },
            foreground = { normal = "#202124" },
        },
        gutter = { foreground = "#323639" },
        border = { normal = "#44464d" },
        chrome = {
            background = {
                normal = "#323639",
                dark = "#27292c",
            },
            foreground = {
                normal = "#80868b",
                dark = "#676c71",
            },
        },
        selection = { background = "#27292c" },
        highlight = {
            line = { background = "#27292c" },
            text = { background = "#323639" },
            search = {
                background = "#27292c",
                foreground = "#ffeb3b",
            },
        },
        status = {
            error = "#f44336",
            warning = "#ff9800",
            info = "#ffeb3b",
            success = "#00e676",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#44464d",

        string = {
            default = "#00e676",
            regexp = "#00e676",
            other = "#00e676",
        },

        constant = {
            default = "#ff9800",
            character = {
                default = "#f44336",
                escape = "#00bcd4",
            },
            language = "#ff9800",
            numeric = {
                default = "#ff9800",
                float = "#ff9800",
            },
        },

        entity = {
            name = {
                class = "#ffeb3b",
                type = "#ffeb3b",
                ["function"] = {
                    default = "#2196f3",
                    constructor = "#2196f3",
                },
                label = "#ffeb3b",
                namespace = "#f44336",
                tag = "#ffeb3b",
            },
            other = {
                ["attribute-name"] = "#ffeb3b",
            },
        },

        keyword = {
            default = "#673ab7",
            control = {
                default = "#673ab7",
                import = "#2196f3",
                flow = "#ffeb3b",
            },
            operator = "#673ab7",
            declaration = "#673ab7",
        },

        storage = {
            type = "#673ab7",
            modifier = "#ffeb3b",
        },

        variable = {
            default = "#80868b",
            parameter = "#80868b",
            other = {
                property = "#80868b",
            },
        },

        punctuation = {
            separator = "#8d6e63",
            section = "#8d6e63",
        },

        markup = {
            default = "#80868b",
            heading = "#2196f3",
            raw = "#ff9800",
            link = "#ff9800",
            list = "#ffeb3b",
            inserted = "#00e676",
            deleted = "#f44336",
        },

        meta = {
            preprocessor = "#ffeb3b",
        },
    },
}
