-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "light",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#fcfcfc",
    base01 = "#e8e8e8",
    base02 = "#d4d4d4",
    base03 = "#c0c0c0",
    base04 = "#7e7e7e",
    base05 = "#545454",
    base06 = "#2a2a2a",
    base07 = "#000000",
    base08 = "#800000",
    base09 = "#fcfc54",
    base0A = "#808000",
    base0B = "#008000",
    base0C = "#008080",
    base0D = "#000080",
    base0E = "#800080",
    base0F = "#54fc54",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#fcfcfc",
            bright = "#e8e8e8",
        },
        gray = {
            dim = "#d4d4d4",
            normal = "#c0c0c0",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#7e7e7e",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#2a2a2a",
            normal = "#545454",
            bright = "#000000",
        },
        red     = { normal = "#800000", bright = "#800000" },
        orange  = { normal = "#fcfc54", bright = "#fcfc54" },
        yellow  = { normal = "#808000", bright = "#808000" },
        green   = { normal = "#008000", bright = "#008000" },
        cyan    = { normal = "#008080", bright = "#008080" },
        blue    = { normal = "#000080", bright = "#000080" },
        magenta = { normal = "#800080", bright = "#800080" },
        brown   = { normal = "#54fc54" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#fcfcfc" },
            foreground = { normal = "#545454" },
        },
        cursor = {
            background = { normal = "#545454" },
            foreground = { normal = "#fcfcfc" },
        },
        gutter = { foreground = "#d4d4d4" },
        border = { normal = "#c0c0c0" },
        chrome = {
            background = {
                normal = "#d4d4d4",
                dark = "#e8e8e8",
            },
            foreground = {
                normal = "#545454",
                dark = "#7e7e7e",
            },
        },
        selection = { background = "#e8e8e8" },
        highlight = {
            line = { background = "#e8e8e8" },
            text = { background = "#d4d4d4" },
            search = {
                background = "#e8e8e8",
                foreground = "#808000",
            },
        },
        status = {
            error = "#800000",
            warning = "#fcfc54",
            info = "#808000",
            success = "#008000",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#c0c0c0",

        string = {
            default = "#008000",
            regexp = "#008000",
            other = "#008000",
        },

        constant = {
            default = "#fcfc54",
            character = {
                default = "#800000",
                escape = "#008080",
            },
            language = "#fcfc54",
            numeric = {
                default = "#fcfc54",
                float = "#fcfc54",
            },
        },

        entity = {
            name = {
                class = "#808000",
                type = "#808000",
                ["function"] = {
                    default = "#000080",
                    constructor = "#000080",
                },
                label = "#808000",
                namespace = "#800000",
                tag = "#808000",
            },
            other = {
                ["attribute-name"] = "#808000",
            },
        },

        keyword = {
            default = "#800080",
            control = {
                default = "#800080",
                import = "#000080",
                flow = "#808000",
            },
            operator = "#800080",
            declaration = "#800080",
        },

        storage = {
            type = "#800080",
            modifier = "#808000",
        },

        variable = {
            default = "#545454",
            parameter = "#545454",
            other = {
                property = "#545454",
            },
        },

        punctuation = {
            separator = "#54fc54",
            section = "#54fc54",
        },

        markup = {
            default = "#545454",
            heading = "#000080",
            raw = "#fcfc54",
            link = "#fcfc54",
            list = "#808000",
            inserted = "#008000",
            deleted = "#800000",
        },

        meta = {
            preprocessor = "#808000",
        },
    },
}
