-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#1d2021",
    base01 = "#383c3e",
    base02 = "#53585b",
    base03 = "#6f7579",
    base04 = "#cdcdcd",
    base05 = "#d5d5d5",
    base06 = "#dddddd",
    base07 = "#e5e5e5",
    base08 = "#d72638",
    base09 = "#eb8413",
    base0A = "#f19d1a",
    base0B = "#88b92d",
    base0C = "#1ba595",
    base0D = "#1e8bac",
    base0E = "#be4264",
    base0F = "#c85e0d",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#1d2021",
            bright = "#383c3e",
        },
        gray = {
            dim = "#53585b",
            normal = "#6f7579",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#cdcdcd",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#dddddd",
            normal = "#d5d5d5",
            bright = "#e5e5e5",
        },
        red = { normal = "#d72638", bright = "#d72638" },
        orange = { normal = "#eb8413", bright = "#eb8413" },
        yellow = { normal = "#f19d1a", bright = "#f19d1a" },
        green = { normal = "#88b92d", bright = "#88b92d" },
        cyan = { normal = "#1ba595", bright = "#1ba595" },
        blue = { normal = "#1e8bac", bright = "#1e8bac" },
        magenta = { normal = "#be4264", bright = "#be4264" },
        brown = { normal = "#c85e0d" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#1d2021" },
            foreground = { normal = "#d5d5d5" },
        },
        cursor = {
            background = { normal = "#d5d5d5" },
            foreground = { normal = "#1d2021" },
        },
        gutter = { foreground = "#53585b" },
        border = { normal = "#6f7579" },
        chrome = {
            background = {
                normal = "#53585b",
                dark = "#383c3e",
            },
            foreground = {
                normal = "#d5d5d5",
                dark = "#cdcdcd",
            },
        },
        selection = { background = "#383c3e" },
        highlight = {
            line = { background = "#383c3e" },
            text = { background = "#53585b" },
            search = {
                background = "#383c3e",
                foreground = "#f19d1a",
            },
        },
        status = {
            error = "#d72638",
            warning = "#eb8413",
            info = "#f19d1a",
            success = "#88b92d",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#6f7579",

        string = {
            default = "#88b92d",
            regexp = "#88b92d",
            other = "#88b92d",
        },

        constant = {
            default = "#eb8413",
            character = {
                default = "#d72638",
                escape = "#1ba595",
            },
            language = "#eb8413",
            numeric = {
                default = "#eb8413",
                float = "#eb8413",
            },
        },

        entity = {
            name = {
                class = "#f19d1a",
                type = "#f19d1a",
                ["function"] = {
                    default = "#1e8bac",
                    constructor = "#1e8bac",
                },
                label = "#f19d1a",
                namespace = "#d72638",
                tag = "#f19d1a",
            },
            other = {
                ["attribute-name"] = "#f19d1a",
            },
        },

        keyword = {
            default = "#be4264",
            control = {
                default = "#be4264",
                import = "#1e8bac",
                flow = "#f19d1a",
            },
            operator = "#be4264",
            declaration = "#be4264",
        },

        storage = {
            type = "#be4264",
            modifier = "#f19d1a",
        },

        variable = {
            default = "#d5d5d5",
            parameter = "#d5d5d5",
            other = {
                property = "#d5d5d5",
            },
        },

        punctuation = {
            separator = "#c85e0d",
            section = "#c85e0d",
        },

        markup = {
            default = "#d5d5d5",
            heading = "#1e8bac",
            raw = "#eb8413",
            link = "#eb8413",
            list = "#f19d1a",
            inserted = "#88b92d",
            deleted = "#d72638",
        },

        meta = {
            preprocessor = "#f19d1a",
        },
    },
}
