-- Auto-generated by tinted-builder-rust from a base24 scheme.
-- Translates base24 slots into tinted8-shaped keys. Mirrors base16.lua.mustache
-- exactly, plus brights from base12-17 and DiagnosticOk = bright_green.
-- Do not edit by hand.

return {
    variant = "light",

    -- Legacy base24 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#fff4d6",
    base01 = "#f2d083",
    base02 = "#d69b45",
    base03 = "#80616b",
    base04 = "#684653",
    base05 = "#432c3b",
    base06 = "#2f1c2e",
    base07 = "#1c0f20",
    base08 = "#a63d4a",
    base09 = "#9b5b19",
    base0A = "#846600",
    base0B = "#327056",
    base0C = "#276e6c",
    base0D = "#365f91",
    base0E = "#784a78",
    base0F = "#704035",
    base10 = "#cf2944",
    base11 = "#c85d00",
    base12 = "#a86e00",
    base13 = "#007b4e",
    base14 = "#007b78",
    base15 = "#005eb8",
    base16 = "#9b3395",
    base17 = "#87301f",

    palette = {
        black = {
            normal = "#fff4d6",
            bright = "#f2d083",
        },
        gray = {
            dim = "#d69b45",
            normal = "#80616b",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#684653",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#2f1c2e",
            normal = "#432c3b",
            bright = "#1c0f20",
        },
        red = { normal = "#a63d4a", bright = "#a86e00" },
        -- base24 has no bright_orange slot; orange.bright falls back to .normal.
        orange = { normal = "#9b5b19", bright = "#9b5b19" },
        yellow = { normal = "#846600", bright = "#007b4e" },
        green = { normal = "#327056", bright = "#007b78" },
        cyan = { normal = "#276e6c", bright = "#005eb8" },
        blue = { normal = "#365f91", bright = "#9b3395" },
        magenta = { normal = "#784a78", bright = "#87301f" },
        brown = { normal = "#704035" },
    },

    ui = {
        global = {
            background = { normal = "#fff4d6" },
            foreground = { normal = "#432c3b" },
        },
        cursor = {
            background = { normal = "#432c3b" },
            foreground = { normal = "#fff4d6" },
        },
        gutter = { foreground = "#d69b45" },
        border = { normal = "#80616b" },
        chrome = {
            background = {
                normal = "#d69b45",
                dark = "#f2d083",
            },
            foreground = {
                normal = "#432c3b",
                dark = "#684653",
            },
        },
        selection = { background = "#f2d083" },
        highlight = {
            line = { background = "#f2d083" },
            text = { background = "#d69b45" },
            search = {
                background = "#f2d083",
                foreground = "#846600",
            },
        },
        status = {
            error = "#a63d4a",
            warning = "#9b5b19",
            info = "#846600",
            -- DiagnosticOk uses bright_green (base14) in current code; preserve.
            success = "#007b78",
        },
    },

    syntax = {
        comment = "#80616b",

        string = {
            default = "#327056",
            regexp = "#327056",
            other = "#327056",
        },

        constant = {
            default = "#9b5b19",
            character = {
                default = "#a63d4a",
                escape = "#276e6c",
            },
            language = "#9b5b19",
            numeric = {
                default = "#9b5b19",
                float = "#9b5b19",
            },
        },

        entity = {
            name = {
                class = "#846600",
                type = "#846600",
                ["function"] = {
                    default = "#365f91",
                    constructor = "#365f91",
                },
                label = "#846600",
                namespace = "#a63d4a",
                tag = "#846600",
            },
            other = {
                ["attribute-name"] = "#846600",
            },
        },

        keyword = {
            default = "#784a78",
            control = {
                default = "#784a78",
                import = "#365f91",
                flow = "#846600",
            },
            operator = "#784a78",
            declaration = "#784a78",
        },

        storage = {
            type = "#784a78",
            modifier = "#846600",
        },

        variable = {
            default = "#432c3b",
            parameter = "#432c3b",
            other = {
                property = "#432c3b",
            },
        },

        punctuation = {
            separator = "#704035",
            section = "#704035",
        },

        markup = {
            default = "#432c3b",
            heading = "#365f91",
            raw = "#9b5b19",
            link = "#9b5b19",
            list = "#846600",
            inserted = "#327056",
            deleted = "#a63d4a",
        },

        meta = {
            preprocessor = "#846600",
        },
    },
}
