-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#000000",
    base01 = "#1c1c1c",
    base02 = "#383838",
    base03 = "#545454",
    base04 = "#7e7e7e",
    base05 = "#a8a8a8",
    base06 = "#d2d2d2",
    base07 = "#fcfcfc",
    base08 = "#fc5454",
    base09 = "#a85400",
    base0A = "#fcfc54",
    base0B = "#54fc54",
    base0C = "#54fcfc",
    base0D = "#5454fc",
    base0E = "#fc54fc",
    base0F = "#00a800",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#000000",
            bright = "#1c1c1c",
        },
        gray = {
            dim = "#383838",
            normal = "#545454",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#7e7e7e",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#d2d2d2",
            normal = "#a8a8a8",
            bright = "#fcfcfc",
        },
        red = { normal = "#fc5454", bright = "#fc5454" },
        orange = { normal = "#a85400", bright = "#a85400" },
        yellow = { normal = "#fcfc54", bright = "#fcfc54" },
        green = { normal = "#54fc54", bright = "#54fc54" },
        cyan = { normal = "#54fcfc", bright = "#54fcfc" },
        blue = { normal = "#5454fc", bright = "#5454fc" },
        magenta = { normal = "#fc54fc", bright = "#fc54fc" },
        brown = { normal = "#00a800" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#000000" },
            foreground = { normal = "#a8a8a8" },
        },
        cursor = {
            background = { normal = "#a8a8a8" },
            foreground = { normal = "#000000" },
        },
        gutter = { foreground = "#383838" },
        border = { normal = "#545454" },
        chrome = {
            background = {
                normal = "#383838",
                dark = "#1c1c1c",
            },
            foreground = {
                normal = "#a8a8a8",
                dark = "#7e7e7e",
            },
        },
        selection = { background = "#1c1c1c" },
        highlight = {
            line = { background = "#1c1c1c" },
            text = { background = "#383838" },
            search = {
                background = "#1c1c1c",
                foreground = "#fcfc54",
            },
        },
        status = {
            error = "#fc5454",
            warning = "#a85400",
            info = "#fcfc54",
            success = "#54fc54",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#545454",

        string = {
            default = "#54fc54",
            regexp = "#54fc54",
            other = "#54fc54",
        },

        constant = {
            default = "#a85400",
            character = {
                default = "#fc5454",
                escape = "#54fcfc",
            },
            language = "#a85400",
            numeric = {
                default = "#a85400",
                float = "#a85400",
            },
        },

        entity = {
            name = {
                class = "#fcfc54",
                type = "#fcfc54",
                ["function"] = {
                    default = "#5454fc",
                    constructor = "#5454fc",
                },
                label = "#fcfc54",
                namespace = "#fc5454",
                tag = "#fcfc54",
            },
            other = {
                ["attribute-name"] = "#fcfc54",
            },
        },

        keyword = {
            default = "#fc54fc",
            control = {
                default = "#fc54fc",
                import = "#5454fc",
                flow = "#fcfc54",
            },
            operator = "#fc54fc",
            declaration = "#fc54fc",
        },

        storage = {
            type = "#fc54fc",
            modifier = "#fcfc54",
        },

        variable = {
            default = "#a8a8a8",
            parameter = "#a8a8a8",
            other = {
                property = "#a8a8a8",
            },
        },

        punctuation = {
            separator = "#00a800",
            section = "#00a800",
        },

        markup = {
            default = "#a8a8a8",
            heading = "#5454fc",
            raw = "#a85400",
            link = "#a85400",
            list = "#fcfc54",
            inserted = "#54fc54",
            deleted = "#fc5454",
        },

        meta = {
            preprocessor = "#fcfc54",
        },
    },
}
