-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#131f1f",
    base01 = "#213132",
    base02 = "#273d3c",
    base03 = "#3e5c53",
    base04 = "#6d9877",
    base05 = "#98c1a3",
    base06 = "#a5cbb9",
    base07 = "#aacbcb",
    base08 = "#d7586e",
    base09 = "#e6b466",
    base0A = "#dfe754",
    base0B = "#59d678",
    base0C = "#76dbd2",
    base0D = "#4ed2d2",
    base0E = "#a874e0",
    base0F = "#c05a8f",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#131f1f",
            bright = "#213132",
        },
        gray = {
            dim = "#273d3c",
            normal = "#3e5c53",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#6d9877",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#a5cbb9",
            normal = "#98c1a3",
            bright = "#aacbcb",
        },
        red = { normal = "#d7586e", bright = "#d7586e" },
        orange = { normal = "#e6b466", bright = "#e6b466" },
        yellow = { normal = "#dfe754", bright = "#dfe754" },
        green = { normal = "#59d678", bright = "#59d678" },
        cyan = { normal = "#76dbd2", bright = "#76dbd2" },
        blue = { normal = "#4ed2d2", bright = "#4ed2d2" },
        magenta = { normal = "#a874e0", bright = "#a874e0" },
        brown = { normal = "#c05a8f" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#131f1f" },
            foreground = { normal = "#98c1a3" },
        },
        cursor = {
            background = { normal = "#98c1a3" },
            foreground = { normal = "#131f1f" },
        },
        gutter = { foreground = "#273d3c" },
        border = { normal = "#3e5c53" },
        chrome = {
            background = {
                normal = "#273d3c",
                dark = "#213132",
            },
            foreground = {
                normal = "#98c1a3",
                dark = "#6d9877",
            },
        },
        selection = { background = "#213132" },
        highlight = {
            line = { background = "#213132" },
            text = { background = "#273d3c" },
            search = {
                background = "#213132",
                foreground = "#dfe754",
            },
        },
        status = {
            error = "#d7586e",
            warning = "#e6b466",
            info = "#dfe754",
            success = "#59d678",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#3e5c53",

        string = {
            default = "#59d678",
            regexp = "#59d678",
            other = "#59d678",
        },

        constant = {
            default = "#e6b466",
            character = {
                default = "#d7586e",
                escape = "#76dbd2",
            },
            language = "#e6b466",
            numeric = {
                default = "#e6b466",
                float = "#e6b466",
            },
        },

        entity = {
            name = {
                class = "#dfe754",
                type = "#dfe754",
                ["function"] = {
                    default = "#4ed2d2",
                    constructor = "#4ed2d2",
                },
                label = "#dfe754",
                namespace = "#d7586e",
                tag = "#dfe754",
            },
            other = {
                ["attribute-name"] = "#dfe754",
            },
        },

        keyword = {
            default = "#a874e0",
            control = {
                default = "#a874e0",
                import = "#4ed2d2",
                flow = "#dfe754",
            },
            operator = "#a874e0",
            declaration = "#a874e0",
        },

        storage = {
            type = "#a874e0",
            modifier = "#dfe754",
        },

        variable = {
            default = "#98c1a3",
            parameter = "#98c1a3",
            other = {
                property = "#98c1a3",
            },
        },

        punctuation = {
            separator = "#c05a8f",
            section = "#c05a8f",
        },

        markup = {
            default = "#98c1a3",
            heading = "#4ed2d2",
            raw = "#e6b466",
            link = "#e6b466",
            list = "#dfe754",
            inserted = "#59d678",
            deleted = "#d7586e",
        },

        meta = {
            preprocessor = "#dfe754",
        },
    },
}
