-- Auto-generated by tinted-builder-rust from a base24 scheme.
-- Translates base24 slots into tinted8-shaped keys. Mirrors base16.lua.mustache
-- exactly, plus brights from base12-17 and DiagnosticOk = bright_green.
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base24 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#243434",
    base01 = "#757575",
    base02 = "#8a8a8a",
    base03 = "#9f9f9f",
    base04 = "#b5b5b5",
    base05 = "#cacaca",
    base06 = "#e0e0e0",
    base07 = "#e0e0e0",
    base08 = "#825d4d",
    base09 = "#ada16d",
    base0A = "#79c3cf",
    base0B = "#718c61",
    base0C = "#719393",
    base0D = "#4d7b82",
    base0E = "#8a7167",
    base0F = "#412e26",
    base10 = "#5c5c5c",
    base11 = "#2e2e2e",
    base12 = "#cf9379",
    base13 = "#fae79d",
    base14 = "#98d9aa",
    base15 = "#ade0e0",
    base16 = "#79c3cf",
    base17 = "#d6b2a1",

    palette = {
        black = {
            normal = "#243434",
            bright = "#757575",
        },
        gray = {
            dim = "#8a8a8a",
            normal = "#9f9f9f",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#b5b5b5",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#e0e0e0",
            normal = "#cacaca",
            bright = "#e0e0e0",
        },
        red     = { normal = "#825d4d", bright = "#cf9379" },
        -- base24 has no bright_orange slot; orange.bright falls back to .normal.
        orange  = { normal = "#ada16d", bright = "#ada16d" },
        yellow  = { normal = "#79c3cf", bright = "#fae79d" },
        green   = { normal = "#718c61", bright = "#98d9aa" },
        cyan    = { normal = "#719393", bright = "#ade0e0" },
        blue    = { normal = "#4d7b82", bright = "#79c3cf" },
        magenta = { normal = "#8a7167", bright = "#d6b2a1" },
        brown   = { normal = "#412e26" },
    },

    ui = {
        global = {
            background = { normal = "#243434" },
            foreground = { normal = "#cacaca" },
        },
        cursor = {
            background = { normal = "#cacaca" },
            foreground = { normal = "#243434" },
        },
        gutter = { foreground = "#8a8a8a" },
        border = { normal = "#9f9f9f" },
        chrome = {
            background = {
                normal = "#8a8a8a",
                dark = "#757575",
            },
            foreground = {
                normal = "#cacaca",
                dark = "#b5b5b5",
            },
        },
        selection = { background = "#757575" },
        highlight = {
            line = { background = "#757575" },
            text = { background = "#8a8a8a" },
            search = {
                background = "#757575",
                foreground = "#79c3cf",
            },
        },
        status = {
            error = "#825d4d",
            warning = "#ada16d",
            info = "#79c3cf",
            -- DiagnosticOk uses bright_green (base14) in current code; preserve.
            success = "#98d9aa",
        },
    },

    syntax = {
        comment = "#9f9f9f",

        string = {
            default = "#718c61",
            regexp = "#718c61",
            other = "#718c61",
        },

        constant = {
            default = "#ada16d",
            character = {
                default = "#825d4d",
                escape = "#719393",
            },
            language = "#ada16d",
            numeric = {
                default = "#ada16d",
                float = "#ada16d",
            },
        },

        entity = {
            name = {
                class = "#79c3cf",
                type = "#79c3cf",
                ["function"] = {
                    default = "#4d7b82",
                    constructor = "#4d7b82",
                },
                label = "#79c3cf",
                namespace = "#825d4d",
                tag = "#79c3cf",
            },
            other = {
                ["attribute-name"] = "#79c3cf",
            },
        },

        keyword = {
            default = "#8a7167",
            control = {
                default = "#8a7167",
                import = "#4d7b82",
                flow = "#79c3cf",
            },
            operator = "#8a7167",
            declaration = "#8a7167",
        },

        storage = {
            type = "#8a7167",
            modifier = "#79c3cf",
        },

        variable = {
            default = "#cacaca",
            parameter = "#cacaca",
            other = {
                property = "#cacaca",
            },
        },

        punctuation = {
            separator = "#412e26",
            section = "#412e26",
        },

        markup = {
            default = "#cacaca",
            heading = "#4d7b82",
            raw = "#ada16d",
            link = "#ada16d",
            list = "#79c3cf",
            inserted = "#718c61",
            deleted = "#825d4d",
        },

        meta = {
            preprocessor = "#79c3cf",
        },
    },
}
