-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#182430",
    base01 = "#243c54",
    base02 = "#46290a",
    base03 = "#616d78",
    base04 = "#74afe7",
    base05 = "#c8e1f8",
    base06 = "#ddeaf6",
    base07 = "#8f98a0",
    base08 = "#4ce587",
    base09 = "#f6a85c",
    base0A = "#f6cd5c",
    base0B = "#c3e88d",
    base0C = "#5fd1ff",
    base0D = "#82aaff",
    base0E = "#ff84dd",
    base0F = "#bbd2e8",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#182430",
            bright = "#243c54",
        },
        gray = {
            dim = "#46290a",
            normal = "#616d78",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#74afe7",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#ddeaf6",
            normal = "#c8e1f8",
            bright = "#8f98a0",
        },
        red     = { normal = "#4ce587", bright = "#4ce587" },
        orange  = { normal = "#f6a85c", bright = "#f6a85c" },
        yellow  = { normal = "#f6cd5c", bright = "#f6cd5c" },
        green   = { normal = "#c3e88d", bright = "#c3e88d" },
        cyan    = { normal = "#5fd1ff", bright = "#5fd1ff" },
        blue    = { normal = "#82aaff", bright = "#82aaff" },
        magenta = { normal = "#ff84dd", bright = "#ff84dd" },
        brown   = { normal = "#bbd2e8" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#182430" },
            foreground = { normal = "#c8e1f8" },
        },
        cursor = {
            background = { normal = "#c8e1f8" },
            foreground = { normal = "#182430" },
        },
        gutter = { foreground = "#46290a" },
        border = { normal = "#616d78" },
        chrome = {
            background = {
                normal = "#46290a",
                dark = "#243c54",
            },
            foreground = {
                normal = "#c8e1f8",
                dark = "#74afe7",
            },
        },
        selection = { background = "#243c54" },
        highlight = {
            line = { background = "#243c54" },
            text = { background = "#46290a" },
            search = {
                background = "#243c54",
                foreground = "#f6cd5c",
            },
        },
        status = {
            error = "#4ce587",
            warning = "#f6a85c",
            info = "#f6cd5c",
            success = "#c3e88d",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#616d78",

        string = {
            default = "#c3e88d",
            regexp = "#c3e88d",
            other = "#c3e88d",
        },

        constant = {
            default = "#f6a85c",
            character = {
                default = "#4ce587",
                escape = "#5fd1ff",
            },
            language = "#f6a85c",
            numeric = {
                default = "#f6a85c",
                float = "#f6a85c",
            },
        },

        entity = {
            name = {
                class = "#f6cd5c",
                type = "#f6cd5c",
                ["function"] = {
                    default = "#82aaff",
                    constructor = "#82aaff",
                },
                label = "#f6cd5c",
                namespace = "#4ce587",
                tag = "#f6cd5c",
            },
            other = {
                ["attribute-name"] = "#f6cd5c",
            },
        },

        keyword = {
            default = "#ff84dd",
            control = {
                default = "#ff84dd",
                import = "#82aaff",
                flow = "#f6cd5c",
            },
            operator = "#ff84dd",
            declaration = "#ff84dd",
        },

        storage = {
            type = "#ff84dd",
            modifier = "#f6cd5c",
        },

        variable = {
            default = "#c8e1f8",
            parameter = "#c8e1f8",
            other = {
                property = "#c8e1f8",
            },
        },

        punctuation = {
            separator = "#bbd2e8",
            section = "#bbd2e8",
        },

        markup = {
            default = "#c8e1f8",
            heading = "#82aaff",
            raw = "#f6a85c",
            link = "#f6a85c",
            list = "#f6cd5c",
            inserted = "#c3e88d",
            deleted = "#4ce587",
        },

        meta = {
            preprocessor = "#f6cd5c",
        },
    },
}
