-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#181616",
    base01 = "#282727",
    base02 = "#393836",
    base03 = "#625e5a",
    base04 = "#737c73",
    base05 = "#c5c9c5",
    base06 = "#c8c093",
    base07 = "#c5c9c5",
    base08 = "#c4746e",
    base09 = "#b6927b",
    base0A = "#c4b28a",
    base0B = "#8a9a7b",
    base0C = "#8ea4a2",
    base0D = "#8ba4b0",
    base0E = "#a292a3",
    base0F = "#b98d7b",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#181616",
            bright = "#282727",
        },
        gray = {
            dim = "#393836",
            normal = "#625e5a",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#737c73",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#c8c093",
            normal = "#c5c9c5",
            bright = "#c5c9c5",
        },
        red     = { normal = "#c4746e", bright = "#c4746e" },
        orange  = { normal = "#b6927b", bright = "#b6927b" },
        yellow  = { normal = "#c4b28a", bright = "#c4b28a" },
        green   = { normal = "#8a9a7b", bright = "#8a9a7b" },
        cyan    = { normal = "#8ea4a2", bright = "#8ea4a2" },
        blue    = { normal = "#8ba4b0", bright = "#8ba4b0" },
        magenta = { normal = "#a292a3", bright = "#a292a3" },
        brown   = { normal = "#b98d7b" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#181616" },
            foreground = { normal = "#c5c9c5" },
        },
        cursor = {
            background = { normal = "#c5c9c5" },
            foreground = { normal = "#181616" },
        },
        gutter = { foreground = "#393836" },
        border = { normal = "#625e5a" },
        chrome = {
            background = {
                normal = "#393836",
                dark = "#282727",
            },
            foreground = {
                normal = "#c5c9c5",
                dark = "#737c73",
            },
        },
        selection = { background = "#282727" },
        highlight = {
            line = { background = "#282727" },
            text = { background = "#393836" },
            search = {
                background = "#282727",
                foreground = "#c4b28a",
            },
        },
        status = {
            error = "#c4746e",
            warning = "#b6927b",
            info = "#c4b28a",
            success = "#8a9a7b",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#625e5a",

        string = {
            default = "#8a9a7b",
            regexp = "#8a9a7b",
            other = "#8a9a7b",
        },

        constant = {
            default = "#b6927b",
            character = {
                default = "#c4746e",
                escape = "#8ea4a2",
            },
            language = "#b6927b",
            numeric = {
                default = "#b6927b",
                float = "#b6927b",
            },
        },

        entity = {
            name = {
                class = "#c4b28a",
                type = "#c4b28a",
                ["function"] = {
                    default = "#8ba4b0",
                    constructor = "#8ba4b0",
                },
                label = "#c4b28a",
                namespace = "#c4746e",
                tag = "#c4b28a",
            },
            other = {
                ["attribute-name"] = "#c4b28a",
            },
        },

        keyword = {
            default = "#a292a3",
            control = {
                default = "#a292a3",
                import = "#8ba4b0",
                flow = "#c4b28a",
            },
            operator = "#a292a3",
            declaration = "#a292a3",
        },

        storage = {
            type = "#a292a3",
            modifier = "#c4b28a",
        },

        variable = {
            default = "#c5c9c5",
            parameter = "#c5c9c5",
            other = {
                property = "#c5c9c5",
            },
        },

        punctuation = {
            separator = "#b98d7b",
            section = "#b98d7b",
        },

        markup = {
            default = "#c5c9c5",
            heading = "#8ba4b0",
            raw = "#b6927b",
            link = "#b6927b",
            list = "#c4b28a",
            inserted = "#8a9a7b",
            deleted = "#c4746e",
        },

        meta = {
            preprocessor = "#c4b28a",
        },
    },
}
