-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "light",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#fff5e5",
    base01 = "#ece4d6",
    base02 = "#d9d3c8",
    base03 = "#7f8080",
    base04 = "#5d6065",
    base05 = "#4e5359",
    base06 = "#4e5359",
    base07 = "#4e5359",
    base08 = "#b14745",
    base09 = "#a25600",
    base0A = "#876500",
    base0B = "#557300",
    base0C = "#0e7767",
    base0D = "#246da5",
    base0E = "#7a50c6",
    base0F = "#a83f92",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#fff5e5",
            bright = "#ece4d6",
        },
        gray = {
            dim = "#d9d3c8",
            normal = "#7f8080",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#5d6065",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#4e5359",
            normal = "#4e5359",
            bright = "#4e5359",
        },
        red = { normal = "#b14745", bright = "#b14745" },
        orange = { normal = "#a25600", bright = "#a25600" },
        yellow = { normal = "#876500", bright = "#876500" },
        green = { normal = "#557300", bright = "#557300" },
        cyan = { normal = "#0e7767", bright = "#0e7767" },
        blue = { normal = "#246da5", bright = "#246da5" },
        magenta = { normal = "#7a50c6", bright = "#7a50c6" },
        brown = { normal = "#a83f92" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#fff5e5" },
            foreground = { normal = "#4e5359" },
        },
        cursor = {
            background = { normal = "#4e5359" },
            foreground = { normal = "#fff5e5" },
        },
        gutter = { foreground = "#d9d3c8" },
        border = { normal = "#7f8080" },
        chrome = {
            background = {
                normal = "#d9d3c8",
                dark = "#ece4d6",
            },
            foreground = {
                normal = "#4e5359",
                dark = "#5d6065",
            },
        },
        selection = { background = "#ece4d6" },
        highlight = {
            line = { background = "#ece4d6" },
            text = { background = "#d9d3c8" },
            search = {
                background = "#ece4d6",
                foreground = "#876500",
            },
        },
        status = {
            error = "#b14745",
            warning = "#a25600",
            info = "#876500",
            success = "#557300",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#7f8080",

        string = {
            default = "#557300",
            regexp = "#557300",
            other = "#557300",
        },

        constant = {
            default = "#a25600",
            character = {
                default = "#b14745",
                escape = "#0e7767",
            },
            language = "#a25600",
            numeric = {
                default = "#a25600",
                float = "#a25600",
            },
        },

        entity = {
            name = {
                class = "#876500",
                type = "#876500",
                ["function"] = {
                    default = "#246da5",
                    constructor = "#246da5",
                },
                label = "#876500",
                namespace = "#b14745",
                tag = "#876500",
            },
            other = {
                ["attribute-name"] = "#876500",
            },
        },

        keyword = {
            default = "#7a50c6",
            control = {
                default = "#7a50c6",
                import = "#246da5",
                flow = "#876500",
            },
            operator = "#7a50c6",
            declaration = "#7a50c6",
        },

        storage = {
            type = "#7a50c6",
            modifier = "#876500",
        },

        variable = {
            default = "#4e5359",
            parameter = "#4e5359",
            other = {
                property = "#4e5359",
            },
        },

        punctuation = {
            separator = "#a83f92",
            section = "#a83f92",
        },

        markup = {
            default = "#4e5359",
            heading = "#246da5",
            raw = "#a25600",
            link = "#a25600",
            list = "#876500",
            inserted = "#557300",
            deleted = "#b14745",
        },

        meta = {
            preprocessor = "#876500",
        },
    },
}
