-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#231f20",
    base01 = "#1c3f95",
    base02 = "#5a5758",
    base03 = "#737171",
    base04 = "#959ca1",
    base05 = "#d9d8d8",
    base06 = "#e7e7e8",
    base07 = "#ffffff",
    base08 = "#ee2e24",
    base09 = "#f386a1",
    base0A = "#ffd204",
    base0B = "#00853e",
    base0C = "#85cebc",
    base0D = "#009ddc",
    base0E = "#98005d",
    base0F = "#b06110",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#231f20",
            bright = "#1c3f95",
        },
        gray = {
            dim = "#5a5758",
            normal = "#737171",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#959ca1",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#e7e7e8",
            normal = "#d9d8d8",
            bright = "#ffffff",
        },
        red     = { normal = "#ee2e24", bright = "#ee2e24" },
        orange  = { normal = "#f386a1", bright = "#f386a1" },
        yellow  = { normal = "#ffd204", bright = "#ffd204" },
        green   = { normal = "#00853e", bright = "#00853e" },
        cyan    = { normal = "#85cebc", bright = "#85cebc" },
        blue    = { normal = "#009ddc", bright = "#009ddc" },
        magenta = { normal = "#98005d", bright = "#98005d" },
        brown   = { normal = "#b06110" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#231f20" },
            foreground = { normal = "#d9d8d8" },
        },
        cursor = {
            background = { normal = "#d9d8d8" },
            foreground = { normal = "#231f20" },
        },
        gutter = { foreground = "#5a5758" },
        border = { normal = "#737171" },
        chrome = {
            background = {
                normal = "#5a5758",
                dark = "#1c3f95",
            },
            foreground = {
                normal = "#d9d8d8",
                dark = "#959ca1",
            },
        },
        selection = { background = "#1c3f95" },
        highlight = {
            line = { background = "#1c3f95" },
            text = { background = "#5a5758" },
            search = {
                background = "#1c3f95",
                foreground = "#ffd204",
            },
        },
        status = {
            error = "#ee2e24",
            warning = "#f386a1",
            info = "#ffd204",
            success = "#00853e",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#737171",

        string = {
            default = "#00853e",
            regexp = "#00853e",
            other = "#00853e",
        },

        constant = {
            default = "#f386a1",
            character = {
                default = "#ee2e24",
                escape = "#85cebc",
            },
            language = "#f386a1",
            numeric = {
                default = "#f386a1",
                float = "#f386a1",
            },
        },

        entity = {
            name = {
                class = "#ffd204",
                type = "#ffd204",
                ["function"] = {
                    default = "#009ddc",
                    constructor = "#009ddc",
                },
                label = "#ffd204",
                namespace = "#ee2e24",
                tag = "#ffd204",
            },
            other = {
                ["attribute-name"] = "#ffd204",
            },
        },

        keyword = {
            default = "#98005d",
            control = {
                default = "#98005d",
                import = "#009ddc",
                flow = "#ffd204",
            },
            operator = "#98005d",
            declaration = "#98005d",
        },

        storage = {
            type = "#98005d",
            modifier = "#ffd204",
        },

        variable = {
            default = "#d9d8d8",
            parameter = "#d9d8d8",
            other = {
                property = "#d9d8d8",
            },
        },

        punctuation = {
            separator = "#b06110",
            section = "#b06110",
        },

        markup = {
            default = "#d9d8d8",
            heading = "#009ddc",
            raw = "#f386a1",
            link = "#f386a1",
            list = "#ffd204",
            inserted = "#00853e",
            deleted = "#ee2e24",
        },

        meta = {
            preprocessor = "#ffd204",
        },
    },
}
