-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "light",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#ffffff",
    base01 = "#c0c0c0",
    base02 = "#c0c0c0",
    base03 = "#808080",
    base04 = "#808080",
    base05 = "#404040",
    base06 = "#404040",
    base07 = "#5e5e5e",
    base08 = "#c41a15",
    base09 = "#eb8500",
    base0A = "#826b28",
    base0B = "#007400",
    base0C = "#318495",
    base0D = "#0000ff",
    base0E = "#a90d91",
    base0F = "#826b28",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#ffffff",
            bright = "#c0c0c0",
        },
        gray = {
            dim = "#c0c0c0",
            normal = "#808080",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#808080",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#404040",
            normal = "#404040",
            bright = "#5e5e5e",
        },
        red     = { normal = "#c41a15", bright = "#c41a15" },
        orange  = { normal = "#eb8500", bright = "#eb8500" },
        yellow  = { normal = "#826b28", bright = "#826b28" },
        green   = { normal = "#007400", bright = "#007400" },
        cyan    = { normal = "#318495", bright = "#318495" },
        blue    = { normal = "#0000ff", bright = "#0000ff" },
        magenta = { normal = "#a90d91", bright = "#a90d91" },
        brown   = { normal = "#826b28" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#ffffff" },
            foreground = { normal = "#404040" },
        },
        cursor = {
            background = { normal = "#404040" },
            foreground = { normal = "#ffffff" },
        },
        gutter = { foreground = "#c0c0c0" },
        border = { normal = "#808080" },
        chrome = {
            background = {
                normal = "#c0c0c0",
                dark = "#c0c0c0",
            },
            foreground = {
                normal = "#404040",
                dark = "#808080",
            },
        },
        selection = { background = "#c0c0c0" },
        highlight = {
            line = { background = "#c0c0c0" },
            text = { background = "#c0c0c0" },
            search = {
                background = "#c0c0c0",
                foreground = "#826b28",
            },
        },
        status = {
            error = "#c41a15",
            warning = "#eb8500",
            info = "#826b28",
            success = "#007400",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#808080",

        string = {
            default = "#007400",
            regexp = "#007400",
            other = "#007400",
        },

        constant = {
            default = "#eb8500",
            character = {
                default = "#c41a15",
                escape = "#318495",
            },
            language = "#eb8500",
            numeric = {
                default = "#eb8500",
                float = "#eb8500",
            },
        },

        entity = {
            name = {
                class = "#826b28",
                type = "#826b28",
                ["function"] = {
                    default = "#0000ff",
                    constructor = "#0000ff",
                },
                label = "#826b28",
                namespace = "#c41a15",
                tag = "#826b28",
            },
            other = {
                ["attribute-name"] = "#826b28",
            },
        },

        keyword = {
            default = "#a90d91",
            control = {
                default = "#a90d91",
                import = "#0000ff",
                flow = "#826b28",
            },
            operator = "#a90d91",
            declaration = "#a90d91",
        },

        storage = {
            type = "#a90d91",
            modifier = "#826b28",
        },

        variable = {
            default = "#404040",
            parameter = "#404040",
            other = {
                property = "#404040",
            },
        },

        punctuation = {
            separator = "#826b28",
            section = "#826b28",
        },

        markup = {
            default = "#404040",
            heading = "#0000ff",
            raw = "#eb8500",
            link = "#eb8500",
            list = "#826b28",
            inserted = "#007400",
            deleted = "#c41a15",
        },

        meta = {
            preprocessor = "#826b28",
        },
    },
}
