-- Auto-generated by tinted-builder-rust from a base24 scheme.
-- Translates base24 slots into tinted8-shaped keys. Mirrors base16.lua.mustache
-- exactly, plus brights from base12-17 and DiagnosticOk = bright_green.
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base24 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#1c1e20",
    base01 = "#1c1d19",
    base02 = "#1c1d19",
    base03 = "#545552",
    base04 = "#8d8e8b",
    base05 = "#c5c6c4",
    base06 = "#fefffe",
    base07 = "#fefffe",
    base08 = "#f18238",
    base09 = "#f3ef6d",
    base0A = "#61b8d0",
    base0B = "#9ed264",
    base0C = "#d53864",
    base0D = "#4f96be",
    base0E = "#695abb",
    base0F = "#78411c",
    base10 = "#121310",
    base11 = "#090908",
    base12 = "#d12a24",
    base13 = "#ff8948",
    base14 = "#a7d32c",
    base15 = "#d53864",
    base16 = "#61b8d0",
    base17 = "#695abb",

    palette = {
        black = {
            normal = "#1c1e20",
            bright = "#1c1d19",
        },
        gray = {
            dim = "#1c1d19",
            normal = "#545552",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#8d8e8b",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#fefffe",
            normal = "#c5c6c4",
            bright = "#fefffe",
        },
        red = { normal = "#f18238", bright = "#d12a24" },
        -- base24 has no bright_orange slot; orange.bright falls back to .normal.
        orange = { normal = "#f3ef6d", bright = "#f3ef6d" },
        yellow = { normal = "#61b8d0", bright = "#ff8948" },
        green = { normal = "#9ed264", bright = "#a7d32c" },
        cyan = { normal = "#d53864", bright = "#d53864" },
        blue = { normal = "#4f96be", bright = "#61b8d0" },
        magenta = { normal = "#695abb", bright = "#695abb" },
        brown = { normal = "#78411c" },
    },

    ui = {
        global = {
            background = { normal = "#1c1e20" },
            foreground = { normal = "#c5c6c4" },
        },
        cursor = {
            background = { normal = "#c5c6c4" },
            foreground = { normal = "#1c1e20" },
        },
        gutter = { foreground = "#1c1d19" },
        border = { normal = "#545552" },
        chrome = {
            background = {
                normal = "#1c1d19",
                dark = "#1c1d19",
            },
            foreground = {
                normal = "#c5c6c4",
                dark = "#8d8e8b",
            },
        },
        selection = { background = "#1c1d19" },
        highlight = {
            line = { background = "#1c1d19" },
            text = { background = "#1c1d19" },
            search = {
                background = "#1c1d19",
                foreground = "#61b8d0",
            },
        },
        status = {
            error = "#f18238",
            warning = "#f3ef6d",
            info = "#61b8d0",
            -- DiagnosticOk uses bright_green (base14) in current code; preserve.
            success = "#a7d32c",
        },
    },

    syntax = {
        comment = "#545552",

        string = {
            default = "#9ed264",
            regexp = "#9ed264",
            other = "#9ed264",
        },

        constant = {
            default = "#f3ef6d",
            character = {
                default = "#f18238",
                escape = "#d53864",
            },
            language = "#f3ef6d",
            numeric = {
                default = "#f3ef6d",
                float = "#f3ef6d",
            },
        },

        entity = {
            name = {
                class = "#61b8d0",
                type = "#61b8d0",
                ["function"] = {
                    default = "#4f96be",
                    constructor = "#4f96be",
                },
                label = "#61b8d0",
                namespace = "#f18238",
                tag = "#61b8d0",
            },
            other = {
                ["attribute-name"] = "#61b8d0",
            },
        },

        keyword = {
            default = "#695abb",
            control = {
                default = "#695abb",
                import = "#4f96be",
                flow = "#61b8d0",
            },
            operator = "#695abb",
            declaration = "#695abb",
        },

        storage = {
            type = "#695abb",
            modifier = "#61b8d0",
        },

        variable = {
            default = "#c5c6c4",
            parameter = "#c5c6c4",
            other = {
                property = "#c5c6c4",
            },
        },

        punctuation = {
            separator = "#78411c",
            section = "#78411c",
        },

        markup = {
            default = "#c5c6c4",
            heading = "#4f96be",
            raw = "#f3ef6d",
            link = "#f3ef6d",
            list = "#61b8d0",
            inserted = "#9ed264",
            deleted = "#f18238",
        },

        meta = {
            preprocessor = "#61b8d0",
        },
    },
}
