-- Auto-generated by tinted-builder-rust from a base24 scheme.
-- Translates base24 slots into tinted8-shaped keys. Mirrors base16.lua.mustache
-- exactly, plus brights from base12-17 and DiagnosticOk = bright_green.
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base24 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#262626",
    base01 = "#303030",
    base02 = "#3a3a3a",
    base03 = "#444444",
    base04 = "#6c6c6c",
    base05 = "#bcbcbc",
    base06 = "#dfdfdf",
    base07 = "#ffffff",
    base08 = "#af5f5f",
    base09 = "#ff8700",
    base0A = "#87875f",
    base0B = "#5f875f",
    base0C = "#5f8787",
    base0D = "#5f87af",
    base0E = "#5f5f87",
    base0F = "#af5f5f",
    base10 = "#1c1c1c",
    base11 = "#121212",
    base12 = "#ff8700",
    base13 = "#ffffaf",
    base14 = "#87af87",
    base15 = "#5fafaf",
    base16 = "#87afd7",
    base17 = "#8787af",

    palette = {
        black = {
            normal = "#262626",
            bright = "#303030",
        },
        gray = {
            dim = "#3a3a3a",
            normal = "#444444",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#6c6c6c",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#dfdfdf",
            normal = "#bcbcbc",
            bright = "#ffffff",
        },
        red = { normal = "#af5f5f", bright = "#ff8700" },
        -- base24 has no bright_orange slot; orange.bright falls back to .normal.
        orange = { normal = "#ff8700", bright = "#ff8700" },
        yellow = { normal = "#87875f", bright = "#ffffaf" },
        green = { normal = "#5f875f", bright = "#87af87" },
        cyan = { normal = "#5f8787", bright = "#5fafaf" },
        blue = { normal = "#5f87af", bright = "#87afd7" },
        magenta = { normal = "#5f5f87", bright = "#8787af" },
        brown = { normal = "#af5f5f" },
    },

    ui = {
        global = {
            background = { normal = "#262626" },
            foreground = { normal = "#bcbcbc" },
        },
        cursor = {
            background = { normal = "#bcbcbc" },
            foreground = { normal = "#262626" },
        },
        gutter = { foreground = "#3a3a3a" },
        border = { normal = "#444444" },
        chrome = {
            background = {
                normal = "#3a3a3a",
                dark = "#303030",
            },
            foreground = {
                normal = "#bcbcbc",
                dark = "#6c6c6c",
            },
        },
        selection = { background = "#303030" },
        highlight = {
            line = { background = "#303030" },
            text = { background = "#3a3a3a" },
            search = {
                background = "#303030",
                foreground = "#87875f",
            },
        },
        status = {
            error = "#af5f5f",
            warning = "#ff8700",
            info = "#87875f",
            -- DiagnosticOk uses bright_green (base14) in current code; preserve.
            success = "#87af87",
        },
    },

    syntax = {
        comment = "#444444",

        string = {
            default = "#5f875f",
            regexp = "#5f875f",
            other = "#5f875f",
        },

        constant = {
            default = "#ff8700",
            character = {
                default = "#af5f5f",
                escape = "#5f8787",
            },
            language = "#ff8700",
            numeric = {
                default = "#ff8700",
                float = "#ff8700",
            },
        },

        entity = {
            name = {
                class = "#87875f",
                type = "#87875f",
                ["function"] = {
                    default = "#5f87af",
                    constructor = "#5f87af",
                },
                label = "#87875f",
                namespace = "#af5f5f",
                tag = "#87875f",
            },
            other = {
                ["attribute-name"] = "#87875f",
            },
        },

        keyword = {
            default = "#5f5f87",
            control = {
                default = "#5f5f87",
                import = "#5f87af",
                flow = "#87875f",
            },
            operator = "#5f5f87",
            declaration = "#5f5f87",
        },

        storage = {
            type = "#5f5f87",
            modifier = "#87875f",
        },

        variable = {
            default = "#bcbcbc",
            parameter = "#bcbcbc",
            other = {
                property = "#bcbcbc",
            },
        },

        punctuation = {
            separator = "#af5f5f",
            section = "#af5f5f",
        },

        markup = {
            default = "#bcbcbc",
            heading = "#5f87af",
            raw = "#ff8700",
            link = "#ff8700",
            list = "#87875f",
            inserted = "#5f875f",
            deleted = "#af5f5f",
        },

        meta = {
            preprocessor = "#87875f",
        },
    },
}
