-- Auto-generated by tinted-builder-rust from a base16 scheme.
-- Translates base16 slots into tinted8-shaped keys. Per-key justification
-- lives in the per-highlight audit; in short, every key fill below is
-- driven by current-code rendering of base16 themes (parity-preserving).
-- Do not edit by hand.

return {
    variant = "dark",

    -- Legacy base16 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#333c43",
    base01 = "#3a464c",
    base02 = "#4d5960",
    base03 = "#859289",
    base04 = "#9da9a0",
    base05 = "#d3c6aa",
    base06 = "#ddd8be",
    base07 = "#f3ead3",
    base08 = "#e67e80",
    base09 = "#e69875",
    base0A = "#dbbc7f",
    base0B = "#a7c080",
    base0C = "#83c092",
    base0D = "#7fbbb3",
    base0E = "#d699b6",
    base0F = "#9da9a0",

    -- Named palette colors. base16 has no bright/dim variants,
    -- so .bright falls back to .normal (matches legacy alias behavior).
    palette = {
        black = {
            normal = "#333c43",
            bright = "#3a464c",
        },
        gray = {
            dim = "#4d5960",
            normal = "#859289",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#9da9a0",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#ddd8be",
            normal = "#d3c6aa",
            bright = "#f3ead3",
        },
        red     = { normal = "#e67e80", bright = "#e67e80" },
        orange  = { normal = "#e69875", bright = "#e69875" },
        yellow  = { normal = "#dbbc7f", bright = "#dbbc7f" },
        green   = { normal = "#a7c080", bright = "#a7c080" },
        cyan    = { normal = "#83c092", bright = "#83c092" },
        blue    = { normal = "#7fbbb3", bright = "#7fbbb3" },
        magenta = { normal = "#d699b6", bright = "#d699b6" },
        brown   = { normal = "#9da9a0" },
    },

    -- UI keys, filled from base16 slots to preserve current rendering.
    ui = {
        global = {
            background = { normal = "#333c43" },
            foreground = { normal = "#d3c6aa" },
        },
        cursor = {
            background = { normal = "#d3c6aa" },
            foreground = { normal = "#333c43" },
        },
        gutter = { foreground = "#4d5960" },
        border = { normal = "#859289" },
        chrome = {
            background = {
                normal = "#4d5960",
                dark = "#3a464c",
            },
            foreground = {
                normal = "#d3c6aa",
                dark = "#9da9a0",
            },
        },
        selection = { background = "#3a464c" },
        highlight = {
            line = { background = "#3a464c" },
            text = { background = "#4d5960" },
            search = {
                background = "#3a464c",
                foreground = "#dbbc7f",
            },
        },
        status = {
            error = "#e67e80",
            warning = "#e69875",
            info = "#dbbc7f",
            success = "#a7c080",
        },
    },

    -- Syntax keys.
    syntax = {
        comment = "#859289",

        string = {
            default = "#a7c080",
            regexp = "#a7c080",
            other = "#a7c080",
        },

        constant = {
            default = "#e69875",
            character = {
                default = "#e67e80",
                escape = "#83c092",
            },
            language = "#e69875",
            numeric = {
                default = "#e69875",
                float = "#e69875",
            },
        },

        entity = {
            name = {
                class = "#dbbc7f",
                type = "#dbbc7f",
                ["function"] = {
                    default = "#7fbbb3",
                    constructor = "#7fbbb3",
                },
                label = "#dbbc7f",
                namespace = "#e67e80",
                tag = "#dbbc7f",
            },
            other = {
                ["attribute-name"] = "#dbbc7f",
            },
        },

        keyword = {
            default = "#d699b6",
            control = {
                default = "#d699b6",
                import = "#7fbbb3",
                flow = "#dbbc7f",
            },
            operator = "#d699b6",
            declaration = "#d699b6",
        },

        storage = {
            type = "#d699b6",
            modifier = "#dbbc7f",
        },

        variable = {
            default = "#d3c6aa",
            parameter = "#d3c6aa",
            other = {
                property = "#d3c6aa",
            },
        },

        punctuation = {
            separator = "#9da9a0",
            section = "#9da9a0",
        },

        markup = {
            default = "#d3c6aa",
            heading = "#7fbbb3",
            raw = "#e69875",
            link = "#e69875",
            list = "#dbbc7f",
            inserted = "#a7c080",
            deleted = "#e67e80",
        },

        meta = {
            preprocessor = "#dbbc7f",
        },
    },
}
