-- Auto-generated by tinted-builder-rust from a base24 scheme.
-- Translates base24 slots into tinted8-shaped keys. Mirrors base16.lua.mustache
-- exactly, plus brights from base12-17 and DiagnosticOk = bright_green.
-- Do not edit by hand.

return {
    variant = "light",

    -- Legacy base24 slot keys (kept for backwards compatibility).
    -- New consumers should read the tinted8-shaped keys below.
    base00 = "#f8fafe",
    base01 = "#edeef1",
    base02 = "#e4e5e7",
    base03 = "#b0a999",
    base04 = "#8d8a82",
    base05 = "#544d40",
    base06 = "#3b362d",
    base07 = "#000000",
    base08 = "#1faa9e",
    base09 = "#268da6",
    base0A = "#2e70ad",
    base0B = "#733d9a",
    base0C = "#bd4c3d",
    base0D = "#b55a0f",
    base0E = "#3e9d21",
    base0F = "#1b6374",
    base10 = "#f9fafe",
    base11 = "#f9fbfe",
    base12 = "#009e91",
    base13 = "#0f5ba2",
    base14 = "#5a1f8a",
    base15 = "#b32e1f",
    base16 = "#b23b00",
    base17 = "#218c00",

    palette = {
        black = {
            normal = "#f8fafe",
            bright = "#edeef1",
        },
        gray = {
            dim = "#e4e5e7",
            normal = "#b0a999",
            -- base04 ("Light Gray" per base16 spec) lives in gray.bright.
            bright = "#8d8a82",
        },
        white = {
            -- base06 ("Lighter White") occupies the white.dim slot — slot identifier,
            -- not a strict luminance semantic.
            dim = "#3b362d",
            normal = "#544d40",
            bright = "#000000",
        },
        red = { normal = "#1faa9e", bright = "#009e91" },
        -- base24 has no bright_orange slot; orange.bright falls back to .normal.
        orange = { normal = "#268da6", bright = "#268da6" },
        yellow = { normal = "#2e70ad", bright = "#0f5ba2" },
        green = { normal = "#733d9a", bright = "#5a1f8a" },
        cyan = { normal = "#bd4c3d", bright = "#b32e1f" },
        blue = { normal = "#b55a0f", bright = "#b23b00" },
        magenta = { normal = "#3e9d21", bright = "#218c00" },
        brown = { normal = "#1b6374" },
    },

    ui = {
        global = {
            background = { normal = "#f8fafe" },
            foreground = { normal = "#544d40" },
        },
        cursor = {
            background = { normal = "#544d40" },
            foreground = { normal = "#f8fafe" },
        },
        gutter = { foreground = "#e4e5e7" },
        border = { normal = "#b0a999" },
        chrome = {
            background = {
                normal = "#e4e5e7",
                dark = "#edeef1",
            },
            foreground = {
                normal = "#544d40",
                dark = "#8d8a82",
            },
        },
        selection = { background = "#edeef1" },
        highlight = {
            line = { background = "#edeef1" },
            text = { background = "#e4e5e7" },
            search = {
                background = "#edeef1",
                foreground = "#2e70ad",
            },
        },
        status = {
            error = "#1faa9e",
            warning = "#268da6",
            info = "#2e70ad",
            -- DiagnosticOk uses bright_green (base14) in current code; preserve.
            success = "#5a1f8a",
        },
    },

    syntax = {
        comment = "#b0a999",

        string = {
            default = "#733d9a",
            regexp = "#733d9a",
            other = "#733d9a",
        },

        constant = {
            default = "#268da6",
            character = {
                default = "#1faa9e",
                escape = "#bd4c3d",
            },
            language = "#268da6",
            numeric = {
                default = "#268da6",
                float = "#268da6",
            },
        },

        entity = {
            name = {
                class = "#2e70ad",
                type = "#2e70ad",
                ["function"] = {
                    default = "#b55a0f",
                    constructor = "#b55a0f",
                },
                label = "#2e70ad",
                namespace = "#1faa9e",
                tag = "#2e70ad",
            },
            other = {
                ["attribute-name"] = "#2e70ad",
            },
        },

        keyword = {
            default = "#3e9d21",
            control = {
                default = "#3e9d21",
                import = "#b55a0f",
                flow = "#2e70ad",
            },
            operator = "#3e9d21",
            declaration = "#3e9d21",
        },

        storage = {
            type = "#3e9d21",
            modifier = "#2e70ad",
        },

        variable = {
            default = "#544d40",
            parameter = "#544d40",
            other = {
                property = "#544d40",
            },
        },

        punctuation = {
            separator = "#1b6374",
            section = "#1b6374",
        },

        markup = {
            default = "#544d40",
            heading = "#b55a0f",
            raw = "#268da6",
            link = "#268da6",
            list = "#2e70ad",
            inserted = "#733d9a",
            deleted = "#1faa9e",
        },

        meta = {
            preprocessor = "#2e70ad",
        },
    },
}
