-- Auto-generated by tinted-builder-rust from a tinted8 scheme.
-- Do not edit by hand.

return {
    variant = "light",

    -- Named palette colors. Variants beyond what the scheme defines
    -- are generated by the tinted8 builder per its spec.
    palette = {
        black = {
            normal = "#1f2328",
            bright = "#393f46",
        },
        gray = {
            dim = "#3d454c",
            normal = "#59636e",
            bright = "#748190",
        },
        white = {
            dim = "#3d454c",
            normal = "#59636e",
            bright = "#818b98",
        },
        red = {
            normal = "#bc4c00",
            bright = "#953800",
        },
        orange = {
            normal = "#953800",
            bright = "#d24f00",
        },
        yellow = {
            normal = "#4d2d00",
            bright = "#633c01",
        },
        green = {
            normal = "#0550ae",
            bright = "#0969da",
        },
        cyan = {
            normal = "#1b7c83",
            bright = "#3192aa",
        },
        blue = {
            normal = "#0969da",
            bright = "#218bff",
        },
        magenta = {
            normal = "#8250df",
            bright = "#a475f9",
        },
        brown = { normal = "#000000" },
    },

    -- UI keys (tinted8 spec).
    ui = {
        global = {
            background = { normal = "#ffffff" },
            foreground = { normal = "#1f2328" },
        },
        cursor = {
            background = { normal = "#1f2328" },
            foreground = { normal = "#ffffff" },
        },
        gutter = { foreground = "#818b98" },
        border = { normal = "#d1d9e0" },
        chrome = {
            background = {
                normal = "#f6f8fa",
                dark = "#748190",
            },
            foreground = {
                normal = "#1f2328",
                dark = "#59636e",
            },
        },
        selection = { background = "#3d454c" },
        highlight = {
            line = { background = "#3d454c" },
            text = { background = "#3d454c" },
            search = {
                background = "#3d454c",
                foreground = "#4d2d00",
            },
        },
        status = {
            error = "#bc4c00",
            warning = "#9a6700",
            info = "#0969da",
            success = "#0969da",
        },
    },

    -- Syntax keys (tinted8 spec).
    -- Parent-with-children nodes use `default` for the parent's own color.
    syntax = {
        comment = "#59636e",

        string = {
            default = "#0a3069",
            regexp = "#0550ae",
            other = "#0a3069",
        },

        constant = {
            default = "#0550ae",
            character = {
                default = "#0550ae",
                escape = "#0550ae",
            },
            language = "#0550ae",
            numeric = {
                default = "#0550ae",
                float = "#0550ae",
            },
        },

        entity = {
            name = {
                class = "#4d2d00",
                type = "#1b7c83",
                ["function"] = {
                    default = "#6639ba",
                    constructor = "#6639ba",
                },
                label = "#1f2328",
                namespace = "#953800",
                tag = "#0550ae",
            },
            other = {
                ["attribute-name"] = "#8250df",
            },
        },

        keyword = {
            default = "#bc4c00",
            control = {
                default = "#bc4c00",
                import = "#1f2328",
                flow = "#bc4c00",
            },
            operator = "#bc4c00",
            declaration = "#bc4c00",
        },

        storage = {
            type = "#bc4c00",
            modifier = "#bc4c00",
        },

        variable = {
            default = "#953800",
            parameter = "#1f2328",
            other = {
                property = "#953800",
            },
        },

        punctuation = {
            separator = "#1f2328",
            section = "#1f2328",
        },

        markup = {
            default = "#953800",
            heading = "#0550ae",
            raw = "#953800",
            link = "#0a3069",
            list = "#3b2300",
            inserted = "#0550ae",
            deleted = "#762c00",
        },

        meta = {
            preprocessor = "#1f2328",
        },
    },
}
