-- Snapshot of highlight build output for base16-gruvbox-dark-medium.
-- Generated by tests/fixtures/snapshot_highlights.lua.
-- This is a parity baseline for the tinted8 migration; do not edit by hand.

return {
    ["@attribute"] = {
        ctermfg = 3,
        fg = "#fabd2f",
    },
    ["@boolean"] = {
        ctermfg = 16,
        fg = "#fe8019",
    },
    ["@character"] = {
        ctermfg = 1,
        fg = "#fb4934",
    },
    ["@character.special"] = {
        ctermfg = 17,
        fg = "#d65d0e",
    },
    ["@class"] = {
        link = "Type",
    },
    ["@comment"] = {
        link = "Comment",
    },
    ["@comment.error"] = {
        link = "DiagnosticError",
    },
    ["@comment.note"] = {
        link = "DiagnosticInfo",
    },
    ["@comment.todo"] = {
        link = "Todo",
    },
    ["@comment.warning"] = {
        link = "DiagnosticWarn",
    },
    ["@conditional"] = {
        ctermfg = 5,
        fg = "#d3869b",
    },
    ["@constant"] = {
        ctermfg = 16,
        fg = "#fe8019",
    },
    ["@constant.builtin"] = {
        link = "@constant",
    },
    ["@constant.macro"] = {
        link = "@constant",
    },
    ["@constructor"] = {
        ctermfg = 4,
        fg = "#83a598",
    },
    ["@decorator"] = {
        link = "Identifier",
    },
    ["@define"] = {
        ctermfg = 5,
        fg = "#d3869b",
    },
    ["@enum"] = {
        link = "Type",
    },
    ["@enumMember"] = {
        link = "Constant",
    },
    ["@error"] = {
        ctermfg = 1,
        fg = "#fb4934",
    },
    ["@event"] = {
        link = "Identifier",
    },
    ["@exception"] = {
        ctermfg = 1,
        fg = "#fb4934",
    },
    ["@field"] = {
        ctermfg = 7,
        fg = "#d5c4a1",
    },
    ["@float"] = {
        ctermfg = 16,
        fg = "#fe8019",
    },
    ["@function"] = {
        link = "Function",
    },
    ["@function.builtin"] = {
        link = "@function",
    },
    ["@function.call"] = {
        link = "@function",
    },
    ["@function.macro"] = {
        ctermfg = 1,
        fg = "#fb4934",
    },
    ["@include"] = {
        ctermfg = 4,
        fg = "#83a598",
    },
    ["@interface"] = {
        link = "Structure",
    },
    ["@keyword"] = {
        link = "Keyword",
    },
    ["@keyword.exception"] = {
        link = "@keyword",
    },
    ["@keyword.function"] = {
        link = "@keyword",
    },
    ["@keyword.import"] = {
        link = "@include",
    },
    ["@keyword.operator"] = {
        link = "@keyword",
    },
    ["@keyword.return"] = {
        link = "@keyword",
    },
    ["@label"] = {
        ctermfg = 3,
        fg = "#fabd2f",
    },
    ["@lsp.mod.readonly"] = {
        link = "@constant",
    },
    ["@lsp.mod.typeHint"] = {
        link = "@type",
    },
    ["@lsp.type.bitwise"] = {
        link = "@operator",
    },
    ["@lsp.type.builtinConstant"] = {
        link = "@constant.builtin",
    },
    ["@lsp.type.class"] = {
        link = "@type",
    },
    ["@lsp.type.comment"] = {
        link = "@comment",
    },
    ["@lsp.type.comparison"] = {
        link = "@operator",
    },
    ["@lsp.type.const"] = {
        link = "@constant",
    },
    ["@lsp.type.decorator"] = {
        link = "@function",
    },
    ["@lsp.type.decorator.rust"] = {
        link = "PreProc",
    },
    ["@lsp.type.enum"] = {
        link = "@type",
    },
    ["@lsp.type.enumMember"] = {
        link = "@constant",
    },
    ["@lsp.type.function"] = {
        link = "@function",
    },
    ["@lsp.type.interface"] = {
        link = "@type",
    },
    ["@lsp.type.lifetime"] = {
        link = "@operator",
    },
    ["@lsp.type.macro"] = {
        link = "@function.macro",
    },
    ["@lsp.type.magicFunction"] = {
        link = "@function.builtin",
    },
    ["@lsp.type.method"] = {
        link = "@method",
    },
    ["@lsp.type.namespace"] = {
        link = "@namespace",
    },
    ["@lsp.type.parameter"] = {
        link = "@parameter",
    },
    ["@lsp.type.property"] = {
        link = "@property",
    },
    ["@lsp.type.punctuation"] = {
        link = "@punctuation.delimiter",
    },
    ["@lsp.type.selfParameter"] = {
        link = "@variable.builtin",
    },
    ["@lsp.type.struct"] = {
        link = "@type",
    },
    ["@lsp.type.type"] = {
        link = "@type",
    },
    ["@lsp.type.variable"] = {
        link = "@variable",
    },
    ["@lsp.typemod.function.builtin"] = {
        link = "@function.builtin",
    },
    ["@lsp.typemod.function.defaultLibrary"] = {
        link = "@function.builtin",
    },
    ["@lsp.typemod.function.readonly"] = {
        link = "@function",
    },
    ["@lsp.typemod.keyword.documentation"] = {
        link = "@comment",
    },
    ["@lsp.typemod.method.defaultLibrary"] = {
        link = "@function.builtin",
    },
    ["@lsp.typemod.operator.controlFlow"] = {
        link = "@keyword.exception",
    },
    ["@lsp.typemod.variable.defaultLibrary"] = {
        link = "Special",
    },
    ["@lsp.typemod.variable.global"] = {
        link = "@constant",
    },
    ["@lsp.typemod.variable.injected"] = {
        link = "@variable",
    },
    ["@lsp.typemod.variable.static"] = {
        link = "@constant",
    },
    ["@markup"] = {
        ctermfg = 7,
        fg = "#d5c4a1",
    },
    ["@markup.danger"] = {
        ctermfg = 1,
        fg = "#fb4934",
    },
    ["@markup.emphasis"] = {
        italic = true,
    },
    ["@markup.environment"] = {
        link = "@keyword",
    },
    ["@markup.heading"] = {
        ctermfg = 4,
        fg = "#83a598",
    },
    ["@markup.heading.1"] = {
        link = "@markup.heading",
    },
    ["@markup.heading.2"] = {
        link = "@markup.heading",
    },
    ["@markup.heading.3"] = {
        link = "@markup.heading",
    },
    ["@markup.heading.4"] = {
        link = "@markup.heading",
    },
    ["@markup.heading.5"] = {
        link = "@markup.heading",
    },
    ["@markup.heading.6"] = {
        link = "@markup.heading",
    },
    ["@markup.link"] = {
        link = "@markup.link.url",
    },
    ["@markup.link.label"] = {
        link = "@markup.link.url",
    },
    ["@markup.link.url"] = {
        ctermfg = 16,
        fg = "#fe8019",
        underline = true,
    },
    ["@markup.list"] = {
        ctermfg = 3,
        fg = "#fabd2f",
    },
    ["@markup.math"] = {
        link = "@constant",
    },
    ["@markup.quote"] = {
        link = "@comment",
    },
    ["@markup.raw"] = {
        ctermfg = 16,
        fg = "#fe8019",
    },
    ["@markup.raw.block"] = {
        link = "@markup.raw",
    },
    ["@markup.strikethrough"] = {
        strikethrough = true,
    },
    ["@markup.strong"] = {
        bold = true,
    },
    ["@markup.todo"] = {
        ctermfg = 3,
        fg = "#fabd2f",
    },
    ["@markup.underline"] = {
        underline = true,
    },
    ["@markup.warning"] = {
        ctermfg = 16,
        fg = "#fe8019",
    },
    ["@method"] = {
        ctermfg = 4,
        fg = "#83a598",
    },
    ["@method.call"] = {
        link = "@method",
    },
    ["@modifier"] = {
        link = "Identifier",
    },
    ["@module"] = {
        link = "@namespace",
    },
    ["@module.builtin"] = {
        link = "@namespace",
    },
    ["@namespace"] = {
        ctermfg = 1,
        fg = "#fb4934",
    },
    ["@none"] = {
        ctermfg = 7,
        fg = "#d5c4a1",
    },
    ["@number"] = {
        ctermfg = 16,
        fg = "#fe8019",
    },
    ["@operator"] = {
        ctermfg = 7,
        fg = "#d5c4a1",
    },
    ["@parameter"] = {
        ctermfg = 7,
        fg = "#d5c4a1",
    },
    ["@preproc"] = {
        ctermfg = 3,
        fg = "#fabd2f",
    },
    ["@property"] = {
        ctermfg = 7,
        fg = "#d5c4a1",
    },
    ["@punctuation.bracket"] = {
        ctermfg = 7,
        fg = "#d5c4a1",
    },
    ["@punctuation.delimiter"] = {
        ctermfg = 17,
        fg = "#d65d0e",
    },
    ["@punctuation.special"] = {
        ctermfg = 17,
        fg = "#d65d0e",
    },
    ["@regexp"] = {
        link = "@string.regex",
    },
    ["@repeat"] = {
        ctermfg = 5,
        fg = "#d3869b",
    },
    ["@storageclass"] = {
        ctermfg = 3,
        fg = "#fabd2f",
    },
    ["@string"] = {
        ctermfg = 2,
        fg = "#b8bb26",
    },
    ["@string.escape"] = {
        ctermfg = 6,
        fg = "#8ec07c",
    },
    ["@string.regex"] = {
        ctermfg = 2,
        fg = "#b8bb26",
    },
    ["@string.special"] = {
        ctermfg = 2,
        fg = "#b8bb26",
    },
    ["@string.special.symbol"] = {
        link = "@symbol",
    },
    ["@string.special.url"] = {
        link = "@markup.link.url",
    },
    ["@struct"] = {
        link = "Type",
    },
    ["@symbol"] = {
        ctermfg = 2,
        fg = "#b8bb26",
    },
    ["@type"] = {
        link = "Type",
    },
    ["@type.builtin"] = {
        link = "@type",
    },
    ["@type.definition"] = {
        link = "@type",
    },
    ["@type.qualifier"] = {
        link = "@keyword",
    },
    ["@typeParameter"] = {
        link = "Type",
    },
    ["@variable"] = {
        ctermfg = 7,
        fg = "#d5c4a1",
    },
    ["@variable.builtin"] = {
        ctermfg = 7,
        fg = "#d5c4a1",
        italic = true,
    },
    ["@variable.member"] = {
        link = "@field",
    },
    ["@variable.parameter"] = {
        link = "@parameter",
    },
    BlinkCmpKindClass = {
        ctermfg = 3,
        fg = "#fabd2f",
    },
    BlinkCmpKindColor = {
        ctermfg = 1,
        fg = "#fb4934",
    },
    BlinkCmpKindConstant = {
        ctermfg = 16,
        fg = "#fe8019",
    },
    BlinkCmpKindConstructor = {
        ctermfg = 4,
        fg = "#83a598",
    },
    BlinkCmpKindCopilot = {
        ctermfg = 6,
        fg = "#8ec07c",
    },
    BlinkCmpKindEnum = {
        ctermfg = 3,
        fg = "#fabd2f",
    },
    BlinkCmpKindEnumMember = {
        ctermfg = 6,
        fg = "#8ec07c",
    },
    BlinkCmpKindEvent = {
        ctermfg = 4,
        fg = "#83a598",
    },
    BlinkCmpKindField = {
        ctermfg = 2,
        fg = "#b8bb26",
    },
    BlinkCmpKindFile = {
        ctermfg = 4,
        fg = "#83a598",
    },
    BlinkCmpKindFolder = {
        ctermfg = 4,
        fg = "#83a598",
    },
    BlinkCmpKindFunction = {
        ctermfg = 4,
        fg = "#83a598",
    },
    BlinkCmpKindInterface = {
        ctermfg = 3,
        fg = "#fabd2f",
    },
    BlinkCmpKindKeyword = {
        ctermfg = 5,
        fg = "#d3869b",
    },
    BlinkCmpKindMethod = {
        ctermfg = 4,
        fg = "#83a598",
    },
    BlinkCmpKindModule = {
        ctermfg = 4,
        fg = "#83a598",
    },
    BlinkCmpKindOperator = {
        ctermfg = 5,
        fg = "#d3869b",
    },
    BlinkCmpKindProperty = {
        ctermfg = 4,
        fg = "#83a598",
    },
    BlinkCmpKindReference = {
        ctermfg = 1,
        fg = "#fb4934",
    },
    BlinkCmpKindSnippet = {
        ctermfg = 17,
        fg = "#d65d0e",
    },
    BlinkCmpKindStruct = {
        ctermfg = 4,
        fg = "#83a598",
    },
    BlinkCmpKindText = {
        ctermfg = 2,
        fg = "#b8bb26",
    },
    BlinkCmpKindTypeParameter = {
        ctermfg = 17,
        fg = "#d65d0e",
    },
    BlinkCmpKindUnit = {
        ctermfg = 2,
        fg = "#b8bb26",
    },
    BlinkCmpKindValue = {
        ctermfg = 16,
        fg = "#fe8019",
    },
    BlinkCmpKindVariable = {
        ctermfg = 17,
        fg = "#d65d0e",
    },
    BlinkCmpLabel = {
        ctermfg = 20,
        fg = "#bdae93",
    },
    BlinkCmpLabelDescription = {
        link = "PmenuExtra",
    },
    BlinkCmpLabelDetail = {
        link = "PmenuExtra",
    },
    BlinkCmpLabelMatch = {
        ctermfg = 4,
        fg = "#83a598",
    },
    BlinkCmpMenu = {
        link = "Pmenu",
    },
    BlinkCmpMenuBorder = {
        link = "FloatBorder",
    },
    BlinkCmpMenuSelection = {
        link = "PmenuSel",
    },
    BlinkCmpSource = {
        ctermfg = 19,
        fg = "#504945",
    },
    Boolean = {
        ctermfg = 16,
        fg = "#fe8019",
    },
    Character = {
        ctermfg = 1,
        fg = "#fb4934",
    },
    CmpDocumentation = {
        ctermfg = 7,
        fg = "#d5c4a1",
    },
    CmpDocumentationBorder = {
        link = "FloatBorder",
    },
    CmpItemAbbr = {
        bg = "#3c3836",
        ctermbg = 18,
        ctermfg = 7,
        fg = "#d5c4a1",
    },
    CmpItemAbbrDeprecated = {
        ctermfg = 8,
        fg = "#665c54",
        strikethrough = true,
    },
    CmpItemAbbrMatch = {
        ctermfg = 4,
        fg = "#83a598",
    },
    CmpItemAbbrMatchFuzzy = {
        ctermfg = 4,
        fg = "#83a598",
    },
    CmpItemKindClass = {
        ctermfg = 3,
        fg = "#fabd2f",
    },
    CmpItemKindConstant = {
        ctermfg = 16,
        fg = "#fe8019",
    },
    CmpItemKindConstructor = {
        ctermfg = 4,
        fg = "#83a598",
    },
    CmpItemKindDefault = {
        ctermfg = 7,
        fg = "#d5c4a1",
    },
    CmpItemKindEnum = {
        ctermfg = 3,
        fg = "#fabd2f",
    },
    CmpItemKindEnumMember = {
        ctermfg = 3,
        fg = "#fabd2f",
    },
    CmpItemKindEvent = {
        ctermfg = 3,
        fg = "#fabd2f",
    },
    CmpItemKindField = {
        ctermfg = 1,
        fg = "#fb4934",
    },
    CmpItemKindFunction = {
        ctermfg = 4,
        fg = "#83a598",
    },
    CmpItemKindInterface = {
        ctermfg = 3,
        fg = "#fabd2f",
    },
    CmpItemKindKeyword = {
        ctermfg = 5,
        fg = "#d3869b",
    },
    CmpItemKindMethod = {
        ctermfg = 4,
        fg = "#83a598",
    },
    CmpItemKindModule = {
        ctermfg = 7,
        fg = "#d5c4a1",
    },
    CmpItemKindOperator = {
        ctermfg = 7,
        fg = "#d5c4a1",
    },
    CmpItemKindProperty = {
        ctermfg = 1,
        fg = "#fb4934",
    },
    CmpItemKindReference = {
        ctermfg = 1,
        fg = "#fb4934",
    },
    CmpItemKindSnippet = {
        ctermfg = 20,
        fg = "#bdae93",
    },
    CmpItemKindStruct = {
        ctermfg = 3,
        fg = "#fabd2f",
    },
    CmpItemKindTypeParameter = {
        ctermfg = 3,
        fg = "#fabd2f",
    },
    CmpItemKindUnit = {
        ctermfg = 3,
        fg = "#fabd2f",
    },
    CmpItemKindValue = {
        ctermfg = 16,
        fg = "#fe8019",
    },
    CmpItemKindVariable = {
        ctermfg = 1,
        fg = "#fb4934",
    },
    CmpItemMenu = {
        ctermfg = 20,
        fg = "#bdae93",
    },
    ColorColumn = {
        bg = "#3c3836",
        ctermbg = 18,
    },
    Comment = {
        ctermfg = 8,
        fg = "#665c54",
    },
    Conceal = {
        ctermfg = 4,
        fg = "#83a598",
    },
    Conditional = {
        ctermfg = 5,
        fg = "#d3869b",
    },
    Constant = {
        ctermfg = 16,
        fg = "#fe8019",
    },
    CurSearch = {
        link = "Search",
    },
    Cursor = {
        bg = "#d5c4a1",
        ctermbg = 7,
        ctermfg = 0,
        fg = "#282828",
    },
    CursorColumn = {
        link = "CursorLine",
    },
    CursorIM = {
        link = "Cursor",
    },
    CursorLine = {
        bg = "#302e2e",
    },
    CursorLineNr = {
        link = "LineNr",
    },
    DapUIBreakpointsCurrentLine = {
        bold = true,
        ctermfg = 2,
        fg = "#b8bb26",
    },
    DapUIBreakpointsDisabledLine = {
        ctermfg = 19,
        fg = "#504945",
    },
    DapUIBreakpointsInfo = {
        ctermfg = 2,
        fg = "#b8bb26",
    },
    DapUIBreakpointsLine = {
        link = "DapUILineNumber",
    },
    DapUIBreakpointsPath = {
        ctermfg = 4,
        fg = "#83a598",
    },
    DapUICurrentFrameName = {
        link = "DapUIBreakpointsCurrentLine",
    },
    DapUIDecoration = {
        ctermfg = 4,
        fg = "#83a598",
    },
    DapUIEndofBuffer = {
        link = "EndOfBuffer",
    },
    DapUIFloatBorder = {
        link = "FloatBorder",
    },
    DapUIFloatNormal = {
        link = "NormalFloat",
    },
    DapUIFrameName = {
        link = "Normal",
    },
    DapUILineNumber = {
        ctermfg = 4,
        fg = "#83a598",
    },
    DapUIModifiedValue = {
        bold = true,
        ctermfg = 4,
        fg = "#83a598",
    },
    DapUINormal = {
        link = "Normal",
    },
    DapUINormalNC = {
        link = "Normal",
    },
    DapUIPlayPause = {
        ctermfg = 2,
        fg = "#b8bb26",
    },
    DapUIPlayPauseNC = {
        ctermfg = 2,
        fg = "#b8bb26",
    },
    DapUIRestart = {
        ctermfg = 2,
        fg = "#b8bb26",
    },
    DapUIRestartNC = {
        ctermfg = 2,
        fg = "#b8bb26",
    },
    DapUIScope = {
        ctermfg = 4,
        fg = "#83a598",
    },
    DapUISource = {
        ctermfg = 5,
        fg = "#d3869b",
    },
    DapUIStepBack = {
        ctermfg = 4,
        fg = "#83a598",
    },
    DapUIStepBackNC = {
        ctermfg = 4,
        fg = "#83a598",
    },
    DapUIStepInto = {
        ctermfg = 4,
        fg = "#83a598",
    },
    DapUIStepIntoNC = {
        ctermfg = 4,
        fg = "#83a598",
    },
    DapUIStepOut = {
        ctermfg = 4,
        fg = "#83a598",
    },
    DapUIStepOutNC = {
        ctermfg = 4,
        fg = "#83a598",
    },
    DapUIStepOver = {
        ctermfg = 4,
        fg = "#83a598",
    },
    DapUIStepOverNC = {
        ctermfg = 4,
        fg = "#83a598",
    },
    DapUIStop = {
        ctermfg = 1,
        fg = "#fb4934",
    },
    DapUIStopNC = {
        ctermfg = 1,
        fg = "#fb4934",
    },
    DapUIStoppedThread = {
        ctermfg = 4,
        fg = "#83a598",
    },
    DapUIThread = {
        ctermfg = 2,
        fg = "#b8bb26",
    },
    DapUIType = {
        ctermfg = 5,
        fg = "#d3869b",
    },
    DapUIUnavailable = {
        ctermfg = 19,
        fg = "#504945",
    },
    DapUIUnavailableNC = {
        ctermfg = 19,
        fg = "#504945",
    },
    DapUIValue = {
        link = "Normal",
    },
    DapUIVariable = {
        link = "Normal",
    },
    DapUIWatchesEmpty = {
        ctermfg = 1,
        fg = "#fb4934",
    },
    DapUIWatchesError = {
        ctermfg = 1,
        fg = "#fb4934",
    },
    DapUIWatchesValue = {
        ctermfg = 2,
        fg = "#b8bb26",
    },
    DapUIWinSelect = {
        bold = true,
        ctermfg = 4,
        fg = "#83a598",
    },
    Debug = {
        ctermfg = 1,
        fg = "#fb4934",
    },
    Define = {
        ctermfg = 5,
        fg = "#d3869b",
    },
    Delimiter = {
        ctermfg = 17,
        fg = "#d65d0e",
    },
    DiagnosticError = {
        ctermfg = 1,
        fg = "#fb4934",
    },
    DiagnosticFloatingError = {
        link = "DiagnosticError",
    },
    DiagnosticFloatingHint = {
        link = "DiagnosticHint",
    },
    DiagnosticFloatingInfo = {
        link = "DiagnosticInfo",
    },
    DiagnosticFloatingOk = {
        link = "DiagnosticOk",
    },
    DiagnosticFloatingWarn = {
        link = "DiagnosticWarn",
    },
    DiagnosticHint = {
        ctermfg = 4,
        fg = "#83a598",
    },
    DiagnosticInfo = {
        ctermfg = 3,
        fg = "#fabd2f",
    },
    DiagnosticOk = {
        ctermfg = 2,
        fg = "#b8bb26",
    },
    DiagnosticSignError = {
        link = "DiagnosticError",
    },
    DiagnosticSignHint = {
        link = "DiagnosticHint",
    },
    DiagnosticSignInfo = {
        link = "DiagnosticInfo",
    },
    DiagnosticSignOk = {
        link = "DiagnosticOk",
    },
    DiagnosticSignWarn = {
        link = "DiagnosticWarn",
    },
    DiagnosticUnderlineError = {
        sp = "#fb4934",
        undercurl = true,
        underline = false,
    },
    DiagnosticUnderlineHint = {
        sp = "#83a598",
        undercurl = true,
        underline = false,
    },
    DiagnosticUnderlineInfo = {
        sp = "#fabd2f",
        undercurl = true,
        underline = false,
    },
    DiagnosticUnderlineOk = {
        sp = "#b8bb26",
        undercurl = true,
        underline = false,
    },
    DiagnosticUnderlineWarn = {
        sp = "#fe8019",
        undercurl = true,
        underline = false,
    },
    DiagnosticVirtualTextError = {
        link = "DiagnosticError",
    },
    DiagnosticVirtualTextHint = {
        link = "DiagnosticHint",
    },
    DiagnosticVirtualTextInfo = {
        link = "DiagnosticInfo",
    },
    DiagnosticVirtualTextOk = {
        link = "DiagnosticOk",
    },
    DiagnosticVirtualTextWarn = {
        link = "DiagnosticWarn",
    },
    DiagnosticWarn = {
        ctermfg = 16,
        fg = "#fe8019",
    },
    DiffAdd = {
        bg = "#5f736b",
        ctermfg = 0,
        fg = "#282828",
    },
    DiffChange = {
        link = "Cursorline",
    },
    DiffDelete = {
        link = "NonText",
    },
    DiffText = {
        link = "DiffAdd",
    },
    Directory = {
        ctermfg = 4,
        fg = "#83a598",
    },
    EndOfBuffer = {
        link = "NonText",
    },
    Error = {
        ctermfg = 1,
        fg = "#fb4934",
    },
    ErrorMsg = {
        ctermfg = 1,
        fg = "#fb4934",
    },
    Exception = {
        ctermfg = 1,
        fg = "#fb4934",
    },
    Float = {
        ctermfg = 16,
        fg = "#fe8019",
    },
    FloatBorder = {
        ctermfg = 8,
        fg = "#665c54",
    },
    FloatFooter = {
        link = "NonText",
    },
    FloatTitle = {
        link = "Title",
    },
    FoldColumn = {
        link = "LineNr",
    },
    Folded = {
        ctermfg = 8,
        fg = "#665c54",
    },
    Function = {
        ctermfg = 4,
        fg = "#83a598",
    },
    Identifier = {
        ctermfg = 1,
        fg = "#fb4934",
    },
    Ignore = {
        link = "NonText",
    },
    IncSearch = {
        bg = "#fe8019",
        ctermbg = 16,
        ctermfg = 18,
        fg = "#3c3836",
    },
    Include = {
        ctermfg = 4,
        fg = "#83a598",
    },
    Keyword = {
        ctermfg = 5,
        fg = "#d3869b",
    },
    Label = {
        ctermfg = 3,
        fg = "#fabd2f",
    },
    LineNr = {
        ctermfg = 19,
        fg = "#504945",
    },
    LineNrAbove = {
        link = "LineNr",
    },
    LineNrBelow = {
        link = "LineNr",
    },
    LspCodeLens = {
        link = "Comment",
    },
    LspInlayHint = {
        link = "Comment",
    },
    LspReferenceRead = {
        link = "LspReferenceText",
    },
    LspReferenceText = {
        bg = "#504945",
        ctermbg = 19,
    },
    LspReferenceWrite = {
        link = "LspReferenceText",
    },
    LspSignatureActiveParameter = {
        link = "LspReferenceText",
    },
    LualineCommandA = {
        bg = "#b8bb26",
        bold = true,
        ctermbg = 2,
        ctermfg = 0,
        fg = "#282828",
    },
    LualineCommandB = {
        bg = "#504945",
        ctermbg = 19,
        ctermfg = 7,
        fg = "#d5c4a1",
    },
    LualineCommandC = {
        bg = "#3c3836",
        ctermbg = 18,
        ctermfg = 7,
        fg = "#d5c4a1",
    },
    LualineInactiveA = {
        bg = "#3c3836",
        bold = true,
        ctermbg = 18,
        ctermfg = 8,
        fg = "#665c54",
    },
    LualineInactiveB = {
        bg = "#3c3836",
        ctermbg = 18,
        ctermfg = 8,
        fg = "#665c54",
    },
    LualineInactiveC = {
        bg = "#3c3836",
        ctermbg = 18,
        ctermfg = 8,
        fg = "#665c54",
    },
    LualineInsertA = {
        bg = "#83a598",
        bold = true,
        ctermbg = 4,
        ctermfg = 0,
        fg = "#282828",
    },
    LualineInsertB = {
        bg = "#504945",
        ctermbg = 19,
        ctermfg = 7,
        fg = "#d5c4a1",
    },
    LualineInsertC = {
        bg = "#3c3836",
        ctermbg = 18,
        ctermfg = 7,
        fg = "#d5c4a1",
    },
    LualineNormalA = {
        bg = "#665c54",
        bold = true,
        ctermbg = 8,
        ctermfg = 0,
        fg = "#282828",
    },
    LualineNormalB = {
        bg = "#504945",
        ctermbg = 19,
        ctermfg = 7,
        fg = "#d5c4a1",
    },
    LualineNormalC = {
        bg = "#3c3836",
        ctermbg = 18,
        ctermfg = 20,
        fg = "#bdae93",
    },
    LualineReplaceA = {
        bg = "#fb4934",
        bold = true,
        ctermbg = 1,
        ctermfg = 0,
        fg = "#282828",
    },
    LualineReplaceB = {
        bg = "#504945",
        ctermbg = 19,
        ctermfg = 7,
        fg = "#d5c4a1",
    },
    LualineReplaceC = {
        bg = "#3c3836",
        ctermbg = 18,
        ctermfg = 7,
        fg = "#d5c4a1",
    },
    LualineVisualA = {
        bg = "#fabd2f",
        bold = true,
        ctermbg = 3,
        ctermfg = 0,
        fg = "#282828",
    },
    LualineVisualB = {
        bg = "#504945",
        ctermbg = 19,
        ctermfg = 7,
        fg = "#d5c4a1",
    },
    LualineVisualC = {
        bg = "#3c3836",
        ctermbg = 18,
        ctermfg = 7,
        fg = "#d5c4a1",
    },
    MatchParen = {
        bg = "#504945",
        ctermbg = 19,
    },
    ModeMsg = {
        ctermfg = 2,
        fg = "#b8bb26",
    },
    MoreMsg = {
        ctermfg = 2,
        fg = "#b8bb26",
    },
    MsgArea = {
        ctermfg = 7,
        fg = "#d5c4a1",
    },
    MsgSeparator = {
        ctermfg = 20,
        fg = "#bdae93",
    },
    NonText = {
        ctermfg = 18,
        fg = "#3c3836",
    },
    Normal = {
        bg = "#282828",
        ctermbg = 0,
        ctermfg = 7,
        fg = "#d5c4a1",
    },
    NormalFloat = {
        link = "Normal",
    },
    NormalNC = {
        link = "Normal",
    },
    NotifyDEBUGBody = {
        link = "Normal",
    },
    NotifyDEBUGBorder = {
        ctermfg = 6,
        fg = "#8ec07c",
    },
    NotifyDEBUGIcon = {
        link = "NotifyDEBUGBorder",
    },
    NotifyDEBUGTitle = {
        link = "NotifyDEBUGBorder",
    },
    NotifyERRORBody = {
        link = "Normal",
    },
    NotifyERRORBorder = {
        ctermfg = 1,
        fg = "#fb4934",
    },
    NotifyERRORIcon = {
        link = "NotifyERRORBorder",
    },
    NotifyERRORTitle = {
        link = "NotifyERRORBorder",
    },
    NotifyINFOBody = {
        link = "Normal",
    },
    NotifyINFOBorder = {
        ctermfg = 7,
        fg = "#d5c4a1",
    },
    NotifyINFOIcon = {
        link = "NotifyINFOBorder",
    },
    NotifyINFOTitle = {
        link = "NotifyINFOBorder",
    },
    NotifyTRACEBody = {
        link = "Normal",
    },
    NotifyTRACEBorder = {
        ctermfg = 6,
        fg = "#8ec07c",
    },
    NotifyTRACEIcon = {
        link = "NotifyTRACEBorder",
    },
    NotifyTRACETitle = {
        link = "NotifyTRACEBorder",
    },
    NotifyWARNBody = {
        link = "Normal",
    },
    NotifyWARNBorder = {
        ctermfg = 5,
        fg = "#d3869b",
    },
    NotifyWARNIcon = {
        link = "NotifyWARNBorder",
    },
    NotifyWARNTitle = {
        link = "NotifyWARNBorder",
    },
    Number = {
        ctermfg = 16,
        fg = "#fe8019",
    },
    Operator = {
        ctermfg = 5,
        fg = "#d3869b",
    },
    Pmenu = {
        bg = "#282828",
        ctermbg = 0,
    },
    PmenuBorder = {
        link = "FloatBorder",
    },
    PmenuExtra = {
        link = "Pmenu",
    },
    PmenuExtraSel = {
        link = "PmenuSel",
    },
    PmenuKind = {
        link = "Pmenu",
    },
    PmenuKindSel = {
        link = "PmenuSel",
    },
    PmenuSbar = {
        bg = "#504945",
        ctermbg = 19,
    },
    PmenuSel = {
        bg = "#3c3836",
        ctermbg = 18,
    },
    PmenuThumb = {
        bg = "#504945",
        ctermbg = 19,
    },
    PreProc = {
        ctermfg = 3,
        fg = "#fabd2f",
    },
    Question = {
        ctermfg = 4,
        fg = "#83a598",
    },
    QuickFixLine = {
        bg = "#504945",
        ctermbg = 19,
    },
    Repeat = {
        ctermfg = 3,
        fg = "#fabd2f",
    },
    Search = {
        bg = "#fabd2f",
        ctermbg = 3,
        ctermfg = 18,
        fg = "#3c3836",
    },
    SignColumn = {
        ctermfg = 20,
        fg = "#bdae93",
    },
    Special = {
        ctermfg = 6,
        fg = "#8ec07c",
    },
    SpecialChar = {
        ctermfg = 17,
        fg = "#d65d0e",
    },
    SpecialKey = {
        ctermfg = 8,
        fg = "#665c54",
    },
    SpellBad = {
        sp = "#fb4934",
        undercurl = true,
        underline = false,
    },
    SpellCap = {
        sp = "#fe8019",
        undercurl = true,
        underline = false,
    },
    SpellLocal = {
        sp = "#fe8019",
        undercurl = true,
        underline = false,
    },
    SpellRare = {
        sp = "#fe8019",
        undercurl = true,
        underline = false,
    },
    Statement = {
        ctermfg = 1,
        fg = "#fb4934",
    },
    StatusLine = {
        bg = "#504945",
        ctermbg = 19,
        ctermfg = 7,
        fg = "#d5c4a1",
    },
    StatusLineNC = {
        link = "StatusLine",
    },
    StorageClass = {
        ctermfg = 3,
        fg = "#fabd2f",
    },
    String = {
        ctermfg = 2,
        fg = "#b8bb26",
    },
    Structure = {
        ctermfg = 5,
        fg = "#d3869b",
    },
    Substitute = {
        bg = "#fabd2f",
        ctermbg = 3,
        ctermfg = 18,
        fg = "#3c3836",
    },
    TabLine = {
        bg = "#3c3836",
        ctermbg = 18,
        ctermfg = 20,
        fg = "#bdae93",
    },
    TabLineSel = {
        bg = "#3c3836",
        ctermbg = 18,
        ctermfg = 2,
        fg = "#b8bb26",
    },
    Tag = {
        ctermfg = 3,
        fg = "#fabd2f",
    },
    TelescopeBorder = {
        link = "FloatBorder",
    },
    TelescopeMatching = {
        ctermfg = 4,
        fg = "#83a598",
    },
    TelescopeNormal = {
        link = "Normal",
    },
    TelescopePreviewLine = {
        link = "Visual",
    },
    TelescopeSelection = {
        link = "Visual",
    },
    TelescopeSelectionCaret = {
        ctermfg = 17,
        fg = "#d65d0e",
    },
    TelescopeTitle = {
        ctermfg = 4,
        fg = "#83a598",
    },
    TermCursor = {
        link = "Cursor",
    },
    TermCursorNC = {
        link = "Cursor",
    },
    Title = {
        ctermfg = 4,
        fg = "#83a598",
    },
    Todo = {
        bg = "#3c3836",
        ctermbg = 18,
        ctermfg = 3,
        fg = "#fabd2f",
    },
    Type = {
        ctermfg = 3,
        fg = "#fabd2f",
    },
    Typedef = {
        ctermfg = 3,
        fg = "#fabd2f",
    },
    Underlined = {
        ctermfg = 1,
        fg = "#fb4934",
    },
    VertSplit = {
        link = "WinSeparator",
    },
    Visual = {
        bg = "#3c3836",
        ctermbg = 18,
    },
    WarningMsg = {
        ctermfg = 1,
        fg = "#fb4934",
    },
    Whitespace = {
        link = "NonText",
    },
    WildMenu = {
        bg = "#fabd2f",
        ctermbg = 3,
        ctermfg = 1,
        fg = "#fb4934",
    },
    WinBar = {
        ctermfg = 7,
        fg = "#d5c4a1",
    },
    WinBarNC = {
        ctermfg = 20,
        fg = "#bdae93",
    },
    WinSeparator = {
        ctermfg = 19,
        fg = "#504945",
    },
    debugBreakpoint = {
        bg = "#504945",
        ctermbg = 19,
        ctermfg = 1,
        fg = "#fb4934",
    },
    debugPC = {
        bg = "#504945",
        ctermbg = 19,
    },
    lCursor = {
        link = "Cursor",
    },
}
