base16.lua:
  filename: lua/tinted-nvim/palettes/{{ scheme-system }}-{{ scheme-slug }}.lua
  supported-systems: [base16]

base16.vim:
  filename: colors/{{ scheme-system }}-{{ scheme-slug }}.vim
  supported-systems: [base16]

base24.lua:
  filename: lua/tinted-nvim/palettes/{{ scheme-system }}-{{ scheme-slug }}.lua
  supported-systems: [base24]

base24.vim:
  filename: colors/{{ scheme-system }}-{{ scheme-slug }}.vim
  supported-systems: [base24]

tinted8.lua:
  filename: lua/tinted-nvim/palettes/{{ scheme.system }}-{{ scheme.slug }}.lua
  supported-systems: [tinted8]
  supports:
    tinted8-builder: "~0.2.0"
    tinted8-styling: "~0.2.0"

tinted8.vim:
  filename: colors/{{ scheme.system }}-{{ scheme.slug }}.vim
  supported-systems: [tinted8]
  supports:
    tinted8-builder: "~0.2.0"
    tinted8-styling: "~0.2.0"
